### ISSUE TITLE
🐛 Bug - Many documentation and Storybook links are broken

### ISSUE THREAD

**Issue by anilkk** [contentful/forma-36#1019]
# Forma 36 bug report

## Summary
Many documentation and Storybook links are broken. 
Example:
1. Design tokens link on Storybook website. https://github.com/contentful/forma-36/pull/1017
2. Link to IconButton Storybook component on Forma36 documentation website. https://github.com/contentful/forma-36/pull/1015

## Environment
Production

## Expected results
For a great experience, I would expect documentation website links to point to the right destination and should not contain any broken links. 

## Proposed Solution
Run **link checker** on published **Forma36 documentation** and **Storybook** websites. Integrate as part of the CI/CD process.  
You can use [Linkinator](https://www.npmjs.com/package/linkinator) npm package for crawling websites and validating links.

**Comment by suevalov** [comment]
I great suggestion to use an automatic link checker 👍🏼

**Comment by denkristoffer** [comment]
Can the name be extracted from Storybook somehow?

**Comment by suevalov** [comment]
We've implemented an automatic links checker so all links on the new Forma36 website should be valid.
