### ISSUE TITLE
🐛 Bug - some people can't merge PRs

### ISSUE THREAD

**Issue by gui-santos** [contentful/forma-36#1023]
# Forma 36 bug report

In some cases the `commit-check` does not run and blocks the PR

**Comment by mshaaban0** [comment]
Yeah this is due to the CircleCI settings.

Enabling it shows warning about exposing ENV variables to the public which includes sensitive data npm tokens, etc.

We need to find a way to do that securely

**Comment by denkristoffer** [comment]
@gui-santos so should this work now?

**Comment by denkristoffer** [comment]
The original issue here should be gone by now. There's a new problem with building the website which should be fixed in #2164
