### ISSUE TITLE
🐛 Bug - Autocomplete Text Input doesn't allow inputting text

### ISSUE THREAD

**Issue by SirGavin** [contentful/forma-36#1024]
# Forma 36 bug report

## Summary

In the latest version of Forma36, the text input rendered via the Autocomplete element doesn't allow the user to type in it.

## Environment

Have tested in Chrome/Firefox on mac and windows.

## Steps to reproduce

Issue can be reproduced using the Forma36 storybook: https://f36-storybook.contentful.com/?path=/story/components-autocomplete--basic

Clicking in the text input opens the dropdown and removes focus from the input

## Expected results

Allowing typing in the text input

## Actual results

Doesn't allow typing in the text input

**Comment by SirGavin** [comment]
Fixed by #1057

**Comment by denkristoffer** [comment]
@all-contributors please add @SirGavin for bug
