### ISSUE TITLE
🐛 Bug - HTML header elements(h1, h2, ...)  in the Paragraph component

### ISSUE THREAD

**Issue by anilkk** [contentful/forma-36#1030]
# Forma 36 bug report

## Summary
Semantically it's not recommended to use the header elements (h1, h2, h3, h4, h5, h6) in the [Paragraph](https://f36-storybook.contentful.com/?path=/story/typography-paragraph--basic) component. 
https://www.loom.com/share/f67e73b5e134471bbeed30f6ea261f86

**Comment by gui-santos** [comment]
That's on purpose!

I think we are mixing two concepts here, one is that we have a React component called "Paragraph"
But that's not its HTML function or anything, is just how we named that group of styles basically
So every paragraph will have, for example, `font-size: 14px`

The other thing is HTML semantics that has a bunch of non-enforced rules like we should have only one `h1` tag per page, or we should only have textual elements inside the `p` tag, and so on...

All that to say that even though the component is named Paragraph, it's just naming a group of styles that can be used with any textual HTML tag... It could have named it differently like "NormalText"

Check out this example of a design where everything should have the same styles but still semantically correct:

![example](https://user-images.githubusercontent.com/6597467/124453743-f7a45e80-dd87-11eb-87fc-6ec4bece9422.jpeg)

Another example of why we separate styling from the function is in our Accordion component, its header needs to be an HTML element with a heading role (h1, h2, h3, ...). We are using the Subheading styles there, but imagine if you have an accordion inside a section that already has an `h2`, then you can change the Subheading element to `h3` and a screen reader would be able to understand the hierarchy of the content

After saying all that, I agree that we still need to improve how we communicate these ideas and patterns so let's keep it registered here and we can create better documentation 🙌 

Thank you for bringing this up

**Comment by denkristoffer** [comment]
Maybe `<Paragraph />` should be named `<Text />`?

**Comment by suevalov** [comment]
For me, it was always confusing as well. I root for renaming `Paragraph` to `Text` as @denkristoffer suggested.
