### ISSUE TITLE
💡 Proposal - Divided button component for v4

### ISSUE THREAD

**Issue by burakukula** [contentful/forma-36#1049]
# Divided button component for v4

## The problem
Hey everyone!
I would like to discuss with you the introduction of the new component in v4. It's a more complex variant of the button.

![Screenshot 2021-07-08 at 12 51 48](https://user-images.githubusercontent.com/4272331/125044419-3bef7180-e09c-11eb-8fe0-a34182f5bc6a.png)

The button is already created as a custom component in production, it might be something that we would like to include in the library.

## The proposed solution

The component contains 2 buttons with 2 different actions, one opening the dropdown

<img width="359" alt="Screenshot 2021-07-09 at 10 01 12" src="https://user-images.githubusercontent.com/4272331/125045484-5544ed80-e09d-11eb-93f7-c723f8e380c9.png">

I guess props would be the same as in the case of the button, except for a couple of them, like `isDropdown`

## Open questions
 Naming of the component:
  - ButtonDivided
  - ButtonSplitted
  - ButtonWithDropdown
  - ???
  
## Breaking changes

v4

**Comment by suevalov** [comment]
I'd rather make it a composition of buttons:

```
<ButtonGroup>
   <Button>Click</Button>
   <Button>v</Button>
</ButtonGroup>
```

ButtonGroup can apply different variants:

1) `padded` - applies equal spacing between all buttons
2) `combined` - squashes button together into one group (as it's captured on the screenshot)

**Comment by domarku** [comment]
Thanks for the proposal @burakukula. I like "ButtonWithDropdown"

**Comment by domarku** [comment]
Possibly a bigger question, more of a design nature, but would it make sense to extend this proposal and implement as a button group? We could have multiple, e.g. up to three, buttons together and optionally with a dropdown. 

![Screen Shot 2021-07-09 at 17 03 01](https://user-images.githubusercontent.com/7631029/125098691-8b06c800-e0d7-11eb-8469-e1a483088edd.png)

**Comment by suevalov** [comment]
Regarding the naming for the button component, my proposal is `DropdownButton`. It makes sense for me to start the component name from `Dropdown` because it belongs to the Dropdown component logically and they both should be collocated.

**Comment by suevalov** [comment]
> Possibly a bigger question, more of a design nature, but would it make sense to extend this proposal and implement as a button group? We could have multiple, e.g. up to three, buttons together and optionally with a dropdown.
> 
> ![Screen Shot 2021-07-09 at 17 03 01](https://user-images.githubusercontent.com/7631029/125098691-8b06c800-e0d7-11eb-8469-e1a483088edd.png)

I agree, and it's aligned well with what I wrote above about `<ButtonGroup>` component

**Comment by denkristoffer** [comment]
I don't have much to add, just a big +1, especially the idea of doing it with `ButtonGroup`. Love it!
