### ISSUE TITLE
🐛 Bug - devault value of getContainerRef should use useCallback to avoid focus on every render when focusContainerOnOpen is true

### ISSUE THREAD

**Issue by OriginalEXE** [contentful/forma-36#1061]
# Forma 36 bug report

## Summary

DropdownContainer component uses `useEffect` to focus the container on mount when `focusContainerOnOpen` is set to true. The issue is that that `useEffect` has `getRef` as a dependency, and because `getRef` is by default set to `getContainerRef` which in turn is by default set to `() => {}`, the `useEffect` executes on every re-render because `() => {}` is not considered a stable dependency.

Default value for `getContainerRef` should instead be something like `useCallback(() => {}, [])` (so it's stable across re-renders) or even `undefined` and then we check if it's a function before calling it?

## Environment

All browsers

## Steps to reproduce

https://codesandbox.io/s/interesting-swanson-o8zyz?file=/src/App.js

## Expected results

Dropdown is not re-focused on every re-render when I don't provide `getContainerRef`.

## Actual results

Dropdown is re-focused on every re-render when `getContainerRef` is not provided.

**Comment by denkristoffer** [comment]
Thank you for taking the time to report this and especially for creating the reproduction @OriginalEXE! I've opened a PR with a fix.

@all-contributors please add @OriginalEXE for bug
