### ISSUE TITLE
🐛 Bug - Close dropdown on clicking outside

### ISSUE THREAD

**Issue by mshaaban0** [contentful/forma-36#1095]
## Summary

Currently one can open multiple dropdowns at the same time unless handled by the consumer. here is an example in launch app

<img width="1487" alt="Screenshot 2021-07-20 at 14 06 12" src="https://user-images.githubusercontent.com/6163988/126320936-8de70be0-7295-42bd-9b58-a6a154cef363.png">

<img width="618" alt="Screenshot 2021-07-20 at 14 04 30" src="https://user-images.githubusercontent.com/6163988/126320967-946db078-4028-41de-87e6-9b6f19c05a26.png">

I think we should close the dropdown if the user clicks anywhere out side, or at least provide an option to do so.

## Environment

All supported browsers

## Steps to reproduce

Have multiple dropdowns rendered in a single page, and try opening all of them

## Expected results

Dropdown should close on clicking out side its content

## Actual results

User can open multiple dropdowns at the same time

**Comment by suevalov** [comment]
@mshaaban0 This problem got fixed in v4 🎉
