### ISSUE TITLE
💡 Proposal - Don't set top:0 on table head cells when isSticky is false

### ISSUE THREAD

**Issue by OriginalEXE** [contentful/forma-36#1113]
# Forma 36 contribution proposal

## The problem

Currently, TableHead always sets value of `TableCellContext.Provider` to 0 by default (even when `isSticky` prop is false), and so `top: 0` style always gets applied to the cell via the style attribute, making it impossible to override without using `!important`.

## The proposed solution

I would suggest that `top: 0` (or any other top value) gets set only when the head is made sticky.

## Breaking changes

People potentially relying on `top: 0` always being set on table head cells might find their styles not working as expected if this behavior is changed.

**Comment by denkristoffer** [comment]
We probably don't want people to have to use `!important` to override any styles, but I'm curious if you can go into details of when or why you'd want to use different `top` values on a table head?

**Comment by OriginalEXE** [comment]
Sure,

In my case, I have a table that is in most cases wider than the screen, so there is horizontal scrolling. I want to make the first column (where I display entry titles) sticky horizontally, and so I apply `position: sticky; left: 0;` to it. However, because it also has `top: 0` applied by default, it will become sticky vertically as well, which is absolutely not something I want 😄 In that case, the only way to override that is to set `top: auto !important` in my css, hence this issue.

**Comment by gui-santos** [comment]
@OriginalEXE It seems to me that with your use case not only we need to do the change you proposed, but also implement a way to make the first column of the table fixed when necessary!

I think this is a good proposal, are you opening a PR for it?

**Comment by OriginalEXE** [comment]
I can create a PR :)

To your point about adding a feature for making the first column sticky, I would not mind it, but I did not have a problem doing it myself, other than this `top: 0` being forced on me. Not sure how often that use-case is.

**Comment by denkristoffer** [comment]
I think a small PR that just removes the `top: 0` enforcement is fine, we can add support for horizontal stickiness separately.
