### ISSUE TITLE
💡 Proposal - Dismiss modal on click outside of modal

### ISSUE THREAD

**Issue by danialnoaein** [contentful/forma-36#1157]
# Forma 36 contribution proposal

## The problem

Currently, When modal launched, it doesn't dismiss when user click outside of modal in dark area.

## The proposed solution

It can be solved with many ways. But I like [Bulma way](https://bulma.io/documentation/components/modal/).

`<div class="modal">`
`<div class="modal-background"></div>`
`<div class="modal-content"></div>`
`</div>`

Modal content load in `modal-content` that is top of `modal-background`. Then, when user click on `modal-background`, whole modal will dismiss.

**Comment by suevalov** [comment]
Hey, @danialnoaein! We have a controlled property `shouldCloseOnOverlayClick` which equals true by default. And, by default, modal is getting closed once you click on the overlay: [see in action](https://f36-storybook.contentful.com/?path=/story/components-modal--default)

Does it work for you?

**Comment by danialnoaein** [comment]
Hi. Yeah it's work for me in storybook. But I saw it in [documentation](https://f36.contentful.com/components/modal/).

**Comment by suevalov** [comment]
I see, I guess the bug happens because all examples are rendered within the iframe... We'll take a look at this. If you use Modal dialog in your application, it will have close-on overlay functionality out of the box. 

So, I'm closing this proposal, since we have it already.
