### ISSUE TITLE
💡 Proposal - dropdown refactoring

### ISSUE THREAD

**Issue by bgutsol** [contentful/forma-36#1164]
# Forma 36 contribution proposal

## The problem

At the moment we have variety of implementation with dropdown within different apps. They are not consistent, do not pass a11y rules, and hard to maintain because of custom complex logic.
The list of examples of current Dropdown usage:

1. Two places where we create custom `MultiSelect` component based on `Dropdown`: 
    - [first](https://github.com/contentful/user_interface/blob/f1874983b0a3e366836f0aaf3d72b61f8d5b39a7/src/javascripts/app/entry_editor/EntryReferences/MultiSelect/MultiSelect.tsx#L92)
    - [second](https://github.com/contentful/user_interface/blob/d390b23ee149c38b68802d608b151578e81f10f1/src/javascripts/app/OrganizationSettings/SpaceRoleEditor.js#L122)
 
![Screen Shot 2021-08-20 at 17 04 19](https://user-images.githubusercontent.com/7631029/130253767-5c274e3a-1101-423f-942b-a7bb8551b764.png)

2. Two places where we changing default `click` event as a trigger to `hover`: 
    - [first](https://github.com/contentful/user_interface/blob/d390b23ee149c38b68802d608b151578e81f10f1/src/javascripts/app/entity_editor/Components/FetchLinksToEntity/LinkedEntitiesBadge.js#L84), 
    - [second](https://github.com/contentful/creator-app-mvp/blob/54ce1619d3e097d81b3c2a2a7dd11cb8a2b12c88/src/features/page-editing-common/components/EntityReuseCounter/EntityReuseCounter.tsx#L82)

![Screen Shot 2021-08-20 at 17 05 40](https://user-images.githubusercontent.com/7631029/130253917-a31d36e7-bb70-418b-bb8b-aebde866936a.png)

3. Several places where we use `DropdownList` without `Dropdown`, and `CardActions` without `Card` components: 
    - [first](https://github.com/contentful/user_interface/blob/324c705288c750f3740ec4efc46175860770390b/src/javascripts/app/EntrySidebar/TasksWidget/View/Task.js#L169)
    - [second](https://github.com/contentful/user_interface/blob/043abbd930a993c99e78799a0539f43a3653e31f/src/javascripts/app/OrganizationSettings/Users/UserDetail/UserSpaceList.js#L91)
    - [third](https://github.com/contentful/user_interface/blob/f04dab65a553ed5c430c29100530d04fb19613c7/src/javascripts/app/OrganizationSettings/Users/UserDetail/UserTeamList.js#L106)
    - [fourth](https://github.com/contentful/content-planning-app/blob/2c0f5f03acdfe57fb31f3ecf4994c9a5af80e68b/src/features/releases-list/components/ReleaseDetails/ReleaseDetailsAppHeader.tsx#L206)

![Screen Shot 2021-08-20 at 17 07 00](https://user-images.githubusercontent.com/7631029/130254036-4f59591a-7bdf-41f9-8749-64aa3d653fe5.png)

4. Places where we use `Dropdown` as a select: 
    - [first](https://github.com/contentful/user_interface/blob/70b48725b58b833cd35c7309d6b18e40fb927388/src/javascripts/app/SpaceSettings/EnvironmentAliases/ChangeEnvironmentModal.js#L180)
    - [second as a `Timepicker` with input as a trigger elem](https://github.com/contentful/user_interface/blob/06373a2d5b6fd749cbd561495a287a34e9cc48cb/src/javascripts/app/ScheduledActions/EntrySidebarWidget/ScheduledActionDialog/TimePicker/index.js#L174)
    - [third as a `Timepicker` in Launch](https://github.com/contentful/content-planning-app/blob/66533ee9e7174036af27f33a616114d5a75c882f/src/core/components/Datetime/TimePicker.tsx#L254) 

![Screen Shot 2021-08-20 at 17 07 42](https://user-images.githubusercontent.com/7631029/130254113-746b28f5-e568-4dbe-a95a-20e9ac9562a6.png)

5. There are some places where we can put all sort of content inside dropdown: 
    - [Table with a TableCell to trigger an action](https://github.com/contentful/user_interface/blob/d390b23ee149c38b68802d608b151578e81f10f1/src/javascripts/app/snapshots/SnapshotSelector.js#L124)
    - [second with text and simple `Buttons`](https://github.com/contentful/user_interface/blob/98b34b5c504c6090cb16d01f21375b516f5aeb5c/src/javascripts/features/api-keys-management/api-tokens/RevokeButton.js#L30)

![Screen Shot 2021-08-20 at 17 08 36](https://user-images.githubusercontent.com/7631029/130254284-19d22fee-6570-4c99-84ea-8868c69c551b.png)

### Other interesting things:
1. In 90% of the use cases we repeat the same simple logic to open/close a dropdown when `triggerElem` clicked. Sometimes there are additional callback passed, like [here](https://github.com/contentful/user_interface/blob/d390b23ee149c38b68802d608b151578e81f10f1/src/javascripts/app/snapshots/SnapshotSelector.js#L119). Maybe it's worth to make component `uncontrolled` by default?

1. Place where we use `span` as a trigger element: [span](https://github.com/contentful/user_interface/blob/5b94be3dac05f835632081607fa837e5a4676f40/src/javascripts/app/EntrySidebar/ContentPreviewWidget/SidebarContentPreview.js#L66)

## The proposed solution

1. Do a base component, `Dropdown` or `Popover` (_popover_ is a more common name based on other popular components libraries). 
    - Component should be also exposed, since it will be used as a one for a custom content. So it will just trap focus inside dropdown, when it's opened, and use default tab navigation within its content (focusTrapping should be optional prop).
    - Trigger element should be wrapped and passed as one of the children, not as a prop. It will introduce more flexibility for the trigger element and we will not have such cases, [when the props that we pass on `toggleElement` end up on the wrong 	element](https://github.com/contentful/content-planning-app/blob/66533ee9e7174036af27f33a616114d5a75c882f/src/core/components/Datetime/TimePicker.tsx#L262).  Example:
    ```jsx
    // current
    <Dropdown toggleElement={<Button>Toggle<Button/>}>
    <DropdownContent>{...}</DropdownContent>
    </Dropdown>
    
    // new proposal
    <Dropdown>
    <DropdownTrigger><Button>Toggle<Button/><DropdownTrigger/>

    <DropdownContent>{...}</DropdownContent>
    </Dropdown>
    ```
    - Component will use https://popper.js.org/ as our current implementation.

1. Based on prev basic component we will create more specific one:
    - `Autocomplete`. Refactor the current one to make it follow [a11y combobox rules](https://www.w3.org/TR/wai-aria-practices/#combobox). I'd propose to use https://www.downshift-js.com/use-combobox in order to not spend too much time on it.
    - `Menu` which will cover 70% percent of use cases. With correct a11y and clear usage guide. This component will cover two most common cases: as a [navigation menu](https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html#) and as an [actions manu](https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-2/menubar-2.html).
    - `Multiselect`. We can also use [downshift](https://www.downshift-js.com/use-multiple-selection). Or create smth simple on our own.

1. I would argue that we need also `Select` component based on `Dropdown`. With clear design/usage guidance. We will probably use mostly `Menu` component or our native `Select` (from forms elements).

1. Make `Menu` component uncontrolled by default. So no need to repeat the same logic of togling by click. And also less temptation to introduce some custom logic, like open on hover.

1. For `Menu` and `Autocomplete` (and `Select` if we decided to do it) components make default behaviour where dropdown close itself when option clicked/chosen. Since it's a [recommended behaviour by w3c](https://www.w3.org/TR/wai-aria-practices/#keyboard-interaction-12) and I already found this approach in couple of places in our codebase [example](https://github.com/contentful/content-planning-app/blob/2c0f5f03acdfe57fb31f3ecf4994c9a5af80e68b/src/features/entry-preview/PreviewComponent.tsx#L97)

1. If it possible, we can also expose the logic with keyboard navigation through menu items as a hook. So when someone needs to do some very custom menu they can use raw `Dropdown` and our hook for custom menu list.

1. Since I didn't find any usage of dropdown nested menus in out projects, I think we can drop support of it.

### Additionally

We also have some inconvenient behaviour with dropdown in the iframe. For example when we use dropdown in our entry field iframe, the iframe does not adapt to the open dropdown height. 
![field_editor](https://user-images.githubusercontent.com/10744462/128640430-82372ac8-e90b-45a9-a4b6-f895504a2555.gif)
So I propose to add specific data attribute on our dropdown and add [this code to updateHeight method](https://github.com/contentful/ui-extensions-sdk/pull/901).
We can also add this attribute for others absolute positioned element that we want to be counted. So it's not limited only to the dropdowns.

------

SO WDYT? 🤔

**Comment by suevalov** [comment]
First of all, amazing detailed write-up!

I agree with the proposal in general.

1. I would probably rename Dropdown to Popover to make it clear that Dropdown is not the same anymore and most likely you should use Menu to replace the Dropdown.
2. Are you sure that we don't have a multi-level Menu? I'm pretty sure that we had one in Compose. Is it gone now? 
3. Interesting approach with data attributes in ui-extensions-sdk. I couldn't understand how it would work from looking at the code, so I'd be interested in seeing a demo.

**Comment by thebesson** [comment]
awesome, very in-depth research! 
I have one question regarding this point:
>3. I would argue that we need also Select component based on Dropdown. With clear design/usage guidance. We will probably use mostly Menu component or our native Select (from forms elements).
It is a bit unclear for me from the wording, do you propose to just make a `Select` based on this base component `Popover` and also keep native select from form components?

**Comment by gui-santos** [comment]
Amazing research! Here are my 2 cents:

> 1. Do a base component, Dropdown or Popover (popover is a more common name based on other popular components libraries).

YES! Let's create a `Popover` component

>Based on prev basic component we will create more specific one:
>
> 2. Autocomplete. Refactor the current one to make it follow a11y combobox rules. I'd propose to use https://www.downshift-js.com/use-combobox in order to not spend too much time on it.
> Menu which will cover 70% percent of use cases. With correct a11y and clear usage guide. This component will cover two most common cases: as a navigation menu and as an actions manu.
> Multiselect. We can also use downshift. Or create smth simple on our own.

Yes to refactor `Autocomplete` and make it use the soon to be created `Popover` (if it makes sense, maybe we don't need it).
`Menu` component makes total sense, Idk about the name but hey naming is the hardest part in software development.
Now, I'm not convinced we need a `Multiselect` component because, in my head, that's just the Menu component with CheckboxField as children. Since the developer can define how the items in the `Menu` component looks like, for me this `Multiselect` wouldn't be a component, but a good example in our documentation

I imagine something like this:
```jsx
<Menu>
  <Menu.Trigger>Click me to open<Menu.Trigger/>
  <Menu.Content>
    <CheckboxField labelText="Option 1" {...} />
    <CheckboxField labelText="Option 2" {...} />
  <Menu.Content/>
</Menu>
```

> 3. I would argue that we need also Select component based on Dropdown. With clear design/usage guidance. We will probably use mostly Menu component or our native Select (from forms elements).

I agree we need two components, but I think `Select` is not based on the Dropdown/Menu component. `Select` is an form input and Dropdown/Menu is just an UI element

And based on that, I actually think that the 4th example you gave (the one where we are using the dropdown as an input) is wrong implementation and we should maybe improve our documentation and guides

> 4. Make Menu component uncontrolled by default. So no need to repeat the same logic of togling by click. And also less temptation to introduce some custom logic, like open on hover.

Yes!

> 5. For Menu and Autocomplete (and Select if we decided to do it) components make default behaviour where dropdown close itself when option clicked/chosen. Since it's a recommended behaviour by w3c and I already found this approach in couple of places in our codebase example

Yes! x10

> 6. If it possible, we can also expose the logic with keyboard navigation through menu items as a hook. So when someone needs to do some very custom menu they can use raw Dropdown and our hook for custom menu list.

Uhmmm 🤔  interesting! I think it will be easier for me to visualize it if we make an experiment of this

> 7. Since I didn't find any usage of dropdown nested menus in out projects, I think we can drop support of it.

Let's ask @domarku about this

> So I propose to add specific data attribute on our dropdown and add this code to updateHeight method.
> We can also add this attribute for others absolute positioned element that we want to be counted. So it's not limited only to the dropdowns.

Great solution!

🍪

**Comment by bgutsol** [comment]
> awesome, very in-depth research!
> I have one question regarding this point:
> 
> > 1. I would argue that we need also Select component based on Dropdown. With clear design/usage guidance. We will probably use mostly Menu component or our native Select (from forms elements).
> 
> It is a bit unclear for me from the wording, do you propose to just make a `Select` based on this base component `Popover` and also keep native select from form components?

Thanks @thebesson 

Sorry for the bad wording. I meant that that we probably don't have to create a `Select` component that will be based on the popover. Because the cases that we have in the 4th example can be covered with `Menu` component or with our native select from form components. As @gui-santos said it's just the matter of better guidelines and documentation.

**Comment by thebesson** [comment]
Thanks, @bgutsol, I understand now! You are right, I agree on this one too.

**Comment by bgutsol** [comment]
@gui-santos Thanks for the feedback!

> Now, I'm not convinced we need a Multiselect component because, in my head, that's just the Menu component with CheckboxField as children. Since the developer can define how the items in the Menu component looks like, for me this Multiselect wouldn't be a component, but a good example in our documentation

I just don't want to mix this two components because they have totally different use cases. They also have some different tech implementation, the `role` for each item for example, some keyboard navigation differences. But we can revisit it for sure when we dig deeper into each component and see that we easy can merge them.

> (As you can see, I'm also in favor of creating Menu with the . pattern for its children components. How do we call this React pattern? I forgot)

I also love this approach, but based on what we already have in v4 we are not using such style, right? Maybe it's something that we need to discuss and agree upon asap?

> I agree we need two components, but I think Select is not based on the Dropdown/Menu component. Select is an form input and Dropdown/Menu is just an UI element
And based on that, I actually think that the 4th example you gave (the one where we are using the dropdown as an input) is wrong implementation and we should maybe improve our documentation and guides

Agree 🙂

**Comment by bgutsol** [comment]
> Are you sure that we don't have a multi-level Menu? I'm pretty sure that we had one in Compose. Is it gone now?
@suevalov I double checked but I couldn't find any signs of multi-level Menu in Compose. I've asked @djagya he also couldn’t find any 🤷‍♂️

**Comment by suevalov** [comment]
@bgutsol then it's either my broken brain, or it was deleted indeed :) I guess it's good news then

**Comment by denkristoffer** [comment]
This looks really interesting, please give me today and tomorrow to read this in-depth 🙏

**Comment by denkristoffer** [comment]
Ok, some thoughts:

> Make Menu component uncontrolled by default. So no need to repeat the same logic of togling by click. And also less temptation to introduce some custom logic, like open on hover.

I think we need to standardise this and do the same thing throughout Forma 36. Menu should not differ from the behaviour of other components.

> Since I didn't find any usage of dropdown nested menus in out projects, I think we can drop support of it.

Pretty sure we have submenus in Compose, but not a Dropdown in a Dropdown, if that's what you mean?

> We also have some inconvenient behaviour with dropdown in the iframe. For example when we use dropdown in our entry field iframe, the iframe does not adapt to the open dropdown height. So I propose to add specific data attribute on our dropdown and add this code to updateHeight method.

This seems complicated if we can just use portals instead. Is there any advantage to doing it this way?

**Comment by bgutsol** [comment]
Hey @denkristoffer thanks for the feedback!

> I think we need to standardise this and do the same thing throughout Forma 36. Menu should not differ from the behaviour of other components.

I'm with you on this one if we see that other components also are used mostly with a simple controlled logic.

> Pretty sure we have submenus in Compose, but not a Dropdown in a Dropdown, if that's what you mean?

To create submenus we have to put Dropdown in a Dropdown, based on [an example in our F36 storybook](https://github.com/contentful/forma-36/blob/d5f62d7ce5e3d2a87d79d711254944e21b0e0719/packages/forma-36-react-components/src/components/Dropdown/Dropdown.stories.tsx#L51) Could you point me please where we use submenus in Compose? 

> This seems complicated if we can just use portals instead. Is there any advantage to doing it this way?

We use portals. But how portals can help us to solve that issue? Could you clarify it for me, please?

> I think Autocomplete and a Select/MultiSelect can be combined into one component that takes all these configuration props, maybe reexported under different names with different defaults. I see that there are design differences between them, but conceptually they seem similar to me.

I'm not against unifying similar logic. But for me Autocomplete and MultiSelect don't seem like the same components with the different configuration props. My approach would be to create two separate components and then merge them if I see that they are similar. But if anyone else would do it in one component and it will not become a monster that's hard to use and support, I'm totally fine 👍

**Comment by denkristoffer** [comment]
I did some thinking on how I would do a `Menu` with submenus. Assuming we have a `Popover` component that does the heavy lifting I would go for an API like this in the `Menu` component: 

```
<Menu>
  <MenuItem label="this is a submenu toggle">
    <MenuItem label="Click me />
  </MenuItem>
  <MenuItem label="No submenu" />
</Menu>
```

It´s up to `Menu` to position the children with the submenu properly, which means that we can check for outside clicks from the root element, instead of having to deal with different root elements like the current dropdown API.



---

> We use portals. But how portals can help us to solve that issue? Could you clarify it for me, please?

Maybe I'm misunderstanding something here, do you want to adapt the iframe height for a reason other than the dropdown being cut off by the iframe? A portal should append the dropdown to the DOM outside the iframe and allow it to be shown in full.

**Comment by bgutsol** [comment]
@denkristoffer 
Agree with the `Menu` submenu implementation.

> Maybe I'm misunderstanding something here, do you want to adapt the iframe height for a reason other than the dropdown being cut off by the iframe? A portal should append the dropdown to the DOM outside the iframe and allow it to be shown in full.

Yes, the iframe doesn't adjust its height when you open dropdown inside it, this is the main reason.
I'm not sure that it's possible to render dropdown outside of the iframe using portals. Am I missing something?

**Comment by denkristoffer** [comment]
>  I'm not sure that it's possible to render dropdown outside of the iframe using portals. Am I missing something?

I think it is 🤔 I can investigate.
