### ISSUE TITLE
v4: Add eslint rule to warn about old colour scheme

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#1198]
# Forma 36 contribution proposal

I propose we add a custom eslint rule to warn about places where the old colour tokens are used.

**Comment by gui-santos** [comment]
Yes! x100

**Comment by burakukula** [comment]
@denkristoffer hey! Just wanted to check if it's still a valid ticket. Did you mean the eslint role on the client side? If so, I think we already have it.
<img width="703" alt="Screenshot 2022-06-02 at 09 05 05" src="https://user-images.githubusercontent.com/4272331/171572755-1dbf72d3-9ebc-4e26-8000-c7cc49d10453.png">

**Comment by denkristoffer** [comment]
@burakukula I'd say it's still valid, the `@deprecated` tag relies on the editor and types, what I'd like is a linting rule to catch all these cases, so we can enable it in the web app.
