### ISSUE TITLE
🐛 Bug - Autocomplete unexpected behavior on keyboard navigation

### ISSUE THREAD

**Issue by OriginalEXE** [contentful/forma-36#1232]
# Forma 36 bug report

## Summary

Hello, I would like to report a bug and propose a change in keyboard handling of the Autocomplete component.

Steps to reproduce the bug:
Use `Tab` to focus the autocomplete field - dropdown opens
Select one of the choices using the arrows and press enter - dropdown closes
Use `Tab` or `Shift + Tab` to focus next/previous element on the page - **dropdown opens**

The last dropdown open should not happen.

Separately but related, I would suggest that the dropdown opens not on focus but only on `ArrowUp` or `ArrowDown` key press. This would be consistent with native elements like select and also [input + datalist](https://codepen.io/cferdinandi/pen/wvargYL).

## Environment

Latest Microsoft Edge, reproduced on the official [docs](https://f36.contentful.com/components/autocomplete/) for the component.

## Steps to reproduce

Use `Tab` to focus the autocomplete field - dropdown opens
Select one of the choices using the arrows and press enter - dropdown closes
Use `Tab` or `Shift + Tab` to focus next/previous element on the page - **dropdown opens**

## Expected results

Autocomplete suggestions dropdown is hidden when I navigate away from the field.

## Actual results

Autocomplete suggestions dropdown is visible when I navigate away from the field.

**Comment by gui-santos** [comment]
Hey so @Lelith will take this

She is working on Autocomplete right now
but we might solve this bug only in v4 which should come soon 👀

**Comment by suevalov** [comment]
@OriginalEXE The problem got fixed in v4 🎉
