### ISSUE TITLE
Constant propType warning in custom UI Extension

### ISSUE THREAD

**Issue by svandersteene** [contentful/forma-36#137]
I'm developing a custom UI extension in which I am using the Forma 36 React Components.
I'm constantly getting the following warning/error;

<img width="902" alt="image" src="https://user-images.githubusercontent.com/33860193/54525786-43dbf280-4975-11e9-9576-4acf3cf34d88.png">

How should I handle this, 'cause it's a warning/error inside a component that gets automatically generated by the Note-component that I'm using?

**Comment by m10l** [comment]
@svandersteene Hey, thanks for raising this issue! I'll create a fix shortly and let you know once it's available in master

**Comment by m10l** [comment]
@svandersteene This is now available in [v2.10.0](https://github.com/contentful/forma-36/releases/tag/%40contentful%2Fforma-36-react-components%402.10.0). Thanks again for reporting!

**Comment by svandersteene** [comment]
> @svandersteene This is now available in [v2.10.0](https://github.com/contentful/forma-36/releases/tag/%40contentful%2Fforma-36-react-components%402.10.0). Thanks again for reporting!

I changed to this newer version, but I still get these errors, now on an other component;

<img width="894" alt="image" src="https://user-images.githubusercontent.com/33860193/54538033-d1c6d600-4993-11e9-9a5c-f488e6996d03.png">
<img width="580" alt="image" src="https://user-images.githubusercontent.com/33860193/54538376-70ebcd80-4994-11e9-88a1-1bc793cf5939.png">

The above is my code where I use a SelectField with 2 Option-components in it.

**Comment by suevalov** [comment]
@m10l Looks like `labelText` is a required property but it is not marked as required. right?

**Comment by m10l** [comment]
> @m10l Looks like `labelText` is a required property but it is not marked as required. right?

Yes, this should be a required prop. @svandersteene - If you want to render a Select without a label I'd recommend just using the `Select` component

**Comment by svandersteene** [comment]
@m10l Thanks you for the quick responses. That did the trick indeed.
