### ISSUE TITLE
Possibility to override forma 36 styles

### ISSUE THREAD

**Issue by svandersteene** [contentful/forma-36#142]
I am creating a Contentful UI extension and I'm using the forma-36-react-components and its styles. I am using Select-component and a Note-component underneath eachother, but that gives me the following result:

<img width="808" alt="image" src="https://user-images.githubusercontent.com/33860193/54699185-db397500-4b30-11e9-83b8-1b76deabce52.png">

I would like some margin between these components, but I haven't been able to override these styles.

**Comment by m10l** [comment]
Hi @svandersteene - If you're also using our fcss library (https://github.com/contentful/forma-36/tree/master/packages/forma-36-fcss), you can add extra classnames to a component like so:

```jsx
<Select extraClassNames="f36-margin-bottom--m">
  <Option value="a">Option A</Option>
  <Option value="b">Option B</Option>
</Select>
<Note>My note</Note>
```

You can of course also assign your own class names for spacing here, however we'd recommend using FCSS as it uses values taken from our design system (see our [spacing tokens](https://f36-storybook.contentful.com/?path=/story/tokens-spacing--default) for a visualisation of our spacing values).

**An important note** - we are [preparing a v3 release](https://github.com/contentful/forma-36/pull/139) of our component library which will contain a breaking change relating to this code snippet. The `extraClassNames` prop will be removed in favour of simply using `classNames` to merge external class names with component internal class names.

Once you upgrade to the v3 version of Forma 36 React Components, the code snippet would be as follows:

**V3 solution**
```jsx
<Select className="f36-margin-bottom--m">
  <Option value="a">Option A</Option>
  <Option value="b">Option B</Option>
</Select>
<Note>My note</Note>
```

**Comment by svandersteene** [comment]
@m10l Alright, perfect answer, thank you!
I was using `className` , I guess that's why it didn't work.

**Comment by svandersteene** [comment]
@m10l so, your solution was indeed great, but if I try to apply some grid or flex on a container, then some components are breaking (picture)

<img width="887" alt="image" src="https://user-images.githubusercontent.com/33860193/54753890-763e5780-4be2-11e9-9d5b-b08855842389.png">

I applied a 2x2 grid, but for some reason, the dropdown button breaks.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/33860193/54753964-a554c900-4be2-11e9-9860-eef3b80f6950.png">

**Comment by m10l** [comment]
@svandersteene Are you able to provide a full example of this? You should be able to fork https://codesandbox.io/s/04o53z4ynv for ease of setting up dependencies

**Comment by svandersteene** [comment]
@m10l https://codesandbox.io/s/jjzr79z05v , does this work for you?

**Comment by m10l** [comment]
@svandersteene Ah okay. So I'd suggest using wrapper divs for this. Maybe this would work as a bare minimum for what you want to achieve?

```jsx
<div className="selection">
  <Select extraClassNames="f36-margin-bottom--m">
    <Option value="optionOne">Option 1</Option>
    <Option value="optionTwo">Long Option 2</Option>
  </Select>
</div>
<Note extraClassNames="note">Test</Note>
<AssetCard
  extraClassNames="asset"
  src="https://placekitten.com/200/300"
/>
```

We don't really support laying out components like this though. At some point we plan to work on layout guidelines and I imagine we will provide a set of components for abstracting layout. We have a little bit of information surrounding component principles in our readme which mentions spacing.

> **1. A component is responsible for only its internal spacing**
> 
> We follow the principle that a component should only be responsible for its own internal spacing - never external spacing. This means that we're flexible in where our components can be used without having to override margins.

(From https://github.com/contentful/forma-36/tree/master/packages/forma-36-react-components#component-principles)

**Comment by m10l** [comment]
I'll mark this issue as closed for now - I think it's maybe more of a general CSS question than a direct issue with Forma 36. Let us know if you have any other issues though!
