### ISSUE TITLE
TextField: characters count is not updated when value is set programmatically

### ISSUE THREAD

**Issue by suevalov** [contentful/forma-36#143]
![count bug](https://user-images.githubusercontent.com/3672221/54755307-0336e000-4be6-11e9-9362-af90ac8c8dfd.gif)

**Comment by wichniowski** [comment]
Hey @suevalov are you directly setting the value of that input?

**Comment by wichniowski** [comment]
cosed with https://github.com/contentful/forma-36/pull/173
