### ISSUE TITLE
Forma 36 tokens type definition doesn't line up with actual export

### ISSUE THREAD

**Issue by Tsmith18256** [contentful/forma-36#144]
The type definition for `@contentful/forma-36-tokens` states that `tokens` is a default export, which leads the TS compiler to expect `import tokens from '@contentful/forma-36-tokens';` to be the syntax, but this fails at runtime. The correct syntax to make the app run is `import * as tokens from '@contentful/forma-36-tokens';`, but that causes a compiler error because of the type definition.

**Comment by wichniowski** [comment]
Hey @Tsmith18256 thanks for opening this issue, we'll resolve this asap!
For the time being my suggestion would be to `allowSyntheticDefaultImports` in your `tsconfig`.

**Comment by wichniowski** [comment]
Hey @Tsmith18256 this has been resolved with @contentful/forma-36-tokens@0.2.3
Thanks for opening the issue!
