### ISSUE TITLE
🐛 Bug - Forma 36 React - Tables that are not forma 36 components change colour on hover.

### ISSUE THREAD

**Issue by samgoulden28** [contentful/forma-36#1451]
# Forma 36 bug report

## Summary

Hovering over any TD element in tables that are not forma 36 components changes their background color to white. This is particularly frustrating as I am attempting to build a contentful UI extension making use of the fullcalendar npm module. 

Due to the rules: 

`tr:hover td:not(.TableCell__TableCell--head___3AHws){background-color:#f7f9fa}.`

and 

`tr:hover td:not(.TableSortingLabel__TableCell--head___yxhXj){background-color:#f7f9fa}`

Hovering over any TD element, even those that are not related to forma 36, will change their background color to #f7f9fa.

https://codesandbox.io/s/epic-mccarthy-yoezd?file=/src/App.js

## Environment

```
"@contentful/forma-36-react-components": "^3.98.4",
"@contentful/forma-36-tokens": "^0.9.4",
```

Chrome Version 94.0.4606.81 (Official Build) (x86_64)

## Steps to reproduce

See code sandbox https://codesandbox.io/s/epic-mccarthy-yoezd?file=/src/App.js

## Expected results

I expect only forma 36 components to adhere to this css rule.

## Actual results

I expected background colour of TDs not to change

**Comment by Lelith** [comment]
@denkristoffer is there still a fix planned for this or can we close this?

**Comment by nawed2611** [comment]
Hey, Can I work on this issue?

**Comment by nawed2611** [comment]
I suppose [this](https://github.com/contentful/forma-36/blob/main/packages/components/table/src/TableRow.tsx) is the file that needs changing

**Comment by nawed2611** [comment]
I'll create a PR for this

**Comment by denkristoffer** [comment]
Although this bug is still valid I'll go ahead and close this issue as the v3 package is not maintained by Contentful anymore. We're still happy to accept external contributions for this issue though!
