### ISSUE TITLE
🐛 Bug - Note styles override link button colours

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#1848]
# Forma 36 bug report

## Summary

<img width="453" alt="Screenshot 2022-02-02 at 14 16 09" src="https://user-images.githubusercontent.com/219017/152161366-4dab0dce-f5a9-4741-a90c-0d06532f3f6c.png">

If you render a `<Button as="a" />` in a Note, the Note variant styles are currently overriding the button's colour because of this line: https://github.com/contentful/forma-36/blob/0e528bed1942e8b4268ec68f2e2fad67f3389f42/packages/components/note/src/Note.styles.tsx#L14-L16

Is there a way we can select something like `a:not(our-button-component)`?

**Comment by gui-santos** [comment]
Is this a bug or a design implementation issue? @domarku 
my question is: do we want a link that looks like a button inside a note?

Also, just looking by the code, it seems that the intention here was to change the color of the link depending on the variant of the Note

I would say the easiest way to "fix" this is to change the styles in the Button component to enforce it to keep the white color when it has `as="a"`

**Comment by denkristoffer** [comment]
>  my question is: do we want a link that looks like a button inside a note?

I would say we do, we use it quite a few places where we want an obvious primary action inside a note, like these EAP signups. I don't think a TextLink is eye-catching enough for that.

**Comment by denkristoffer** [comment]
@gui-santos 

> I would say the easiest way to "fix" this is to change the styles in the Button component to enforce it to keep the white color when it has as="a"

How would you do this?

**Comment by denkristoffer** [comment]
@gui-santos Ping 🙂

**Comment by Lelith** [comment]
@denkristoffer should we close this? I do not think we can fix it without removing the general rule for links in the note.styles this is one of the big downsides of css-in-js imho. If we would have proper class names we could prevent the button style from beeing overwrittin by hooking on the generic button class :(
