### ISSUE TITLE
💬  Feedback - Getting started

### ISSUE THREAD

**Issue by mhaneef50673** [contentful/forma-36#1878]
Sandbox Code Example is not working

<img width="849" alt="image" src="https://user-images.githubusercontent.com/31245872/153349225-8c62402c-88b8-4f89-b057-9fd61ed334b3.png">

**Comment by domarku** [comment]
Hi @mhaneef50673, thanks for submitting this issue!

I took a look now and it seems the embedded Codesandbox example on the website works:
https://f36.contentful.com/getting-started#try-out-forma-36-in-the-codesandbox

The same example works when you open it in Codesandbox:
https://codesandbox.io/s/contentful-forma-36-template-v4-x-x-k78l0?from-embed

Could you give us a bit more context? For example, how did you navigate to the example?

**Comment by denkristoffer** [comment]
Hey @mhaneef50673 👋 

I'm going to close this issue, but please feel free to re-open it if you're still experiencing problems.
