### ISSUE TITLE
💡 Proposal - Allow to edit which heading element is used in components

### ISSUE THREAD

**Issue by YvesRijckaert** [contentful/forma-36#1879]
# Forma 36 contribution proposal

## The problem

When using the EntryCard component, I wanted to change the heading element from h1 to h3. But this does not seem possible right now.

https://github.com/contentful/forma-36/blob/1f3b3eb71e2c22efced2ae64e2528f027fb47504/packages/components/card/src/EntryCard/EntryCard.tsx#L36

## The proposed solution

Being able to change the heading element with a prop.

**Comment by YvesRijckaert** [comment]
I can create a PR for this, just checking if it would be okay to do so.

**Comment by burakukula** [comment]
Hey @YvesRijckaert! Sorry for the delay. I think it totally makes sense, I would even say that we have a bug right now, since it might actually create an incorrect structure. We should consider changing the default to something different than `h1`, but yeah, allowing the setting up of the tag here would be great and changing the default maybe. If you have some time to create a PR it would be great.

**Comment by denkristoffer** [comment]
Rendering the `h1` shouldn't be a problem when it's inside `article`.

**Comment by YvesRijckaert** [comment]
@denkristoffer I think we use this component in a lot of places, and often we would need more flexibility when it comes to which heading element to use.. I ran into this issue when using this component in compose.
But for example here in the web app an h2 or h3 would be more appropriate:
![Screenshot 2022-02-14 at 14 31 48](https://user-images.githubusercontent.com/22968325/153873658-02549edf-de01-47ed-814a-c69e7ba2c12e.png)

**Comment by denkristoffer** [comment]
I am all for being able to change the element. I wanted to add information that `article` should create a new heading context which would mean using a `h1` in one should be fine. However, this discussion made me double check, and [it looks like this behaviour was never actually implemented in browsers](https://html5accessibility.com/stuff/2021/03/21/a-decade-a-year-of-heading-backwards/) even though the spec says it's fine 😱

**Comment by massao** [comment]
> I am all for being able to change the element. I wanted to add information that `article` should create a new heading context which would mean using a `h1` in one should be fine. However, this discussion made me double check, and [it looks like this behaviour was never actually implemented in browsers](https://html5accessibility.com/stuff/2021/03/21/a-decade-a-year-of-heading-backwards/) even though the spec says it's fine 😱

Didn't know that the browsers didn't implement this, good to know.
But IMHO even if it was implemented we should also give the option to change the heading, since we give the option to change the tag used as wrapper of the EntryCard and other components

**Comment by denkristoffer** [comment]
Coming back to this, I guess an API that fits with our existing guidelines would be something like passing an object to `headingProps`, which can then contain the `as` key?

```tsx
<Card headingProps={{ as: 'h3' }} />
```

What do you think?

**Comment by Lelith** [comment]
this was fixed
