### ISSUE TITLE
💡 Proposal - Less prominent `Note` variant

### ISSUE THREAD

**Issue by fabe** [contentful/forma-36#1921]
# Forma 36 contribution proposal

## The problem

`Note`s are used frequently in our products, mostly the `primary` (blue) variant. It's visually quite a prominent element, yet not always is the information crucial to completing the task at hand. Additionally, we use blue as our primary interaction color, so a regular `Note` draws even more unnecessary attention.

High-level comparison of how prominent a low-priority `Note` can be:

![comparison](https://user-images.githubusercontent.com/5220692/156411536-322725bc-7b02-4d18-a624-a4ffd763d934.png)

## The proposed solution

We introduce a new variant (default, `info`, `neutral`, etc.), taking on grays/white for the background and border colors. I would do one of gray or white—currently, I'd lean towards gray, as it should work best for our use cases.

![image](https://user-images.githubusercontent.com/5220692/156413219-86962e9f-12a3-4874-a966-b3ded73c05ce.png)

[Playground with some hacky styles](https://f36.contentful.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwAQCUYBDMPAM0whVwB0RNjS6BuGgO1Qx12FwGVsJANYAaXADkI2GLgC+uClVogAApDbSNZAK4AbAPRkAzADYAtJHQQ2MDQGcW7TljzYIQ23YWVqdNdc1sHQNjczcPNgcQVjZ2GAAPLjxYMiI9cm02UiRrCSkYAHUkbAALABVi3RgAUXiidCqACgBKHnZcXAZsbUw2XEb2jtwAHgFhBSr4gBEkBmzrAF46SF1tFFiQAD5BoZG7bABPKp3d3CgiNgBzGEptO10DvhhsAEk2G0wACTKAWQAZBbAYAnU64AD6YJK2BQunguAABkQcEgwFV4GRZvszBAyGZDmgZHYAG6XHgKJC6WG4AAkwHCngAdJdMEQDiYAAzs+QAQmcOAu2GYsiR2BRaI0JWxuPxMEaACZWsTSbwMZS4bT6ZEmSyDgBWTk8vmCDTMOS4EVimS8ADuSCgpTh+vZaHiuF5Vn5Jrk8JEIKGslkfv02z6p2Gkmkfo6ouwVSWICmMFS6VwMeOICjuH2RxggN4ACNhMyIJkoABhCC6LBwzV2bWsgCMnLE+awsEwFarmBr7kZzNZRk5ckDod2IdBHUTyd02D9w30EZg47Di8zadzdCnaRn5p367omezcaBmY6hbAQmLpc71dTva1KywBRKxRgvtHE9bmHbN+7d4idb9gccrNpmAZ+suoJbimRAznOC75JBQzhvkqaVBuIAAAqYKgSIHPobxkBAaGxjAdCbNhuGYPhhEQPOi5IR0KHSCRcZ0JhEB2MUSBEjI+4gLgRJIkgArxhgXGirx5GZhxEk8WRH5MQh0iMSMi6sRhBRIhwVwaXQgnCaJdDWtpSBXNJilDFpvRmZc8EMXO6nrvG4gwJcRCSXx6H6UJOFGSANjuZ5FkThIbkefJ9mISc85jBey7NDEI4gLIQA).

## Breaking changes

This variant could make sense as the default. The default variant right now is `primary`. However, we probably just want to give this a distinct name to get around a breaking change.

**Comment by denkristoffer** [comment]
This is a great idea 👌 My gut reaction is also a preference for the gray version, but I wonder how well that would work in Compose.

**Comment by denkristoffer** [comment]
@gui-santos Add your comment please.
@Lelith

**Comment by Lelith** [comment]
In my gut feeling, it looks like we overuse the component. A important note should be prominent and visible in blue. I believe in the other cases we can go with a normal text or maybe the hint is not necessary at all?
Adding two new variations looks to me as a workaround for a deeper problem which is "how can we bring all important information to the customer, but not clutter them with too much"

@fabe maybe a more reallife example could help me to understand why the blue notification is not working there?

**Comment by fabe** [comment]
@Lelith We currently use blue for almost everything: Interaction (buttons & text links), active/selected states (tabs & toggle buttons & text input highlights), information highlighting (notes), statuses (badge). I think it would be good to tone that down a bit and reserve it for specific use cases (e.g. primary interactions, but not states). Ideally, `Note`s never take away from the primary interaction in a view.

I agree that we overuse the component, but I do see the frequent need to highlight information, or really, just structure information in a more meaningful way—without making that information the most important thing to look at. IMO, we need more tools to do this.

Just to make it clear, I'd add one of the two variations proposed here, not both :)

**Comment by Lelith** [comment]
@fabe thank you for the explanation! I really see the issue you describe. And i guess its more applyable  to reach for this solution.
if we can vote for one of the variations, then i'd go for the white one.

**Comment by burakukula** [comment]
Solution was provided in version `4.14.0`
