### ISSUE TITLE
🐛 Bug - Tooltip content accepting only string

### ISSUE THREAD

**Issue by burakukula** [contentful/forma-36#2045]
TS complains that Tooltip accepts only a string for the content prop, but there might be a case where we would like to pass a component.

**Comment by denkristoffer** [comment]
We've talked about this before 😄 What's the use case you see? I thought we agreed to nudge people towards only using Tooltip when the content is a string, otherwise they should be using a popover?

**Comment by burakukula** [comment]
Won't fix
