### ISSUE TITLE
Proposal - consistent use of Compound Components pattern

### ISSUE THREAD

**Issue by burakukula** [contentful/forma-36#2064]
## The problem

It came up in several proposals so far, to use Compound Component Pattern. This pattern is currently (v3) used in a `Workbench` component. Would be good to align on the usage of this pattern, document it in code style guides and refactor v4 components accordingly.

## The proposed solution

This pattern is commonly used in UI libraries, for example, semantic-ui-react or ant-design. We even use it (inconsistently) in our codebase.

### Components with `Compound Components` pattern

- [Accordion](https://f36.contentful.com/components/accordion)
- [EntityList](https://f36.contentful.com/components/entity-list)
- [FormControl](https://f36.contentful.com/components/form-control)
- [Radio (`Radio.Group`)](https://f36.contentful.com/components/radio)
- [Select](https://f36.contentful.com/components/select)
- [TextInput (`TextInput.Group`)](https://f36.contentful.com/components/text-input)
- [Grid](https://f36.contentful.com/components/grid)
- [List](https://f36.contentful.com/components/list)
- [Menu](https://f36.contentful.com/components/menu)
- [Modal](https://f36.contentful.com/components/modal)
- [Popover](https://f36.contentful.com/components/popover)
- [Skeleton](https://f36.contentful.com/components/skeleton)
- [Table](https://f36.contentful.com/components/table)
- [Tabs](https://f36.contentful.com/components/tabs)
- [Workbench](https://f36.contentful.com/components/workbench)

### Components, that could benefit from this pattern

- Any missing?

**Comment by burakukula** [comment]
Transferred from the discussion as a reminder to adjust all the components to follow this pattern. Some of the components are still not following it, like `Skeleton`

**Comment by denkristoffer** [comment]
Opened Skeleton PR here: #2169

**Comment by denkristoffer** [comment]
I've gone through our v4 components and see no more components that need this pattern. If you notice any that could benefit from it, please let me know and we can reopen this issue.
