### ISSUE TITLE
🐛 Bug - F36 v4 codemod migration TextField textLinkProps are not being migrated

### ISSUE THREAD

**Issue by andreascful** [contentful/forma-36#2102]
# Forma 36 bug report

## Summary

It seems that when a TextField is being migrated, nothing happens to the textLinkProps prop. No error is thrown, it is just not present in the newly created component.

**Example:**

```
<TextField
      id={name}
      name={name}
      labelText={label}
      helpText={description}
      required={isRequired}
      textInputProps={textInputProps}
      formLabelProps={formLabelProps}
    />
```

![image](https://user-images.githubusercontent.com/93705529/175057366-b4561752-dc62-42d5-97dd-7c53006922fa.png)

**Comment by denkristoffer** [comment]
Since we have a workaround I will close this, I don't expect we'll come back to this but let's see.
