### ISSUE TITLE
💡 Proposal - "Info" variant for Notification component

### ISSUE THREAD

**Issue by LiamStokingerContentful** [contentful/forma-36#2140]
# Forma 36 contribution proposal

## The problem

Currently, the [Notification](https://f36.contentful.com/components/notification) component supports three states: positive, negative, and secondary. These roughly correspond to success, error, and warning states, accordingly.

![Screen Shot 2022-07-25 at 10 02 17](https://user-images.githubusercontent.com/109533364/180728698-9175baf0-b293-4859-b105-5ec620192512.png)

With that in mind, there is currently no state for simple information, which could be useful and is already being used in a similar component: [Note](https://f36.contentful.com/components/note#__next)

![Screen Shot 2022-07-25 at 10 02 37](https://user-images.githubusercontent.com/109533364/180728746-bd748325-f8d7-422b-93c5-f644b0c13d0c.png)

## The proposed solution

We would like to propose the addition of a fourth state to the Notification component which roughly corresponds to an 'information' state. This would leverage the current Notification component for core functionality and could leverage the info icon already used in the Note component for matching style.

**Open question: What should the naming of this state be? ex. 'info' or 'tertiary'**

## Breaking changes

There should be no breaking changes as this will simply be an addition to the API.

**Comment by burakukula** [comment]
Hey @LiamStokingerContentful! Thanks a lot for the proposal! 🙌 
So we would have a white notification with the blue left border + blue info icon, right? @fabe @damann what do you think?
When it comes to naming conversation, I would vote for `info`, we would then call it like `Notification.info()`, which makes it consistent with existing API of this component.

**Comment by LiamStokingerContentful** [comment]
Hey @burakukula, thanks for the quick response!

> So we would have a white notification with the blue left border + blue info icon, right?

Yup! That would be the plan.

> When it comes to naming conversation, I would vote for info

Sounds good to me as well - I think I got a little confused by the names of the button variants that allow you to open a notification in [the public docs](https://f36.contentful.com/components/notification), now I see that `info` clearly makes the most sense.

**Comment by LiamStokingerContentful** [comment]
Here is a design for the component @burakukula @fabe @damann :

<img width="574" alt="image" src="https://user-images.githubusercontent.com/109533364/181572426-82e920cb-b1e3-4e7f-8b78-312a9bd49d22.png">

I'm currently working on putting up a PR and linking it to this issue
