### ISSUE TITLE
💬  Feedback - Dropdown

### ISSUE THREAD

**Issue by marcolink** [contentful/forma-36#2145]
# Forma 36 component feedback

Wouldn't it make more sense to link to the docs of the replacement components intead of linking to the github repo?
https://f36.contentful.com/deprecated-components/dropdown

**Comment by burakukula** [comment]
Hey @marcolink ! Thanks for bringing this up! 
Yeah I think you are right, it would make more sense to link to the replacement component. We will provide this fix. 🙂

**Comment by marcolink** [comment]
@thank you @burakukula 🙏
