### ISSUE TITLE
💡 Proposal - Multi Selection Component

### ISSUE THREAD

**Issue by Lelith** [contentful/forma-36#2162]
# Forma 36 contribution proposal

## The problem

Inside the web application and app framework apps we often have cases where users have to select multiple entries from a long list. We currently do not have such a dedicated Element. But we often use the Autocomplete Component or a Single Select and show the selection in removable Filter Bubbles  as a workaround. There is also often a modal invovled for the selection.
Examples see here: 

<img width="238" alt="image" src="https://user-images.githubusercontent.com/1789174/184637694-662d233d-5aed-455b-a1cb-df66f5ec305e.png">
In roles and permissions configuration

<img width="281" alt="image" src="https://user-images.githubusercontent.com/1789174/184641864-d013ca01-a021-407c-bb89-a64e7faa4a7b.png">
In the workflows app on multiple configuration 

And here is another multi select workaround with just checkboxes and the selected options again displayed as bubbles.
<img width="294" alt="image" src="https://user-images.githubusercontent.com/1789174/184640647-236baf98-f051-46f9-87fa-becbd83f0d07.png">

<img width="156" alt="image" src="https://user-images.githubusercontent.com/1789174/184640738-fef7754f-d118-4790-b442-97d5b4ee91e3.png">

## The proposed solution
<img width="748" alt="image" src="https://user-images.githubusercontent.com/1789174/184643141-fccdaf10-2832-4d89-9983-6266e3f122b4.png">

This new component will be based on a pop-out component. The search input field will be optional as well as a select all possibility. Also we will have some space to put in information messages like a maximum selection limit, which is another property. 

Proposed Interface would be:
- items: ItemType[] | GenericGroupType<ItemType>[];
- isGrouped?: boolean;
- onSelectionChange: ()=>{};
- selectedItems:  ItemType[];
- icon?: React.ReactElement;
- hasSearchInput?: boolean;
- onSearchValueChange?: () => {};
- searchPlaceholder?: string;
- itemToString?: (item: ItemType) => string;
- placeholder?: string
- noMatchesMessage?: string
- listWidth?: 'auto' | 'full';
- listMaxHeight?: number;
- maxSelectedItems?: number; // 0 would be default and mean no maxmimum
- informationMessage?: string;
- isLoading?: boolean;

**Comment by denkristoffer** [comment]
Yes I agree we should have this component. 

I'd like some arguments for why this cannot be a part of the autocomplete though. Any thoughts on that? I'll try to gather my thoughts on the topic as well 🙂

**Comment by burakukula** [comment]
It totally makes sense to introduce this component. I think this should be released already in Forma 36, taking into consideration in how many places we actually need it already. 
Maybe we could release in `alpha` and experiment with it, then move to `beta` and give it to community to try it out?

**Comment by Lelith** [comment]
@denkristoffer the autocomplete is more ideal for a single select, a lot of magic for the single selection comes from downshiftJS. And unfortunately introduced a couple of issues, based on the way it was implemented.These issues we can not fix without a breaking change. For selectable elements with checkboxes, i do not need to use downshiftJs at all. Because there default form-behaviour takes care of what is selected and what not. But i think what is missing in my initial proposal is the "currentSelection" object, so its a fully controlled component.

Yes the properties are very very similar to the Autocomplete, but in reality autocomplete is a single select with a search input field. Also in Autocomplete i would not be able to show the selected elements in the same way as i would be with this new component.

**Comment by Lelith** [comment]
The component is now released as an alpha. Therefore i close the issue.
