### ISSUE TITLE
💡 Proposal - Add 'overlayClassName' prop to Modal component

### ISSUE THREAD

**Issue by maxcheremisin** [contentful/forma-36#2166]
# Forma 36 contribution proposal

## The problem

Customise Modal overlay.

![image](https://user-images.githubusercontent.com/22265863/186731804-851096e7-aa53-4c1f-97f7-1e6b5d4c6d00.png)

## The proposed solution

Add an optional `overlayClassName` prop for Modal component to have a possibility to change the style of it.

## Breaking changes

No Breaking changes

**Comment by denkristoffer** [comment]
Done.
