### ISSUE TITLE
🐛 Bug - Autocomplete: prop "ref" from getMenuProps was not applied correctly

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#2222]
# Forma 36 bug report

## Summary

The Autocomplete component doesn't handle ref props from Downshift correctly. This logs an error on render, which results in noisy tests, even when they pass.

## Steps to reproduce

Try the TagsSelection test from experience-packages.

## Expected results

Tests should pass without logging errors

## Actual results

```
  PASS  src/TagsSelection/TagsSelection.spec.tsx (9.244s)

    console.error
      downshift: The ref prop "ref" from getMenuProps was not applied correctly on your element.

      29 |   }
      30 |
    > 31 |   error.apply(console, [message, ...args]);
         |         ^
      32 | };
      33 |
```

**Comment by massao** [comment]
closed by #2249
