### ISSUE TITLE
Full-width option for modal

### ISSUE THREAD

**Issue by floelhoeffel** [contentful/forma-36#232]
Would be great to be able to create modals which take the entire width of the screen (minus some margin)

![image](https://user-images.githubusercontent.com/6864947/60504039-2121df80-9cc1-11e9-9552-3a662e148956.png)

Workaround: set the width to 5000px so the modal grows as much as possible but thats rather dirty

**Comment by m10l** [comment]
Hey @floelhoeffel, thanks for the request! I've added a PR to add a `fullWidth` option to the `size` prop for the Modal component, this should give you what you're looking for. Let me know if you have any issues/concerns.

**Comment by m10l** [comment]
@floelhoeffel This is now available in v3.13.0 of  the component library (`@contentful/forma-36-react-components@3.13.0`).
