### ISSUE TITLE
🐛 Bug - Text component should not take "color" prop

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#2339]
# Forma 36 bug report

## Summary

The `Text` component should not take the prop `color` but instead throw a type error. I keep using `color` instead of `fontColor` because I'm silly and I never get an error, but I don't get the result I expect either 🙁 The prop type comes from the fact that we're extending the default HTML attributes. We should probably `Omit` `color`. 

Example: https://f36.contentful.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwATFwDEAbGADwBpcAVcvAX1wDNMIVcByAAUgDtsY-JgFdiAeiYBmAGwBaSOgi9B2AM4cA3AB1eO8hhy5YTAIai8I3mGxIluAIJo0ACgCU+HblyYY2YZl5cAB4ScmZSMgARJB9rW14AXi1wCGJhFF0QAD5PL2DaMjxIYiwkkB8oAFYABmrkrIBJXFUACwhRKFxsFtYAd1wTLoBPNBhcGExWTABCILEC7BzAvKCF5iVsAGFU0uSKmrrsptb24k6AIzGK2fm6Ja850LIl+hB6IA

**Comment by Wake1st** [comment]
@denkristoffer, could you provide an example of how you're passing in `color` - is it via `style` prop?

**Comment by denkristoffer** [comment]
Thanks for requesting that @Wake1st, I've added an example to the issue.
