### ISSUE TITLE
🐛 Bug - Multiselect dropdown not positioned correctly (missing portal?)

### ISSUE THREAD

**Issue by msieroslawska** [contentful/forma-36#2398]
# Forma 36 bug report

## Summary

We are currently using `Autocomplete` component for multiselection, but we would like to migrate it properly to `Multiselect`. In our case, we display the list of selected options underneath the selection component, if there is at least one element in the list. When trying to migrate the selection component I have discovered a behavior, where if that list changes its size, the component's input and option dropdown are no longer attached to each other. I'm suspecting this might be caused by the lack of support for `usePortal` prop.

## Environment

MacOS, Chrome

## Steps to reproduce

0. Go to [my branch](https://github.com/contentful/user_interface/tree/dante-855), clone it and run web-app locally (I tried reproducing it in the playground, but took me too much time and I didn't get anywhere)
1. In an existing content model, create a new field of type "Reference" using the button "Create and configure"
2. Go to "Validation" tab
3. Select "Accept only specified entry type"
4. Click on any of the available options in the dropdown

## Expected results

Dropdown stays attached to the input field despite the content type box extending the parent element.

Before selection:
![Screenshot 2023-02-02 at 16 58 34](https://user-images.githubusercontent.com/8281495/216376450-a6a15ad7-5974-4d0e-bf99-5ddd0dbdf212.png)

After selection:
![Screenshot 2023-02-02 at 16 58 55](https://user-images.githubusercontent.com/8281495/216376478-8ca8e9aa-c9af-47c7-9115-1c0dfe126d31.png)

## Actual results

Dropdown is glued to its original position and when the parent element extends its height and moves the input there is a gap between dropdown and input.

Before selection:
![Screenshot 2023-02-02 at 15 04 49](https://user-images.githubusercontent.com/8281495/216376250-e66afb9e-061d-48b4-8a40-f7400875417f.png)

After selection:
![Screenshot 2023-02-02 at 15 05 33](https://user-images.githubusercontent.com/8281495/216376314-4739da1f-cfbc-4a44-a445-4f9d4f2cc59a.png)

**Comment by Lelith** [comment]
This issue seems to be fixed
