### ISSUE TITLE
🐛 Bug - EntityListItem actions click doesn't prevent entire card click

### ISSUE THREAD

**Issue by dani1993** [contentful/forma-36#2463]
# Forma 36 bug report

## Summary

On EntityListItem component, if are enabled both **_onClick_** and **_actions_** properties, clicking on actions button is intercepted also card **_onClick_** event property.

## Expected results

Expected **_stopPropagation_** and **_preventDefault_** of click event when actions button is clicked.

**Comment by wpigoury** [comment]
Same issue when href and actions properties are set, clicking on actions menu triggers the href as well opening a new tab while we just want to open the action menu.

**Comment by Lelith** [comment]
was fixed in https://github.com/contentful/forma-36/pull/2839
