### ISSUE TITLE
💬  Feedback - Color system

### ISSUE THREAD

**Issue by JorgeLGonzalez** [contentful/forma-36#2490]
Just some quick feedback on documentation. I found it difficult to figure out how to use the same color values documented here https://f36.contentful.com/tokens/color-system but without hardcoding them. It would have been useful to document the `tokens` const exported from `@contentful/f36-tokens`.

Somewhat related, we are creating a sidebar nav on our home app default page. The NavList component is looking very promising. Did not use it since it is in Alpha, but it would be nice somewhere to specify more about the color scheme such as which colors are used for on hover and selected.

**Comment by denkristoffer** [comment]
Thanks for the feedback @JorgeLGonzalez, I think you are right that the color system page is missing an explanation of how to actually implement the tokens. I will create a ticket for us to address this.

**Comment by denkristoffer** [comment]
Closing this issue, it's in our backlog. Thanks again for the feedback, we will address this.
