### ISSUE TITLE
🐛 Bug - Autocomplete loading state not shown unless it has data

### ISSUE THREAD

**Issue by AndrewLeedham** [contentful/forma-36#2507]
# Forma 36 bug report

## Summary

When using the `<Autocomplete>` component with the `isLoading` attribute it requires `items` to have a value to render the "loading" dropdown. However, by the very nature of data being loaded we don't have any yet.

## Environment

Arc/macOs

## Steps to reproduce

[This playground example](https://f36.contentful.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwAQCUYBDMPAM0whVwHJNjSaBuAHQDtUMddhcBBAK7YIkdABsY2GABpcAZWwkA1rgC+uClVoABSGyn6yAsQHoyAZgBsAWlEY2MfQGdm7djAAeXPLDJFj5AJspEgQbPxCIlRoElIAMhBEUEhsAOYKRFIAFACUPOy4uPTYApjhWQWFuAA8GWAqZBIeACJI9CFhALws4BBiAihsPbhEYkipbACSUihO3SBOijg9AHyVVTWCwnaxMOsbuEgzc8AA2gC6qvsbSE4JSSmp17gma+EH1VtR4pJ77weHY6dM5BXwpGBQS7PQq3e7JNLPV77aomOpKN6FHKsNhXNggVRAA) shows `isLoading` with `items` as an empty array (no loading state) and adding a single undefined value (shows loading state).

## Expected results

I would expect the loading state to still show with an empty array.

## Actual results

The loading state is only shown if `items` has values.

**Comment by AndrewLeedham** [comment]
Still an issue.

**Comment by AndrewLeedham** [comment]
...

**Comment by Lelith** [comment]
Hey @AndrewLeedham,
i double checked the behaviour, and to force showing the loading state, there is already an attribute called `showEmptyList` 

```
      <Autocomplete
        isLoading
        showEmptyList
        items={[]}
        onInputValueChange={handleInputValueChange}
        onSelectItem={handleSelectItem}
      />
`

See working example in the [Playground](https://f36.contentful.com/playground?code=N4Igxg9gJgpiBcICWBbADhATgFwAQCUYBDMPAM0whVwHJNjSaBuAHQDtUMddhcBBAK7YIkdABsY2GABpcAZWwkA1rIAKRTEQDmmtAAtcAX1wUqtAAKQ2U62QFiA9GQDMANgC0ojGxjWAzszs7DAAHlx4sGRE9uQCbKRIEGz8QiJUaBJSAEJEfkhgAKp+2jAAoiFE4jAAFACUPOy4uFZ+eH5oJDB+uAC8uADajU20ACqaAG4wYrhZYhBaNNJDTTQAYkhsbETxMDNzC0vJw2tI2D5+3XxoaIvLtAByMADu3QDqMABGeVK3RyswAGEqCgYJgwLsAURFPsBDBfsNaKo9BBhLgAOJEMQSTAAT3huAAuqw2EMHA5cCM9EhugADAR+GAKKEwGm4am4LQQDZaXCo1pYXbYPS7BkSUgwKC4FggdqdaW4PwQXBPXZgbYK5FPNl4Da84W4AoASSGLTw-VFMHFUDkHXBsgZ2DkU0tUmttpgBN6BAY2AAdPTGYopHViU1TQMyEgxFJ6FBDVIUH57ZJ1tHQRL4zBE56+oQSH6A0zg7LwX5asTSeT3iYozG9btpSWuvKNJocbgPu2hbsNmghAA1TGwyvK3YB2jCAAyEBVmEhDLqNF5SpQRCUgv1DI0YAMaoZbLYDMPpyQkxNSVauD02ygEkNbD72EHYlhAOvbC0uz61XGQ5g9R6AA+Bo-maC88B8J5UxjDME26Pomz8X1IzTTBqmqU4swAwC7iaTCUF9KcZ1BecalqX0NjAF9YD8H8-0IiBp1nUi6lqQ4EXLO4HWg9M4zg6pIJ42NM0TTijkMCsjjJCkqW6Ox4mwRJkieKNpg+VVMQkSUknBetcADTAFWdUhunVfCDz0sRqTwCAyFwCA0EUi9z0PPB31vRljOwESvQwhNsJAhEHSdMVXRtTo-Kw0MjEkpp6GwARMGSao7gAHiZMAlBMCQQgAESQegEiSHppUgF8UBJEBcExJAtDYES-BKmVFBwaUcNAppUsEYQvEyGBcOGalpyIKBuQGpo-E1Up0GwHFJ2s8btSzRrgH6AlDEWpJ70fZ9X3fT8emAdy7wfAc-zfbZPw2jrhiSEKXREw7js80KROuhEmgcdqBtS9RNB0Ih9Haj7hnuq0FXdeBcFSj5AOAC0rXC8FDFShxYZ+hw-u0XQ9GB4ZUYypQ8bE66QEMIA)
