### ISSUE TITLE
🐛 Bug -  Text component does not allow to control the letter spacing

### ISSUE THREAD

**Issue by maxrawlinger** [contentful/forma-36#2604]
# Forma 36 bug report

## Summary

The [documentation about the Text component](https://f36.contentful.com/components/text) gives an indiction about letter spacing abilities, however, it does not consider this attribute in any case eventually.

What is the importance?

While most of the typography components (e.g `Heading`, `Paragraph`, etc) do already incorporate a predefined appearance and semantic, the `Text` component, however, works as the generic base layer enabling to add color system tokens but especially tokens to define typography styles.

Furthermore, while the `Text` component allows to control mostly all described tokens [on the typography page](https://f36.contentful.com/tokens/typography) it does not allow to set the letter spacing. This behaviour bears some sort of inconsistence at first sight. Is the implementation intentionally chosen, if so, why?

Additionally, while the `Text` component is missing the ability to control the letter spacing the `SectionHeading does incorporate letter spacing implicitly as the only typographical component.

Given behaviour enforces confusion because a semantic components implicitly enforces a visual appearance which cannot not be reproduce by any other component including the `Text` component although the typography token is explicitly listed in the guidelines.

The following image depicts the implementation of the `SectionHeading` component showing in line 49 that the letter spacing is passed via the className to the underlying `Text` component.
<img width="507" alt="Bildschirm­foto 2023-11-07 um 14 36 19" src="https://github.com/contentful/forma-36/assets/9822752/94668ce9-805e-4959-8ebc-2d056209d3bb">

## Environment

An environment might not be necessary needed.

## Steps to reproduce

The `Text` component [source code](https://github.com/contentful/forma-36/blob/main/packages/components/typography/src/Text/Text.tsx) does not expose a prop related to the letter spacing.

## Expected results

Being able to control the letter spacing in the `Text` component via a prop.

## Actual results

Currently not able to control the letter spacing in the `Text` component via a prop.

**Comment by cf-remylenoir** [comment]
Hi @maxrawlinger ,

Thank you for bringing it up to us.

This PR https://github.com/contentful/forma-36/pull/2633 takes care of adding the letter-spacing support via props.

**Comment by cf-remylenoir** [comment]
@maxrawlinger you can install the latest to get the new capabilities.

`npm install @contentful/f36-components@latest @contentful/f36-tokens@latest`

Thank you for your contribution.
