### ISSUE TITLE
Make ref, classNames, otherProps always go to the root element

### ISSUE THREAD

**Issue by guilebarbosa** [contentful/forma-36#267]
I would like to propose a pattern to be implemented in all Forma36 components.
`ref`, `classNames` and `otherProps`, `testId` should always go to the root element.

Currently, the lack of a pattern slows down development with the components. Besides not being consistent about where those props go, there's also inconsistency in their names -- i.e. `ref` shows up as `nodeRef`, `inputRef`, `getRef `, `setRef`... -- and their presence in the components.

**Comment by wichniowski** [comment]
@guilebarbosa how should we handle components that use portals. Those props would go to the element that is mounted through the portal or the container/target (e.g Dropdown, Tooltip) ?

**Comment by guilebarbosa** [comment]
IMO it should go to the root of target (Tooltip, Dropdown)

**Comment by burakukula** [comment]
It will be delivered in v4
