### ISSUE TITLE
💡 Proposal - Enable passing a customised `Badge` to `EntryCard`

### ISSUE THREAD

**Issue by Cyberxon** [contentful/forma-36#2670]
# Forma 36 contribution proposal

## The problem

While working with the `EntryCard` component to create a new externalResourceCard that will represent 3rd party content, I noticed that we only allow entry statuses on `EntryCard`. Since the status list of the externalResourceCards is different from the Entry's (see the attached photo), How can we enable these badges to appear with the correct status for external resource cards?

![image (4)](https://github.com/contentful/forma-36/assets/26111745/47ee9773-f4da-4c0c-8163-c23a65cbd629)

## The proposed solution

One straightforward solution is to enable passing a `Badge` element as an option to the `EntryCard` (the option already exists in the code of the `BaseCard` component that the `EntryCard` extends from). This will allow users of the EntryCard component to customise the statuses they want to show on the card and not be restricted to the EntryStatuses list.

## Breaking changes

Using the badge option and passing an actual Badge component to the EntryCard will ignore the status option if it was passed to it

**Comment by cf-remylenoir** [comment]
Hi @Cyberxon , 

Thank you for this proposal, as discussed the proposed solution sounds good to me 👍 

cc: @damann for visibility

**Comment by damann** [comment]
Thanks! I'll add a note to the Figma component.
