### ISSUE TITLE
Date and time formatting guideline

### ISSUE THREAD

**Issue by domarku** [contentful/forma-36#279]
Hi 👋

I'd like to propose a date and time formatting guideline in the Copy section of the Guidelines.

Currently, whenever we need to show a timestamp we lack guidelines on how to show it:
- what format to use? US / UK / International?
- absolute or relative time? is "Today" enough?
- 12-hour or 24-hour? should am / pm be written in lowercase or uppercase?

**Comment by domarku** [comment]
Here's a WIP preview of the proposal:

![localhost_8000_guidelines_copy_date-and-time_(1280) (1)](https://user-images.githubusercontent.com/7631029/62940071-015afc80-bdd3-11e9-8fcd-6afb96b93018.png)

**Comment by wichniowski** [comment]
Hey @domarku thanks for this excellent proposal! I think this looks very good can you please open an PR with the documentation changes.

**Comment by m10l** [comment]
PR has been opened here #282
