### ISSUE TITLE
Sticky notifications on fast mouse movement

### ISSUE THREAD

**Issue by MarkusLaut** [contentful/forma-36#280]
Hi :wave: 

I noticed that notifications can be sticky when moving the mouse fast, which can be irritating.
This seems to only happen in a more complex application which puts some demand on the browser.
![notifications-fast](https://user-images.githubusercontent.com/40791319/62943682-5569df00-bddb-11e9-9742-747959e13404.gif)

**Comment by m10l** [comment]
Thank you for reporting! After looking into the issue the problem appeared to be related to the disabled button being wrapped by the Tooltip component.

Adding `pointer-events: none` to the disabled button element will resolve the issue.

**Comment by MarkusLaut** [comment]
Thanks :bowing_man:
