### ISSUE TITLE
No key press, key down or key up event on Input element

### ISSUE THREAD

**Issue by brunoxd13** [contentful/forma-36#287]
When using TypeScript and react in interface of `Text Input` doesn't exist the events(`onKeyPress`, `onKeyDown`, `onKeyUp`). In this case I need to capture the enter key in an input to get the value and add this value to the state of component.

**Comment by wichniowski** [comment]
Hey @brunoxd13 your PR was reviewed and approved! Thank you for the contribution 👍 

Related PR: https://github.com/contentful/forma-36/pull/288

**Comment by wichniowski** [comment]
This was released with Forma 36 3.15.18 

https://github.com/contentful/forma-36/releases/tag/%40contentful%2Fforma-36-react-components%403.15.18
