### ISSUE TITLE
🐛 Bug - Playground seems to be broken.

### ISSUE THREAD

**Issue by pjmlp** [contentful/forma-36#2896]
# Forma 36 bug report

## Summary

The playground seems to be down, failing to fetch something that makes it work.

## Steps to reproduce

Open playground at https://f36.contentful.com/playground

## Expected results

Being able to access the playground.

## Actual results

Playground shows an error message that it isn't able to fetch dependencies.

![image](https://github.com/user-attachments/assets/5500107a-359e-4262-b178-291a5f26b17c)

**Comment by cf-remylenoir** [comment]
Hi @pjmlp,

Thank you for reporting this issue, I can reproduce it and will look into it.

**Comment by cf-remylenoir** [comment]
Hi @pjmlp , the issue is now resolved, thank you again for reporting it.
