### ISSUE TITLE
Modal component: allow height overflow by default

### ISSUE THREAD

**Issue by MarkusLaut** [contentful/forma-36#305]
Hi,

We had some issues concerning Modals with moderate amounts of content in small windows and the resulting overflow.
Setting `allowHeightOverflow` to true fixed that for us and it seems there are actually no downsides to setting it.
Should it be set to true by default?

**Comment by wichniowski** [comment]
Related PR: https://github.com/contentful/forma-36/pull/316

**Comment by wichniowski** [comment]
Will be released with Forma 36 4.0
