### ISSUE TITLE
Switch label is defined as a `p` tag instead of label

### ISSUE THREAD

**Issue by mshaaban0** [contentful/forma-36#317]
Hi there, I've a small note on Switch component...
Label is defined as a `<p />` tag. Using `label` tag is semantically valid, and enables accessibility out of the box.
Happy to contribute, if you guys are okay with the approach!

**Comment by wichniowski** [comment]
Hey @mshaaban0 

good catch! Your contribution is highly appreciated :). 

Thanks in advance!

Johannes
