### ISSUE TITLE
Proposal: forma-36-react-date-components

### ISSUE THREAD

**Issue by wichniowski** [contentful/forma-36#325]
Hey lovely people 👋 

I'm here with another proposal about date components.
One artifact of the brand new scheduled publishing feature is 3 UI components to enter and select dates, time and timezones. I want to move these components to Forma 36 for you to reuse so I'm proposing a new package called `forma-36-react-date-components`.

This package will include the following components:

DatePicker
![image](https://user-images.githubusercontent.com/1766274/67879832-ea0fed80-fb3d-11e9-8545-11bed0add0d5.png)

TimePicker
![image](https://user-images.githubusercontent.com/1766274/67879866-f7c57300-fb3d-11e9-93f3-6fe48e8ecb68.png)

TimezonePicker
![image](https://user-images.githubusercontent.com/1766274/67879893-feec8100-fb3d-11e9-988c-86f1efe4a331.png)

FormattedDate -> Utility component the formats date in Forma-36 compliant formats

**Why is this a new package?**

These components will have a peer dependency on moment.js (or date-fns up for discussion..) which I don't want to force the consumer of our `forma-36-react-components` package to install.

Ideas & comments are as always much appreciated ❤️ 

Thanks!

**Comment by suevalov** [comment]
Sounds reasonable for me! Few questions and suggestions:

1) Would `forma-36-react-components` be a peer dependency of this package as well?
2) Do you plan to use `emotion` or the same `sass` approach? 
2) I strongly recommend using `tsdx` instead of coping webpack configuration from `forma-36-react-components`.

**Comment by wichniowski** [comment]
@suevalov thanks for the comments, here is my response:

1. Ja :)
2. Emotion!!
3. Sounds good, so yes!

**Comment by m10l** [comment]
Nice, components sound great! My only concern is grouping all of these things in one package. We've discussed the possibility of going for a one-component-per-package and I feel like this single `forma-36-react-date-components` package could be a little short-sighted. So instead I'd recommend building out each component as a separate package like so:

`forma-36-react-components/date-picker`
`forma-36-react-components/time-picker`
`forma-36-react-components/time-zone-picker`
`forma-36-react-components/formatted-date`

**Comment by mshaaban0** [comment]
Nice one 👍
What do you guys think about using [dayjs](https://github.com/iamkun/dayjs) instead of momentjs? 
I personally prefer dayjs because it's lighter and performs way better than moment. [This nice article](https://inventi.studio/en/blog/why-you-shouldnt-use-moment-js) compares different date libraries.

**Comment by joaoramos** [comment]
This is a good idea! I'll share my concerns regarding accessibility in the follow-up pull request.

**Comment by wichniowski** [comment]
@mshaaban0 good suggestion! I'd lean towards date-fns since it comes with a timezone package that we'll depend on for the timezone select component. But in general yeah I think we can agree on replacing moment js :)

**Comment by wichniowski** [comment]
Datepicker component released: https://www.npmjs.com/package/@contentful/forma-36-react-datepicker
