### ISSUE TITLE
DropdownList inside EntryCard not positioned correctly

### ISSUE THREAD

**Issue by Herdismaria** [contentful/forma-36#326]
I'm using the EntryCard component and trying to add a DropdownList to edit and remove entries.

The DropdownList position seems to be calculated incorrectly or I'm missing something

`return (

        <EntryCard
          title={colorName.en}
          contentType={sys.id}
          thumbnailElement={
            <div
              style={{
                height: '100%',
                width: '100%',
                opacity: opacity || 1,
                background
              }}
            />
          }
          dropdownListElements={
            <DropdownList>
              <DropdownListItem isTitle>Actions</DropdownListItem>
              <DropdownListItem onClick={() => {}}>Edit</DropdownListItem>
              <DropdownListItem onClick={() => {}}>Remove</DropdownListItem>
            </DropdownList>
          }
        />
      );
`

![Screenshot 2019-11-01 at 09 50 15](https://user-images.githubusercontent.com/22525070/68013547-88f72f80-fc8d-11e9-9544-351d61d001ad.png)

**Comment by wichniowski** [comment]
Hey, @Herdismaria thanks for opening this issue! It seems like a bug with the auto-alignment of that component. Is the dropdown list overflowing the bottom of the current viewport?

**Comment by Herdismaria** [comment]
> Hey, @Herdismaria thanks for opening this issue! It seems like a bug with the auto-alignment of that component. Is the dropdown list overflowing the bottom of the current viewport?

I'm not sure. It looks like the iframe cuts off the dropdown. I tried moving it down and then the bottom of the list got cut off by the iframe

**Comment by Herdismaria** [comment]
So I just ditched the dropdown and found another way. Now I tried adding the dropdown back and it is positioned correctly 🤷‍♀ .

**Comment by Herdismaria** [comment]
The position seems to be calculated correctly, however the iframe cuts off the bottom

![Screenshot 2019-11-01 at 16 02 42](https://user-images.githubusercontent.com/22525070/68033966-215ad780-fcc1-11e9-89e1-eb68456e0a04.png)

**Comment by wichniowski** [comment]
@Herdismaria thanks for bringing this up. We'll look into it asap! For now, a possible workaround could be to wrap the card in a container and give this container some min-height so that it won't overflow. I'll let you know as soon as there is a fix for this issue!

**Comment by lukethacoder** [comment]
Has this been fixed up? Running into similar issues with the standard `<Dropdown/>` component.

![image](https://user-images.githubusercontent.com/13529535/83649244-508c4b00-a5fa-11ea-9ac7-87a15368fd03.png)

There are 6 items in this list, but they get cut off at 2. `position="bottom-left"` on `<Dropdown/>` doesn't seem to be doing anything either.

repo [here](https://github.com/lukethacoder/contentful-ui-icon-selector) for reference

**Comment by lukethacoder** [comment]
Looks like I was having my own issues with `window.startAutoResizer()` not kicking in for dropdowns (presumably `position: absolute;` elements). 

anyone else facing this issue will need to use the `window.updateHeight(SIZE_OF_INPUT)`. Where `SIZE_OF_INPUT` is your own calculation, or value of height.

**Comment by gui-santos** [comment]
It seems that this bug has been fixed. Pls open a new one if this is not true 🙏
