### ISSUE TITLE
TableSortingLabel is not exported

### ISSUE THREAD

**Issue by jooohn** [contentful/forma-36#335]
Is there any reason that you're not exporting TableSortingLabel from index.tsx? This causes missing css style even though I can import the component like this way: `import { TableSortingLabel } from '@contentful/forma-36-react-components/dist/components/Table/TableCell';`.

**Comment by wichniowski** [comment]
Hey @jooohn I think we just missed exporting it I'm sorry :/.. I'll open a PR asap.

**Comment by gui-santos** [comment]
Closing this since it seems to have been fixed in #852
