### ISSUE TITLE
Proposal: Use tether.io for attaching absolutely positioned elements to a target 

### ISSUE THREAD

**Issue by arpl** [contentful/forma-36#361]
Hi all,

## Description
There is an easy win out there called [tether](http://tether.io/docs/welcome/) see [docs](http://tether.io/) and [source](https://github.com/shipshapecode/tether). The library focuses on the very specific problem of attaching an absolutely positioned element to another. 

### Pros
* Solves one problem and it does it [well](http://tether.io/overview/why_you_should_use_tether/)
* Well maintained since major [components](http://tether.io/examples/projects_using_tether/) depend on it
* Great API and docs

### Cons
* Yet another dependency
* Adds 5kb gzipped

Since I'm working on porting the Autocomplete we can have an example using tether which might help towards a decision.

Your awesome point of view is an absolute must ;)
Aris

**Comment by wichniowski** [comment]
Hey @arpl I think this is a great suggestion since we previously had issues with the component that attaches and repositions dropdowns, tooltips etc.. Since tether is widely used and well tested I'd be in favor of replacing our InViewport component with it. Although it comes with a 5kb price per component package that uses it.

**Comment by kamsar** [comment]
This also causes problems with the multiple reference field editor if used in an app or UI extension (https://github.com/contentful/field-editors/issues/415)

**Comment by m10l** [comment]
We recently refactored the tooltip component to use [Popper.js](https://popper.js.org/) and a follow-up PR is open to refactor the Dropdown component is currently open.
