### ISSUE TITLE
Distribute source files

### ISSUE THREAD

**Issue by davilima6** [contentful/forma-36#366]
For tree shaking (thus smaller bundle sizes) have you considered instead of distributing only a `styles.css` to also publish the source code?

In some cases if I only import `<Button>` I'd like to avoid including in my UI extension the CSS for all components.

**Comment by wichniowski** [comment]
Hey @davilima6 thanks for opening this issue! Yes we want to go even further and actually publish every component as a separate package. You can find the discussion about the new package structure here: https://github.com/contentful/forma-36/issues/329
We're actively working on migrating all components to this new structure: https://github.com/contentful/forma-36/tree/master/packages/components

**Comment by davilima6** [comment]
Thanks for the quick reply and links.

Closing in favour of contentful/forma-36#329
