### ISSUE TITLE
Formatted date and time components

### ISSUE THREAD

**Issue by wichniowski** [contentful/forma-36#396]
Hey Forma 36 Fam ✌️

I'm proposing a package that will provide 3 components to format date and time absolute and relative following our guidelines: https://f36.contentful.com/guidelines/date-and-time/

The components would look something like this:

```jsx
import { FormattedDate, FormattedRelativeDate, FormattedTime } from '@contentful/forma-36-react-formatted-date-time'

<FormattedDate date={new Date()} /> // 13 Aug 2019
<FormattedRelativeTime date={new Date()} /> // 4 hours ago, today, 2 days ago, 3 weeks ago, 4 months... 
<FormattedTime date={new Date()} format="12" /> // 12pm
```
WDYT? Any feedback is much appreciated!

🖖

**Comment by mshaaban0** [comment]
Noice, Shall we combine these components with similar ones in one package and call it helpers, or utilities, or something? or you prefer to keep them separate?

**Comment by wichniowski** [comment]
@mshaaban0 yeah good idea! Could be nice to have `forma-36-react-utilites` 🤔

**Comment by guilebarbosa** [comment]
I like the idea of the components very much. 

Maybe we can consider different names? I feel like "formatted" is not really necessary but unfortunately we probably can't just use `<Date />`.

I'm not a fan of the utilities idea. In my opinion these are just components, not utilities.
I'd also avoid having any sort of public "utils" or "helpers", since its meaning is vague, in my opinion.

**Comment by wichniowski** [comment]
@guilebarbosa yeah good point do you think it should be even separate packages like:
`forma-36-react-formatted-date`
`forma-36-react-formatted-time`

or should it be one package exporting those components, something I'm not sure about 🤔 
I think the names should include `formatted` since those a re single purpose components

**Comment by guilebarbosa** [comment]
I think it should be exported just like the other components.
For instance, we have all the typography components there in the same package, and I think it's fine.
So, IMO, just export them from `forma-36-react-components`

**Comment by wichniowski** [comment]
Following the new package structure that is package per component, I'd create this as separate packages that will be also separately published on NPM I'm just not sure if this is one package or if every one of those components should be a single package.

**Comment by guilebarbosa** [comment]
Oh, I'm sorry! I was not aware of this new package structure decision. I seems like I've missed it.

**Comment by m10l** [comment]
Nice, a good addition. I'm in favor of keeping them as individual components rather than grouping into another package. So either individual components, or under `forma-36-react-components` if we have issues.

**Comment by domarku** [comment]
Hello! Can we close this as it was introduced by https://github.com/contentful/forma-36/pull/584?
