### ISSUE TITLE
Button with buttonType primary gets gray border instead of blue when href is set

### ISSUE THREAD

**Issue by giotiskl** [contentful/forma-36#421]
When I set an `href` attribute on the `Button` component, with a `buttonType="primary"` I get a gray border as opposed to the normal bluish border.

See screenshot below:

![buggy_button](https://user-images.githubusercontent.com/12873414/75022664-ce3aa980-5496-11ea-9535-9aaf5ba478a3.png)

Bug is reproducible in forma-36's storybook, if you set the href prop.

**Comment by burakukula** [comment]
Hey @giotiskl thx a lot for letting us know. 🙂I will have a look on it.
