### ISSUE TITLE
List should accept a style prop so we can have bullet lists.

### ISSUE THREAD

**Issue by vbeleuta** [contentful/forma-36#423]
![Screenshot 2020-02-21 at 16 28 17](https://user-images.githubusercontent.com/7528329/75047587-4f119980-54c7-11ea-9546-9a5a794c59b9.png)

First list works. Second list causes an error because we pass the **_style_** prop to the _**ul**_ html tag.

Ideally a _List_ with _style="disc"_ should create a bullet list by appling the value of the _style_ prop to the items as _list-style: disc;_

**Comment by mshaaban0** [comment]
@vbeleuta The `style` prop exposes all css properties for the `ul`, hence, I think you can do this...
```jsx
<List style={{listStyleType: "disc"}} />
```
Is that what you're looking for?

**Comment by m10l** [comment]
Actually, this component needs more work… Right now it only renders a UL (what if I want an ordered list?). It also doesn't set the list styles itself.

**Comment by nikazawila** [comment]
@vbeleuta this is now addressed via https://github.com/contentful/forma-36/pull/809 - we introduced the `element` tag that lets you decide which style the list should be displayed in. 
It can either be bulleted (element="ul") or numbered (element="ol") - hope this solves your use case 🤞🏼
