### ISSUE TITLE
Contribution Proposal: Grid Component

### ISSUE THREAD

**Issue by mshaaban0** [contentful/forma-36#424]
Hello Lovely F36 Community 👋

I'm proposing a new Grid component to ease the overhead for developer to write their own layout css.

## Overview
* Built on [CSS Grid](https://www.w3schools.com/css/css_grid.asp)
* Fluid Grid (columns width is relative to the container width)
* Grid Playground - Alpha [CodeSandbox](https://codesandbox.io/s/react-grid-t2xg8?fontsize=14&hidenavigation=1&theme=dark)
* Fun way to learn css grid: [CSSGridGarden](https://cssgridgarden.com)

The Grid consists of two components `Grid` and `GridItem `:

### Grid Component
Represents the Grid container
|Prop|Description|
|-|-|
|`columns`| number, or `grid-template-columns` values |
|`rows`| number, or `grid-template-rows` values |
|`rowGap`| string, one of spacing values, default is `0` |
|`columnsGap`| string, one of spacing values, default is `spacing-l = 1.5rem`|
|`flow`| string, accepts `grid-auto-flow` css values |
|`justifyContent`| string, one of `justify-content` css values |
|`alignContent`| string, one of `align-content` css values |
|`inline`| boolean, sets grid container to `display: inline-grid` |

### GridItem Component
Represents the Grid Items
|Prop|Description|
|-|-|
|`columnStart`| number, accepts `grid-column-start` css values |
|`columnEnd`| number, accepts `grid-column-end` css values |
|`rowStart`| number, accepts `grid-row-start` css values |
|`rowEnd`| number, accepts `grid-row-end` css values |
|`area`| string, accepts `grid-area` css values |
|`order`| number, accepts `order` css values |

The component usage would be something like this...

```jsx
<Grid columns={12} rows={3} columnGap={'xs'}>
  <GridItem rowStart={1} rowEnd={2}>
    <p>I'll be in column 1, row 1</p>
  </GridItem>
  <GridItem rowStart={3} columnStart={2}>
    <p>I'll be in column 6, row 2</p>
  </GridItem>
</Grid>
```

### Question
- Shall we introduce optional breakpoints, and make the grid responsive ready?

Let me know what you think 😊

**Comment by wichniowski** [comment]
Hey great proposal 👏  I'm all in for a grid component and I think we should definitely introduce breakpoints. How would you enable those?

**Comment by mshaaban0** [comment]
@johanneswuerbach I was thinking about breakpoints to be something like this...
### Breakpoints

|Screen|Size|
|-|-|
| mobile | `0px - 480px` |
| phablet | `480px - 768px` |
| tablet | `768px - 1200px` |
| desktop | `1200px - 1920px` |
| desktop-lg | `1920px - ∞` |

Usage of the breakpoints should be optional, example...
* All props that controls alignments and sizes, accepts numbers or an optional object that maps values to breakpoints
`<Grid columns={12} rows={3} />`
Or
`<Grid columns={{mobile: 4, tablet: 8}} rows={{mobile: 1}} />`

**Comment by m10l** [comment]
@mshaaban0 

Looks great to me!

I think we discussed in person earlier about adding padding/margin spacing to this too. I think this would be overkill and the component should just be about grids. The only spacing should be the colGap/rowGap (or maybe gridGap would be nice to define both with a single value?). If we want something for margin/padding I'd probably bring back the Box component proposal.

**Comment by domarku** [comment]
Thanks for the proposal, @mshaaban0!

Before going into the implementation proposal, which I take is good, I would like to challenge the need or the problem it's supposed to be solving. There haven't been many examples of multi-column layouts in Contentful so far — perhaps only the space home, and not even that — and I don't know of any multi-column layouts being considered at the moment or in the near future. We recently set some guidelines for [how and when to use the workbench component](https://f36.contentful.com/guidelines/layout/workbench/), based on the content on the page. Is there a real need for it or could we make do with the workbench component for the immediate future? Is this an alternative or an addition?

Aside from the question of why do we need this, there may also be potential overhead introduced to both designers and developers by offering a new tool without a guideline on how to use it — If it's in Forma, does it mean I _have_ to use it? How many columns is a good number of columns? When would there be a need for more than two columns? How can I use columns of different widths?

Finally, even though I believe any direction towards making Contentful responsive is great, it should be discussed not only on the design system level, but also strategically — whether we ever plan on making the web app responsive and if we should include it in our efforts, prioritize accordingly etc.

@m10l @wichniowski @joaoramos Please chip in and let me know if I took too many steps back :)

**Comment by joaoramos** [comment]
How about apps? It may make sense to support grids now that customers can extend the entire screens in the web app.

**Comment by mshaaban0** [comment]
@domarku Thanks for raising your concerns!

 > I don't know of any multi-column layouts being considered at the moment or in the near future.

The grid use is not only for the main layout, It should also help developers to layout smaller blocks. without having to write their own styles. i.e

<img width="572" alt="Grid Usage" src="https://user-images.githubusercontent.com/6163988/75551969-98b53380-5a35-11ea-9709-4d31b4dcc298.png">

For an example as above, devs would have to write almost the same custom css, use specific tokens, and maybe they use the grid, or flexbox. This component here, aims to reduce that, and at the same time ensure consistency (correct spacing usage).

> Is there a real need for it or could we make do with the workbench component for the immediate future? Is this an alternative or an addition?

It's an addition, also the workbench should use it when it's in place.


> Aside from the question of why do we need this, there may also be potential overhead introduced to both designers and developers by offering a new tool without a guideline on how to use it — If it's in Forma, does it mean I have to use it? How many columns is a good number of columns? When would there be a need for more than two columns? How can I use columns of different widths?

Documentation and guidelines for designers, and developers will be in place with the component, I don't believe that designers have to use all the grid features as devs. The grid component will also make sure that designers use spacings properly, as we won't allow custom values for `rowGap`, and `columnGap`

> Finally, even though I believe any direction towards making Contentful responsive is great, it should be discussed not only on the design system level, but also strategically.

Introducing breakpoints here is completely optional, and it's also helpful to target desktop screens, and larger screens as well. I believe the component should have the proper structure and be ready for all use cases as long as it's not affecting anything.

Let me know if you have any questions. :)

**Comment by domarku** [comment]
Thanks for the clarification, @mshaaban0.

I wasn't aware of some of these uses and it would be great if we would suggest some best practices in the component documentation.

> For the above example, devs would have to write almost the same custom css, use specific tokens, and maybe they use the grid, or flexbox. This component here, aims to reduce that, and at the same time ensure consistency (correct spacing usage).

That already seems like a great benefit.

**Comment by wichniowski** [comment]
@mshaaban0 can we close this issue?

**Comment by mshaaban0** [comment]
@wichniowski yes we can, will follow up with another ticket for responsive
