### ISSUE TITLE
Table Component: showing loading state with the Skeleton Component

### ISSUE THREAD

**Issue by gui-santos** [contentful/forma-36#433]
![table_skeleton](https://user-images.githubusercontent.com/6597467/76405848-14de3e00-6389-11ea-8cbf-c17072d2dc5c.gif)

I would like to propose an extension to the Table Component (more specifically the TableBody)
The case is that, in some places, we fill tables with async data, right?
Well, one way of dealing with that would be, let's say, showing a spinner in the page and only after the data is fetched show the table.
A better pattern for the users would be mimicking the final look of the table after with the Skeleton Component that forma already have (take a look on the gif ⬆️ ).

Initially, my idea is that we could pass a bool prop to TableBody and while this is `true` we render a "SkeletonRow" instead of the TableBody's children. Something like:

```jsx
<TableBody loading={true}>
    <TableRow>
        // ... n TableCells here
    </TableRow>
</TableBody>
```
And in  /TableBody.js
```jsx
<tbody data-test-id={testId} className={className} {...otherProps}>
    {loading ? <SkeletonRow /> : children}
</tbody>
```

This would render a pretty standard skeleton row. In case the table needs a more personalised skeleton setup, you could do it without the prop by just setting the load yourself as a children (I guess... more cases will show up as this gets developed hahaha)

This is just an initial thought and I would love to know what you think about it.
And if we can already have some suggestions 😄

**Comment by m10l** [comment]
Nice, looks like a good addition!

**Comment by wichniowski** [comment]
@gui-santos can we close this issue?

**Comment by gui-santos** [comment]
@wichniowski yes! I totally missed closing this
