### ISSUE TITLE
CSS variable references in Button.css

### ISSUE THREAD

**Issue by mts** [contentful/forma-36#441]
Hello folks!

I happen to look into `forma-36-react-components` styling out of interest. 
My compliments. All looks very nicely structured. 

I noticed a couple small issues regarding CSS variable references. Just to let you know:

- `color-blue-base` reference
  I noticed the following: `background-color: var(---color-blue-base);` in
  https://github.com/contentful/forma-36/blob/7c91f8ab14b15a793cc1fc1878082234314830c1/packages/forma-36-react-components/src/components/Button/Button.css#L87

  It looks like `color-blue-base` CSS variable is referred to with three dashes instead of two. 

- `glow-warning` reference
  I also noticed `var(--glow-warning)` does not exist in https://github.com/contentful/forma-36/blob/master/packages/forma-36-tokens/src/tokens/box-shadows/glows.js

**Comment by wichniowski** [comment]
Hey @mts 👋

Thanks so much for reporting this and sorry for the late reply! We’ll look into asap!

All the best,

Johannes

**Comment by ChidinmaOrajiaku** [comment]
Hello @mts 👋, this issue has been fixed.
