### ISSUE TITLE
Allow notifications to accept a title, body, and CTA

### ISSUE THREAD

**Issue by m10l** [contentful/forma-36#442]
## Proposal

I'm proposing a change to the Notification component to allow rendering a title, body, and a CTA. 

## Approaches

Currently, the Notification component is called like so:

```
Notification.success('Text content of notification (string)', {
  duration: 6000 (int)
  canClose: true (boolean)
})
```

I can think of two approaches to achieve this:

#### Example usage:

```
const message = (
  <React.Fragment>
    <Heading>Notification title</Heading>
    <Paragraph>Some notification body copy</Paragraph>
    <TextLink href="#">Some CTA</TextLink>
  </React.Fragment>
);

Notification.success(message, {
  duration: 6000 (int)
  canClose: true (boolean)
})
```

#### Pros:
- Minimal changes required
- Uses exactly the same API to render content as before

#### Cons:
- Could end up with many different variations
- Need to refer to an example to know how to best construct message (could create NotificationTitle/NotificationBody/NotificationCta components though)

#### Example usage:
```
const message = (
Notification.success('Body text content of notification (string)', {
  title: 'Message title' (string),
  cta: {
    label: 'CTA title (string)',
    action: '() => {blah} (function)'
  }
  duration: 6000 (int)
  canClose: true (boolean)
})
```

#### Pros:
- Complete control over how component renders
- TypeScript will show API usage hints

#### Cons:
- Slightly confusing API (mix of strinng for body and settings object for title and CTA)
- Slightly more involved changes needed

**Comment by burakukula** [comment]
Hey @m10l ! 👍 from me. 
I would probably be more on the side of the second approach in that case. It might be good to keep the controll over UI elements, to not deal with different variations later on. But if adds a lot of complexity to the migration, maybe solution 1 and explicit guidelines of usage will also do the trick?

**Comment by gui-santos** [comment]
For the second approach. Would it be possible (or easy) to modify the `Notification.success()` in a way that you pass only one object as an argument instead of a string and an object?

Example:
```js
Notification.success({
  title: 'Message title',
  message: 'Body text content of notification (string)',
  cta: {
    label: 'CTA title (string)',
    action: () => void
  }
  duration: 6000
  canClose: true
})
```

**Comment by m10l** [comment]
@burakukula Thanks for taking a look, I'm leaning towards option 2 too as it's a bit more foolproof

@gui-santos This would be a lot nicer, but, if we broke the current API where you pass a string and an options object it would be a breaking change. Could possibly add it as an option in the options object too though

**Comment by suevalov** [comment]
FYI, all notifications methods are exposed to UI Extension SDK so we shouldn't do breaking changes.

What about the following:

```
Notification.success('Hello world!', {
  render: ({ message, onClose }) => (
     <div><h1>{message}</h1><button onClick={onClick}>CLOSE ME!</button></div>
  )
})
```

**Comment by m10l** [comment]
> FYI, all notifications methods are exposed to UI Extension SDK so we shouldn't do breaking changes.
> 
> What about the following:
> 
> ```
> Notification.success('Hello world!', {
>   render: ({ message, onClose }) => (
>      <div><h1>{message}</h1><button onClick={onClick}>CLOSE ME!</button></div>
>   )
> })
> ```

@suevalov So does this mean we're forced to do option 1 and option 2 isn't possible? I didn't see option 2 as being a breaking change, but maybe it is. Would some updates be needed elsewhere in either case?

**Comment by mshaaban0** [comment]
Looks good to me @m10l 
I vote for option no.1  (simpler, and no breaking change)

**Comment by suevalov** [comment]
@m10l both options are non-breaking I think

**Comment by m10l** [comment]
I'm going to close this issue and work on a PR - I'll go for solution 2 as I think it offers the more foolproof API even if it's a tiny bit weird, please raise any concerns with that in the PR.

Thanks all 🙇
