### ISSUE TITLE
Proposal for Forma36's website navigation

### ISSUE THREAD

**Issue by gui-santos** [contentful/forma-36#455]
Hey!

While working on the documentation search last Friday, I played around the navigation to try to improve it a little bit.

The issues I was trying to solve is while scrolling down to read some documentation if you want to go to another page you would need to scroll back up to find the navigation again.
The same thing happens if you want to search for something or click on a social link (Blog, GitHub and Community).

I took inspiration in how other documentation websites deal with this, like:
- [CircuitUI](https://circuit.sumup.com/) from SumUp (Storybook Docs)
- [Atlassian design](https://atlassian.design/guidelines/product/foundations/typography)
- [Pajamas](https://design.gitlab.com/) from GitLab

And I propose moving all the navigation to the side menu. Keeping the logo, the social links and the search fixed in the top left. The list of links for the components documentation would scroll independently from the content (see the gif). Also, we can keep the three categories (Foundation, Guidelines and Components) always expanded.

### Home
<img width="1792" alt="Screenshot 2020-04-06 at 13 05 50" src="https://user-images.githubusercontent.com/6597467/78563317-103b6700-781b-11ea-9f73-1586c6c475d7.png">

### Documentation Page
<img width="1792" alt="Screenshot 2020-04-06 at 13 06 09" src="https://user-images.githubusercontent.com/6597467/78563338-17627500-781b-11ea-9bfd-e044eb02a1a9.png">

### Scrolling
![Apr-03-2020 19-25-51](https://user-images.githubusercontent.com/6597467/78563407-352fda00-781b-11ea-8955-23e50152e82d.gif)

**Comment by mshaaban0** [comment]
Yo, I love this, please do it 🥺

**Comment by m10l** [comment]
Having the sidebar stay in position and giving it it's own scrollbar is a good improvement, but I'm not keen on moving the other elements into the sidebar. The idea behind things at the moment is that the side navigation is for documentation, and the items in the header are for external links.

**Comment by gui-santos** [comment]
@m10l TBH I don't have a strong argument for moving the external links to the side hahaha. I would say we can keep the topbar and give the sidebar its own scroll like in this docs:
https://tailwindcss.com/docs/installation

And it would work great... what do you think?

**Comment by m10l** [comment]
> @m10l TBH I don't have a strong argument for moving the external links to the side hahaha. I would say we can keep the topbar and give the sidebar its own scroll like in this docs:
> https://tailwindcss.com/docs/installation
> 
> And it would work great... what do you think?

I think that'd be great!
