### ISSUE TITLE
Forma 36 website search and navigation styling

### ISSUE THREAD

**Issue by domarku** [contentful/forma-36#457]
### Navigation styling

- There should be a hover state on the menu items
- There shouldn't be such a strong difference between the items that have children
- There's not really a need for a background color in the navigation — if we set it to white it would improve the contrast

![79452800-066aee00-7fe9-11ea-8164-68e77ba00264](https://user-images.githubusercontent.com/7631029/79565331-cbcc8880-80b0-11ea-8119-3e3ab8f3eb30.gif)

### Search

~The position of the search right above the website navigation is a bit misleading — it implies that it's a filter for navigation items, rather than a fully powered search across the whole website. I suggest we put the search in the top bar and trigger it with a button.~

Decided to leave the search as it is for now.

**Comment by gui-santos** [comment]
Hey @domarku 

I like your proposal to change the navigation. I believe it would be a great improvement :)

I'm thinking that the person visiting the docs would have to click the icon and then search. And then if you search something else after that, it's another click + type
What do you think about exposing the search in the bar and having it always there? So the user just needs to type and they get the results

And I made two quick alternatives for the hover and active states

![Screenshot 2020-04-23 at 11 43 24](https://user-images.githubusercontent.com/6597467/80085527-9c0dfc80-8558-11ea-9f63-b652de8c9dbc.png)

I've just used the hover color we have set for the DropdownListItem (The contrast of this hover will be increased soon once we change the color palette)
And I added that blue bar trying to mimic the active state of the Tab component

![Screenshot 2020-04-23 at 11 36 57](https://user-images.githubusercontent.com/6597467/80085521-99aba280-8558-11ea-81b5-8dfa8913369e.png)
In this one, we do the same for the hover state, but the active state is the same that you did I've just used the lightest blue.... but Idk

What do you think?

**Comment by domarku** [comment]
Hi @gui-santos,

> I like your proposal to change the navigation. I believe it would be a great improvement :)

Thanks ✌️

> I'm thinking that the person visiting the docs would have to click the icon and then search. And then if you search something else after that, it's another click + type
> What do you think about exposing the search in the bar and having it always there? So the user just needs to type and they get the results

Wouldn't the user have to click into the field to type anyway? I counted the same number of actions. Even in the case of two consecutive queries, the user would:

1. click in the field (or click on **search** to toggle a focused search field)
1. type the query
1. select and press enter to execute query
1. click in the field (or click on **search** to toggle a focused search field)
1. type the query
1. ...

I don't mind having the search bar exposed at all times but tbh it's a bit ugly to see on the blue header. Come to think of it, it's the same after we toggle it, too. I'll work on it a bit more.

> And I made two quick alternatives for the hover and active states 

Thanks for the suggestions, looks good! I prefer the second one:

> ![Screenshot 2020-04-23 at 11 36 57](https://user-images.githubusercontent.com/6597467/80085521-99aba280-8558-11ea-81b5-8dfa8913369e.png)
> In this one, we do the same for the hover state, but the active state is the same that you did I've just used the lightest blue.... but Idk
> 
> What do you think?

I wouldn't use the lightest blue, though. Perhaps the one between, to keep the contrast to WCAG standards as much as possible.

**Comment by domarku** [comment]
Looking at it more, @gui-santos, seems like the search is ok where it is now. I'll adjust my issue proposal to only focus on the navigation

**Comment by gui-santos** [comment]
> Wouldn't the user have to click into the field to type anyway? I counted the same number of actions. Even in the case of two consecutive queries, the user would:

Of course!!! 🤦 
@domarku you're 100% right... I totally missed this hahaha

So yeah! For me, this is a good proposal we should do it
thanks a lot!
