### ISSUE TITLE
💡 Proposal - CSS classNames for components by default

### ISSUE THREAD

**Issue by marcolink** [contentful/forma-36#469]
# Forma 36 contribution proposal

## The problem

In a nutshell: **Skinning nested components.**

In some cases, you want to apply custom styles to a rather complex component E.g. `Autocomplete`.

With the current system, the only way to access underlaying components like `Dropdown` is by CSS selectors of standard html tags (`div`, `ul`, `li` and so on). 

The CSS classNames currently used are driven by emotion and don't provide predictable classnames. 

(Please correct me if i'm wrong, i have a very limited experience with emotion)

## The proposed solution

A dedicated className per component following a standardized f36 convention (tbd).
In case of `Automcomplete`, it could look like this:

```css
.my-custom-autocomplete .f36-dropdown .f36-dropdown-container .f36-dropdown-list {

}
```
This would enable more control over nested (not directly accessible) components.

If this could be a way to solve the issue, what would be a good (naming) convention? 

## Breaking changes

I don't see any breaking changes with this.

**Comment by wichniowski** [comment]
Not really solving the issue of nested classNames but this is a quick idea on how we could allow for more flexibility in rendering the input elements without a breaking change: https://github.com/contentful/forma-36/pull/470

**Comment by m10l** [comment]
Hey @marcolink - the unpredictable class names are by design. We're not using emotion here, but CSS modules (enabled via post-css). We're using the hashes to help ensure we don't have any styling clashes. Sounds like @wichniowski's suggestion is the better choice for what you're after here.

**Comment by marcolink** [comment]
@m10l Thanks for providing some context to the decisions made. After chatting to @wichniowski, we came to the conclusion that [this solution](https://github.com/contentful/forma-36/pull/471) solves my issue. 

I'm fine with closing this issue for mow.
