### ISSUE TITLE
💡 Proposal - Add the References and Tags icons

### ISSUE THREAD

**Issue by domarku** [contentful/forma-36#472]
# Forma 36 contribution proposal

## The problem
There are no existing icons in the library we could use to represent references and tags.

## The proposed solution
![Screenshot 2020-05-19 at 11 15 00](https://user-images.githubusercontent.com/7631029/82309937-08e3ad80-99c4-11ea-9fe9-588daba8f88e.jpg)

Use the Local offer and Account tree icons from Material Icons
https://material.io/resources/icons/?icon=local_offer&style=baseline
https://material.io/resources/icons/?icon=account_tree&style=baseline

## Breaking changes
No

**Comment by joaoramos** [comment]
Super! Where do you plan on using it? Feel free to share a screenshot or mockup.

**Comment by domarku** [comment]
Ah @joaoramos yes of course, here's some context:

We're introducing tags in Contentful and they're going to be in a separate tab inside of the entry editor, as well as the reference tree tab. Actually, I'll add the reference tree icon as part of this proposal, as well!

Here's a screenshot with both icons:

![Screenshot 2020-05-19 at 11 15 00](https://user-images.githubusercontent.com/7631029/82309654-ae4a5180-99c3-11ea-89f7-917b045a6170.jpg)

**Comment by joaoramos** [comment]
We seem to be using filled and outlined icons interchangeably, although most times we stick to the former. As an example, that tabbed navigation uses a filled `description` icon, followed by the new outlined icons you're proposing.

This shouldn't really hold off your proposal, but rather raise a wider question about our inconsistent use of icons.

**Comment by domarku** [comment]
Oh @joaoramos, that's a good point! I missed the style completely. Thanks for noticing and bringing it up.

I would move forward with the outlined versions of the icons. Here's the preview:

![Screenshot 2020-05-19 at 11 15 00 Copy](https://user-images.githubusercontent.com/7631029/82829604-ee25a300-9eb3-11ea-98e8-9b6f7b901a4b.jpg)

**Comment by joaoramos** [comment]
BAM! 🚀

**Comment by domarku** [comment]
Great, submitting PR soon!
