### ISSUE TITLE
🐛 Bug - Documentation website bundle errors

### ISSUE THREAD

**Issue by burakukula** [contentful/forma-36#476]
We came across isssue in our documentation:

<img width="1201" alt="Screenshot 2020-05-25 at 09 52 36" src="https://user-images.githubusercontent.com/4272331/82791174-95cbb280-9e6d-11ea-881b-c7b8a0d293d0.png">

Error is coming from components package, we would need to get rid of `no-explicit-any` from there I guess. For now I added `.eslintrc` on the documentation side to make it work, but I guess it should not be handled this way.

**Comment by gui-santos** [comment]
![Screenshot 2020-05-25 at 12 01 57](https://user-images.githubusercontent.com/6597467/82802715-9f5e1600-9e7f-11ea-9277-ce818d292085.png)
"It works in my machine" - Every Developer in history moments before breaking something

But looking at the error it seems like '@typescript-eslint/eslint-plugin' it's not installed for some weird reason

or I am confused

**Comment by burakukula** [comment]
@gui-santos hmm, 🤔 strange. A mystery!
@wichniowski WDYT? As far as I remember you had also this issue on your machine yeah?

**Comment by burakukula** [comment]
Solved!
