### ISSUE TITLE
🐛 Bug - Notification overflow when too much text

### ISSUE THREAD

**Issue by Spring3** [contentful/forma-36#495]
# Forma 36 bug report

## Summary

It can be reproduced on the [Storybook](https://forma-36-react-components.netlify.app/?path=/story/components-notification--default) if you add something like this abomination as a text

```
Hello world jashjr hjqwh4j 23ghjgh4 g2hjghj21gh3zg21hg3auh21tbyu321yfb3yd12av3ruy21svyu312vyu32ayv3rty21vr3ty12rdyu3v12vg3cb12g3h g12hj fegwfghrfwghrfg3f4gh2fg4f12gf3g12f4yut21361245261853675126451267t3yu12feghasftefaster6w5467521ytesagertw4567254uygdshatdyas
```

## Environment

Latest Chrome, (v83), latest MacOS 10.15.5

## Steps to reproduce

Described above

## Expected results

No transparent background.

## Actual results

![Screenshot 2020-06-12 at 16 18 58](https://user-images.githubusercontent.com/4171202/84513024-248f5a80-acc9-11ea-955b-3c74eff99add.png)

(with a different background for better visibility)

![Screenshot 2020-06-12 at 16 24 49](https://user-images.githubusercontent.com/4171202/84513150-543e6280-acc9-11ea-91e3-834ec010af65.png)

**Comment by mshaaban0** [comment]
@Spring3 it looks like it's related to storybook black magic, it only breaks when we change knobs values (inject dynamic content), if you change the increase the characters in the stories file, it will wrap and behave as expected.

![Screenshot 2020-06-30 at 20 05 21](https://user-images.githubusercontent.com/6163988/86161096-09b44700-bb0d-11ea-8513-7a6ad022a956.png)

**Comment by Spring3** [comment]
@mshaaban0 Thanks for your reply. In fact the first time I noticed it, it was in one of the web apps. I linked storybook as the easiest way to reproduce.

**Comment by m10l** [comment]
Hey @Spring3, we're going to close this issue as it looks like a bug with the Storybook canvas. Thanks for reporting though!
