### ISSUE TITLE
💡 Proposal - Icons Package

### ISSUE THREAD

**Issue by mshaaban0** [contentful/forma-36#506]
## The problem

As we expand and scale, we see a rise in requests to add more icons, whether the user is building a feature in Contentful web-app, a separate app or an internal tool, etc.

With the current structure adding more icons will increase the bundle size, and it also increases the overhead on the maintainers to follow up on what goes in and out.

## The proposed solution

Moving all icons to a separate new package `@contentful/forma-36-icons` where users can import only what they need as svg which will get inline within their bundle

This way we can have a huge icons library without worrying about f36 or consumer's bundle size as they only get what they ask for.

Adding extra icons would be simpler, and doesn't require much reviews

Removing icons in the future won't be necessary, and we could avoid potential breaking changes, and easily support backward compatibility

**Usage example**
```js
import { search } from '@contentful/forma-36-icons`
import { Icon } from '@contentful/forma-36-react-components`

<Icon color="primary" size="m" icon={search} />
```

## Breaking changes
This change will eventually require forma-36 to remove the current icons from our bundle, and consumers will need to migrate accordingly

## Other thoughts
Possibly we could upload these SVG icons to `S3` bucket and keep only reference inside the package for faster builds?

**Comment by joaoramos** [comment]
That sounds terrific, @mshaaban0 👏 Do you foresee any other risks, besides the required migration?

**Comment by domarku** [comment]
Great proposal! If we go with S3, would adding new icons be as trivial as it is today?

**Comment by m10l** [comment]
Nice, sounds good. I'd advise against S3 - it'd make the contribution process a lot harder and less-open.

**Comment by burakukula** [comment]
@mshaaban0 sounds great! 👏 The only thing that comes to my mind is the fact that when it comes to usage, there is one additional import, but that's a minor I guess. Icon API would stay the same as far as I understand.
This would be a breaking change in F36 right?

**Comment by mshaaban0** [comment]
@joaoramos @m10l @domarku I can’t think of other potential issues tbh, but thinking more about this Mike is right, adding icons to S3 won’t be as easy as it is today. Having them within the package directly will do for now I think.

@burakukula yes this would be a breaking change once we remove the icons from the library, as a start we can move the current icons to the new package and have some sort of mapping, deprecate the current usage, and remove them in the next major release, then it would be a breaking changes.

**Comment by gui-santos** [comment]
I think it's a good idea!

Can I also suggest that in the icons package we add more material icons?
Right now, when someone needs an icon we tell them that we are using material design icons and they just need to choose one that suits them and open the PR. So I thought that since we are doing this, why not add more material basic icons that will be requested soon? (like the calendar one that was requested the other day)

**Comment by domarku** [comment]
> I think it's a good idea!
> 
> Can I also suggest that in the icons package we add more material icons?
> Right now, when someone needs an icon we tell them that we are using material design icons and they just need to choose one that suits them and open the PR. So I thought that since we are doing this, why not add more material basic icons that will be requested soon? (like the calendar one that was requested the other day)

That would be cool! How would we choose which ones to add? 🤔

**Comment by domarku** [comment]
(sorry, clicked `Close and comment` by mistake)

**Comment by gui-santos** [comment]
> That would be cool! How would we choose which ones to add? 🤔

I can only see two alternatives, tbh.
The most tedious one is going through the material icon library and picking the ones we think will serve some purpose in Forma36. 
The more "lazy" one hahaha, we get all icons put them in the package and make sure we do a good code-splitting in the library, so when the user imports an icon it only imports that icon and not the whole package. This way, the package can have a huge amount of icons, and it will not matter to our user's bundles (right?).

But some material icons won't ever be used so I kind of prefer the tedious option

**Comment by domarku** [comment]
The current process of adding an icon or two seems like the least tedious
of the three, and we get to keep it reduced to the ones we really use.
Going through the material icon library and picking the ones we might use
in the future feels like uncertain guessing.

Dominik Markušić
Product Designer, Developer Workflows

Contentful GmbH
Ritterstraße 12-14
10969 Berlin, Germany <https://goo.gl/maps/9qViWH2BwXB2>

www.contentful.com

Privacy Policy <https://www.contentful.com/legal/de/privacy/>

Registration Court: Berlin-Charlottenburg HRB 155607 B

Managing Directors: Steve Sloan, Paolo Negri, Dr. Markus Harder

**Comment by gui-santos** [comment]
I see I see... I mentioned this idea just because it was a comment made last week about the current process. But I also prefer that people open a PR to add icons to the set, we just need to communicate why we have this process in place I think

**Comment by suevalov** [comment]
Related to https://github.com/contentful/forma-36/pull/879 and https://github.com/contentful/forma-36/pull/880
