### ISSUE TITLE
💡 Proposal - Accordion Component

### ISSUE THREAD

**Issue by gui-santos** [contentful/forma-36#513]
# Forma 36 contribution proposal

## The problem

In the feature that I'm working on we had to create a FAQ section for a page. But the content of around 6 questions is quite long to be always on the page, also a user may want to know about one thing only so scrolling over the other 5 questions would be annoying or make the user miss what they a looking for. 

## The proposed solution

Let's create an Accordion component. It would also need an `<AcordionHeader />` and an `<AcordionPanel />`

[prototype](https://www.figma.com/proto/q73ZvGDXXliJTyMklNDmJq/Accordion?node-id=16%3A0&viewport=-245%2C-150%2C0.39369869232177734&scaling=min-zoom)

![Anatomy](https://user-images.githubusercontent.com/6597467/88805539-90f9e680-d1af-11ea-8b77-df2e50883742.jpg)

> **Accordion Header:**
> Label for or thumbnail representing a section of content that also serves as a control for showing, and in some implementations, hiding the section of content.
> **Accordion Panel:**
> Section of content associated with an accordion header.
> (taken from [WAI-ARIA](https://www.w3.org/TR/wai-aria-practices-1.2/#accordion))

### Chevron variation

We could have a prop to define two different alignments for the chevron

![Chevron Orientation](https://user-images.githubusercontent.com/6597467/88805941-1087b580-d1b0-11ea-925e-395bf2f43bd5.jpg)

### Hover/Focus state

For hover and focus state we can use the same styles we use in the `naked` button

![Focus state](https://user-images.githubusercontent.com/6597467/88806019-29906680-d1b0-11ea-9147-1c5b43ad64a2.jpg)

Considering the case where the accordion has a gray background, this is how it would look
![Focus state GRAY](https://user-images.githubusercontent.com/6597467/88805989-22695880-d1b0-11ea-87a0-ed64c5ac4096.jpg)

### Usage

The component allows other components to be passed as a title for the accordion, but it is better to avoid abusing this feature. In most cases, a Heading or Subheading component will be enough.
It's worth to point out that there is a case in Contentful's webapp where we have a `...` button in an accordion header. I propose that his pattern should not be supported because it harms the accessibility of the component. The reason for this can be checked in the [W3 docs for accordions](https://www.w3.org/TR/wai-aria-practices-1.2/#wai-aria-roles-states-and-properties)

> - The title of each accordion header is contained in an element with role button.
> - Each accordion header button is wrapped in an element with role heading that has a value set for aria-level that is appropriate for the information architecture of the page.
>   - If the native host language has an element with an implicit heading and aria-level, such as an HTML heading tag, a native host language element may be used.
>   - The button element is the only element inside the heading element. That is, if there are other visually persistent elements, they are not included inside the heading element.

![DO and DONTS](https://user-images.githubusercontent.com/6597467/89034197-c716a200-d338-11ea-8038-3bad3be82b44.jpg)

## Important requirements
- Accessibility following [WAI-ARIA](https://www.w3.org/TR/wai-aria-practices-1.2/#accordion)
- Possibility to pass other components to the Accordion Header

## Breaking changes

Uhmmm I don't think there is any breaking change, but maybe we would release it as an alpha component first

**Comment by domarku** [comment]
Great proposal, do it!

I'm never sure of the right position of the arrows (chevrons) so that the user is sure their click will expand the accordion and not be a link or a button to take them to another tab / page.

This is what we have in the web app (Saved views) and I think that works well.

![saved-views-cf](https://user-images.githubusercontent.com/7631029/87311823-0ca53380-c520-11ea-91a8-5a60e963c9bf.gif)

If you, or the designer that did this prefer to have arrows on the right side, it might make more sense to have the closed state with the chevron pointing down instead of right, kind of indicating the user's wish — "I want to expand this downwards".

**Comment by gui-santos** [comment]
Aha! I totally missed the accordion we have in Saved Views at Contentful's web app. I also never know what to do with the chevrons I just wanted to quick start this, but I agree with the suggestion. I think we should try to keep the same pattern that it's already in use :)

Thanks a lot!

P.S.: I was trying to keep my proposal text very neutral as if I was just another public user hahaha sorry, but the designer (Grace) is sick today I will show her this another day

**Comment by domarku** [comment]
Yeah, great suggestion!

As far as the position and orientation of chevrons, it depends on the usage of the accordion. Maybe we could have both options, like the [accordion from Carbon](https://www.carbondesignsystem.com/components/accordion/usage/#live-demo).

1. If the accordion is used for any kind of navigation, it makes sense for the chevrons to be on the left.
2. If the accordion is used for information, e.g. an FAQ section, it makes sense for them to be on the right.

Also, for the first case, it would be good if the accordion could hold any other component and not only a paragraph of text. Like in the Saved views example. Not sure if that's something to consider while implementing.

Hehe no worries. If Grace is up to help you with the design that would be great.

**Comment by gui-santos** [comment]
I love Carbon and its documentation! Great reference

I agree with using the chevron on both sides, depending on if it's navigation or information. It makes sense

> Also, for the first case, it would be good if the accordion could hold any other component and not only a paragraph of text. Like in the Saved views example. Not sure if that's something to consider while implementing.

Yes! And I think we will need to do the same for the header of the accordion. In the example of the saved views, you can see that the header is also not only text, but it also has buttons

> Hehe no worries. If Grace is up to help you with the design that would be great. Note to self or anyone designing it: we need to consider a11y, size, hover states, mouse and keyboard interaction and animation.

Yes! I'm already checking the [W3C design pattern for Accordions](https://www.w3.org/TR/wai-aria-practices-1.1/#accordion) maybe I will mention it in the proposal.
I'm still working on the different states, and I will update this proposal whenever I have them.
Regarding animation, specifically the collapsing/expanding animation, I was thinking of working on it as a follow-up proposal because the accordion we have in the saved views has no animation for expanding and collapsing, so this component wouldn't look inconsistent.
What I have in mind for the follow-up proposal is a component for collapsing/expanding that would be possible to use in other places if we need it. (... and maybe using FLIP technique to make it performant and hipster)

But if everyone prefers, we could include the animation here as well

**Comment by domarku** [comment]
Amazing 👍 

> Regarding animation, specifically the collapsing/expanding animation, I was thinking of working on it as a follow-up proposal because the accordion we have in the saved views has no animation for expanding and collapsing, so this component wouldn't look inconsistent.

Great, that's exactly what I thought by _consider_ :)

**Comment by joaoramos** [comment]
Good one! I advise against collapsing sections automatically when one section gets selected, if you ever consider introducing that behaviour. Otherwise, I'd move forward 🚀

**Comment by gui-santos** [comment]
@joaoramos makes sense! I will avoid that

I think I will have time to go back to Accordion by the end of the week. I will update you all here when I get more stuff done
Thanks a lot for the suggestions so far 🙏

**Comment by gui-santos** [comment]
[SPOILER]:
I will open a PR with all the code, but I think it's worth posting the animation here to document the design process of the component I guess.

This is the animation I managed to make. I will study a way to make it more performant, but I think it is good for now. It is already using the duration and the easing tokens from Forma36

![animation](https://user-images.githubusercontent.com/6597467/89056055-b3c8fe00-d35b-11ea-887c-ae11c1eff430.gif)

(the quality of the GIF is 💩  and you can't see the focus state, but this was recorded only using keyboard so a11y is there 😄 )

**Comment by mshaaban0** [comment]
Looks really good @gui-santos ⚡ 
Love the fact that we're looking into a11y more.
One way I would build this, is using `summary` & `details` html5 tags to benefit from the default browser functionality, and reduce the use of aria roles.

**Comment by gui-santos** [comment]
@mshaaban0 oh I used I bunch of aria attributes, let me open my PR and then you point me where I can use summary and detail, thanks a lot!
