### ISSUE TITLE
🐛 Bug - DropdownList off screen limits

### ISSUE THREAD

**Issue by giotiskl** [contentful/forma-36#523]
# Forma 36 bug report

## Summary

The `DropdownList` that appears when you click on the context menu icon (3 dots) of the last item in the folder view of the content page (`https://app.contentful.com/spaces/{:spaceId}/entries`) is cut off of the screen in smaller resolutions, as in the screenshot (unless you zoom out your browser window).

This has as a result that the user cannot click on the `Delete` button which is the last item in the dropdown list.

![IMG_20200721_094938](https://user-images.githubusercontent.com/12873414/88030159-302d3700-cb3b-11ea-8812-31ccfdd5649d.jpg)

## Environment

Latest chrome on osx

## Steps to reproduce

1. Go to `https://app.contentful.com/spaces/{:spaceId}/entries`.
2. Find the last list item in the folders view.
3. Click on its context menu button (3 dots)
4. See the dropdown list which is off the screen limits

## Expected results

`DropdownList` is within screen limits and I can normally interact with it.

## Actual results

`DropdownList` is off screen limits and I cannot normally interact with it.

**Comment by gui-santos** [comment]
@mshaaban0 suggested us to use this:
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

🤯

**Comment by gui-santos** [comment]
It turns out, we won't need to change anything in Forma36
There is a PR for a fix in Contentful's web app to enable the auto-align prop in the implementation of the CardAction component. Once that is deployed I will close this issue :)
