### ISSUE TITLE
Reference Card React component

### ISSUE THREAD

**Issue by vincenzomilone** [contentful/forma-36#53]
Hi, 

I'm using forma-36-react-component in leatest ui-extensions. I think it's a great work 💪 !

The problem involve the `<ReferenceCard />` component. 

In version **2.0.1-alpha.0** the component it's smooth and beautiful:
![reference-card-2 0 1-alpha 0](https://user-images.githubusercontent.com/1504134/51393879-14596700-1b39-11e9-9d21-43084fb4488d.png)

But in version **2.0.2**...
![reference-card-2 0 2](https://user-images.githubusercontent.com/1504134/51393898-276c3700-1b39-11e9-9072-5853c9dee69b.png)

How you can see there is:
- giant font size;
- useless empty space for missing description.

Is it possibile to go back to previus verision? Or can you show me another solution?

Thanks,
Vincenzo

**Comment by wichniowski** [comment]
Hey @vincenzomilone! First of all, thank you for submitting the first Issue! 🎉🎉

We're very happy about your feedback and that you enjoy working with Forma 36!

Yes, we fixed the height of the reference card and adjusted the font size for usage in the Rich Text editor. We're currently discussing to add a dynamic height property and a small text variation to this component to enable the previous layout.

Right now a possible workaround is to pass another class name through the `extraClassNames` prop and overwrite the height and font size. See this example: https://codepen.io/DEVFROMABOVE/pen/PVbeGW

I also just realized that we will have a call on Friday and I'm looking forward to discussing this issue in person :)

**Comment by vincenzomilone** [comment]
Hi, 

thank you for the answer.

> We're very happy about your feedback and that you enjoy working with Forma 36!

Yeah, I think it's really a good React UI library. I was using a custom made UI library to speed up UI-extensions development in the last year, so having an official replacement it's a time saving improvement.

> I also just realized that we will have a call on Friday

OMG It's true... 🙂

Vincenzo
