### ISSUE TITLE
🐛 Bug - NavigationIcon documentation page is missing

### ISSUE THREAD

**Issue by gui-santos** [contentful/forma-36#530]
# Forma 36 bug report

Not a real bug, but we forgot to add a page in the docs for the NavigationIcons (probably will be renamed to ProductIcon)

**Comment by burakukula** [comment]
@gui-santos yeah, I was thinking to add it as soon as I manage the migration to the ProductIcon name. WDYT?

**Comment by gui-santos** [comment]
@burakukula makes total sense

**Comment by burakukula** [comment]
Done ✅
