### ISSUE TITLE
💡 Proposal - EntityListItem selection

### ISSUE THREAD

**Issue by Spring3** [contentful/forma-36#533]
# Forma 36 contribution proposal

## The problem

Currently EntityList can only render the EntityListItems. It would be a huge help if it could support selection, just like Cards component does.

## The proposed solution

Support the `selected` or `isSelected` property for the EntityListItem, that will, if `true`, apply styles to the EntityListItem, highlighting it as a selected item.

[Please check the way Cards currently work](https://forma-36-react-components.netlify.app/?path=/story/components-card--default) and I think replicating the same behaviour for the EntityListItem, would be just perfect for this feature

## Breaking changes

No breaking changes

**Comment by joaoramos** [comment]
Yeah, that totally makes sense. Let's just make sure that ties in nicely with the existing behaviour when clicking EntityListItem in the web app right now.

**Comment by Spring3** [comment]
@joaoramos the idea is not to change the logic behind the click, but just to introduce a new prop, that would mark the EntityListItem as selected and apply styles.

Right now I can assign onClick to each item and then add them to an array of selected items on click, but they won't be highlighted. So this prop will allow me to highlight them out of the box too, not touching the onClick behaviour

**Comment by domarku** [comment]
I think the [Toggle button](https://forma-36-react-components.netlify.app/?path=/story/components-togglebutton--default)'s active state would be a better choice here, because

- the visual difference between idle and selected is a bit stronger
- the Card's isActive looks too similar to a focused state on form elements

**Comment by m10l** [comment]
Sounds good. I'd either keep the selected styles the same as the card, or use the active state from the toggle button and update everything else with an active state. I think it'd be fine to go with the first and do the second as a separate task

**Comment by burakukula** [comment]
I would be great to add keyboard support

**Comment by domarku** [comment]
> @domarku do you mean something like this?
@gui-santos sorry I missed your question! Exaxctly, that's what I meant
