### ISSUE TITLE
💡 Proposal - EntityList ref prop

### ISSUE THREAD

**Issue by Spring3** [contentful/forma-36#534]
# Forma 36 contribution proposal

## The problem

When scrolling through the EntityList, there is currently no way to securely attach an event handler to the HtmlElement.
There is a way to do so by querying the DOM and searching by id, but there is no guarantee, that the item, that will be fetched, is the correct copy of the component.

## The proposed solution

I propose to allow passing a ref to the EntityList.

```js
   const entityListRef = useRef();
   return (
      <EntityList
         ref={entityListRef}
      />
   );
```

This will allow to then attach event handlers, like let's say detecting if we hit the bottom of the list

```js
   entityListRef.current.addEventListener('scroll', onScroll):
```

## Breaking changes

No breaking changes

**Comment by joaoramos** [comment]
Excellent! A tiny improvement that may pack a big punch. Would this also allow to scroll a specific item within `EntityList` into view? e.g. if there's an highlight, or something which needs attention.

**Comment by Spring3** [comment]
@joaoramos adding a support for ref won't impact any of the functionality on it's own. Implementation will, so if we want to block scrolling, we might have a way to do that by blocking the event. But this would be have to be done explicitly. By allowing to pass a ref, we just provide an ability for devs to have more flexibility around the html element, instead of just the react component, that is a wrapper around the native html element. The scrolling event handler was provided just as an example.

**Comment by m10l** [comment]
Sounds good! No objections from me :)
