### ISSUE TITLE
💡 Proposal - EntityListItem optional thumbnail

### ISSUE THREAD

**Issue by Spring3** [contentful/forma-36#535]
# Forma 36 contribution proposal

## The problem

Currently if an entity doesn't have a link to the image file, or a link to an asset, that doesn't have an image file, a thumbnail renders a generic image on a grey background. This doesn't always help differentiate between the EntityListItems and in fact makes each look the same and the focus shifts towards the thumbnail, instead of the title or the description of the EntityListItem, since most humans read from left to right and top to bottom, the first thing they see is a generic thumbnail.

## The proposed solution

It would be great, if EntityListItem allowed to make such thumbnail optional. Just like EntityCard does.

I think, a good way to do it without introducing a breaking change, would be to support a boolean property `withThumbnail` or similar, that, by default, may be `true`, but if `false` is given, should not render the thumbnail at all.

## Breaking changes

No breaking changes

**Comment by joaoramos** [comment]
Sounds like a good idea. So thumbnails would only be shown if the asset they're related to links to an image file and not, for instance, a PDF or a text file. Right? If that's the case, I'd go with `true` by default as you suggested.

**Comment by Spring3** [comment]
Yeah, for now it displays a generic thumbnail for a mime type of an asset, or if the asset is missing, it just renders some common image. So `true` should keep the same behaviour, but the adding a prop would allow to hide the thumbnail if not needed, and it will not introduce a breaking change

**Comment by m10l** [comment]
Just some background: The icons for asset/entry were implemented as a design decision as the intention was to use entries and assets within the same list and using these icons would allow users to quickly differentiate between the two. This icon currently changes based on the `entityType` prop.

Initially, we considered just using a thumbnail if it exists, but this would mean assets would have a different layout and would suck for scannability as the entity list items would no longer be uniform.

Maybe this concern isn't valid for your implementation though, so I'm okay with adding a prop to show this and setting it as true by default as you suggested.
