### ISSUE TITLE
🐛 Bug - ListItem doesn't enforce list-style-type

### ISSUE THREAD

**Issue by mshaaban0** [contentful/forma-36#549]
## Summary

When using `ListItem` the `li` style-type gets overridden by higher level definitions. e.g. the webapp legacy css contain the following:
```css
ul li {
  list-style-type: none;
}
```

This overrides the ListItem styles, as there's no `style-type` defined for it within the component.

## Expected results

`List` and `ListItem` should retain the `list-style-type` default styles, and potentially provide an api to choose between different `list-style-type` values

**Comment by developerKumar** [comment]
Ciao!

I am looking to contribute to open source issues, I believe this might be a good start. May I submit a PR for this issue?

**Comment by burakukula** [comment]
@developerKumar it would be great! 🚢
