### ISSUE TITLE
💡 Proposal - Change the card border radius to 3 or 4

### ISSUE THREAD

**Issue by Gracegross** [contentful/forma-36#556]
# Forma 36 contribution proposal

The border radius of cards is 2. This curve is too small to detect with the human eye. It might as well be square. The square border looks quite harsh in the new space purchase flow. 

Change the border radius to 3 or 4.

None

Border radius 2
![BorderRadius2](https://user-images.githubusercontent.com/69515265/92454775-2fbb2f00-f1c1-11ea-86f5-859f7d6f921e.png)

Border radius 3
![BorderRadius3](https://user-images.githubusercontent.com/69515265/92454780-30ec5c00-f1c1-11ea-920d-e1e7cc500483.png)

Border radius 4
![BorderRadius4](https://user-images.githubusercontent.com/69515265/92454785-321d8900-f1c1-11ea-80c6-161efc99c9f2.png)

**Comment by domarku** [comment]
Thanks for the proposal @Gracegross! I don't see why not to increase the card border-radius, but let's see if the others have a different opinion. Either higher value is good, but I would vote for 3px to keep it consistent with the [modal](https://f36.contentful.com/components/modal/).

Looking at the rest of the components, most of the border-radiuses on smaller components — e.g. buttons — are 2px, modals have 3px and only the tooltip has 4px (which would make sense to change to 2px as well, but that's another issue).

**Comment by gui-santos** [comment]
> Looking at the rest of the components, most of the border-radiuses on smaller components — e.g. buttons — are 2px, modals have 3px and only the tooltip has 4px (which would make sense to change to 2px as well, but that's another issue).

Hmmmm 🤔  now that you mentioned this... Should we get this opportunity to change all those radii and make them more consistent? Make them all 3px, for example

I don't think it would be a breaking change, but I don't know hahahah

**Comment by m10l** [comment]
I'd say it's not a breaking change unless it changes the API of a component.

What I think we should do is add some new border-radius tokens to the `forma-36-tokens` package. We currently only have CSS custom properties in the [component library](https://github.com/contentful/forma-36/blob/master/packages/forma-36-react-components/src/styles/settings/borders.css) for border-radius.

So, we could add a `forma-36-tokens/src/tokens/border-radius/border-radius.js` file with the content:

```js
const borderRadius = {
  'border-radius-small': '2px',
  'border-radius-medium': '4px',
};
```

Using 3px used to be a bit iffy for low-dpi displays and caused issues with antialiasing. I'm not sure that's a big deal anymore, but I'd recommend using 4px anyway if we go with this token approach. It'll help differentiate the two border radiuses.

**Comment by domarku** [comment]
👍 @m10l this is a good point 👇 
> Using 3px used to be a bit iffy for low-dpi displays and caused issues with antialiasing. I'm not sure that's a big deal anymore, but I'd recommend using 4px anyway if we go with this token approach. It'll help differentiate the two border radiuses.

**Comment by Gracegross** [comment]
@gui-santos @domarku This is what it looks like with cards/buttons at 4
<img width="525" alt="Screenshot 2020-09-10 at 13 15 43" src="https://user-images.githubusercontent.com/69515265/92722349-be69b080-f367-11ea-8be2-08a896d6dbe0.png">


And at 2
<img width="516" alt="Screenshot 2020-09-10 at 13 16 08" src="https://user-images.githubusercontent.com/69515265/92722378-cc1f3600-f367-11ea-933c-6cb4dbc0c591.png">


**I prefer 4!**

**Comment by domarku** [comment]
> I prefer 4!

Me too! Vote 4px!

**Comment by gui-santos** [comment]
Yep I vote 4
and I vote for @m10l token idea
and I vote for using the token in the components we want to make the radius consistent (respecting their API as @m10l said too)

**Comment by burakukula** [comment]
Cool, I will take care of introducing new token and update of the components.

**Comment by burakukula** [comment]
Done. ✅ closing this ticket. 🎉
