### ISSUE TITLE
💡 Proposal - string as a prop value for Skeletons?

### ISSUE THREAD

**Issue by Spring3** [contentful/forma-36#559]
# Forma 36 contribution proposal

## The problem

The problem is that when I use `SkeletonImage`, I can not make it stretch to the full width of the container, because the prop type, that the component expects is a number. So I can't pass let's say `100%` as a prop to make it behave that way.

Same as that if I don't have fixed width for the container, setting a fixed number won't work here.

## The proposed solution

Allow string values for width, height props

## Breaking changes

expected prop type

**Comment by domarku** [comment]
Sounds good to me. Do we need to have validations for possible `width` values, like `auto` or length in units?

**Comment by joaoramos** [comment]
👍

**Comment by m10l** [comment]
> Sounds good to me. Excuse the non-educated technical question, but would we then need to have validations for possible `width` values, like `auto` or length in units?

@domarku TypeScript helps us with this :)

**Comment by mshaaban0** [comment]
Closing this, all skeleton components accepts numbers and strings now.
