### ISSUE TITLE
💡 Proposal - Pill component color variants

### ISSUE THREAD

**Issue by burakukula** [contentful/forma-36#585]
Hello!
We came across potential need for color variants for Pill component. Not sure if that's something that we would like to consider. 

# Forma 36 contribution proposal

![pill](https://user-images.githubusercontent.com/4272331/95211256-a2352400-07ec-11eb-9b0d-96fffedb416d.gif)

## The proposed solution
Extend component to contain more variants. Maybe it would be necessary to get feedback from designers in terms of the needs here. @domarku WDYT?

## Breaking changes

This change would be a minor version I would say.

**Comment by burakukula** [comment]
Hey there! @domarku what do you think about this proposal? does this make sense? I'm also wondering about the mustard color in the example. what's the reason behind it?

**Comment by domarku** [comment]
Hey @burakukula! We finally came to a point where this is tackled again. I'm using the pill component for tags and need to have an "active" state for items that have been changed in the list.

(The orange (mustard) color in the example was the first iteration. I've toned it down now.)

### Proposal

Have an "active" state for the pill component.

![Screen Shot 2021-02-08 at 18 59 33](https://user-images.githubusercontent.com/7631029/107261614-cd03e300-6a3f-11eb-9801-553af28c6857.png)

### Preview

https://user-images.githubusercontent.com/7631029/107261625-cf663d00-6a3f-11eb-93e9-e468ebab7033.mp4

**Comment by domarku** [comment]
P. S. As you can see in the screencast above, we use a "deleted" state — no remove button, 0.5 opacity and a strikethrough

<img width="248" alt="Screen Shot 2021-02-22 at 15 53 09" src="https://user-images.githubusercontent.com/7631029/108724864-149d6b00-7526-11eb-8ca2-eb3217b32210.png">

**Comment by denkristoffer** [comment]
I think having states makes sense. Are variants still a part of the proposal then @domarku?

**Comment by domarku** [comment]
Awesome! Good to hear. I don't think we need variants, then. I'll see if my teammates can open a PR for this. Thanks for the feedback!

**Comment by damienxy** [comment]
FYI, I'll start working on this

**Comment by suevalov** [comment]
Closed by #874
