### ISSUE TITLE
💡 Proposal - Asset upload field should get visual change on file over

### ISSUE THREAD

**Issue by lukasoppermann** [contentful/forma-36#599]
# Forma 36 contribution proposal

## The problem

When a file is dragged onto the upload field, no indication is shown that the position is correct. (If you drag outside the image is opened instead of uploaded).

<img width="807" alt="Screenshot 2020-10-21 at 11 08 20" src="https://user-images.githubusercontent.com/813754/96699086-2b705d00-138e-11eb-96b9-dc1a6767b3d7.png">

## The proposed solution

1. Visual indication of correct position (e.g. blue outline or filling the field blue and adding "upload")
2. Even better would be to allow the entire screen to be used for uploading so no matter where I drag it uploads. Still an indication would be needed.

## Breaking changes

None

**Comment by joaoramos** [comment]
Thanks for the proposal, @lukasoppermann 👏 This is a good one. I'd go with 1) as the proposed solution.

**Comment by domarku** [comment]
Thanks for submitting the issue, @lukasoppermann. We would usually invite you to submit a PR with the proposed change, but since this is not a Forma component, we'll put it in our team backlog and change as soon as possible. Cheers!
