### ISSUE TITLE
🐛 Bug - Autocomplete component

### ISSUE THREAD

**Issue by ihuntington** [contentful/forma-36#613]
# Forma 36 bug report

## Summary

The Autocomplete component does not render the list of options after an intial suggestion has been displayed. This happens when the items have been fetched and passed into the component. If the items are hard coded or referenced from a variable then the component behaves as expected.

## Environment

I have tested this with v3.63.5 of the @contentful/forma-36-react-components package in stable builds of Chrome, Firefox and Safari.

## Steps to reproduce

1. Asynchronously reference the items and pass into the Autocomplete component
2. Click the dropdown arrow of the Autocomplete and no list of options are shown
3. Type in the input and sometimes on the first use a match is found. Change the value of the input to another option and no results are shown.
4. Using the input from this point on, not even the first match is shown again if type in

Along the lines of:

```
// fruits.json
[
    { id: 1, name: "apples" },
    { id: 2, name: "bananas" },
    { id: 3, name: "pears" },
];

const [fruits, setFruits] = useState([]);

useEffect(() => {
    const getFruits = async () => {
        const response = await fetch("/fruits.json");
        const data = response.json();
        setFruits(data);
    }

    getFruits();
}, []);

<Autocomplete
    maxHeight={100}
    items={fruits}
    onQueryChange={handleQueryChange}
    onChange={handleChange}
    placeholder="Choose a fruit"
    width="full"
    emptyListMessage="There are no fruits to choose from"
    noMatchesMessage="No matches"
>
{(options) =>
  options.map((option) => (
    <span key={option.id}>{option.name}</span>
  ))
}
</Autocomplete>
```

## Expected results

- I expected to see a list of items when clicking the dropdown arrow.
- I expected to have matches when typing values into the autocomplete

## Actual results

- I did not see a list of items when clicking the dropdown arrow
- I received a match on the first use of the component but after that no matches

**Comment by mshaaban0** [comment]
Hi @ihuntington Thanks for the detailed issue.

I can see that your list of items are missing the `label` property, can you please try this:
```js
[
    { id: 1, name: "apples", label: "apples" },
    { id: 2, name: "bananas", label: "bananas" },
    { id: 3, name: "pears", label: "pears" },
];
``

**Comment by denkristoffer** [comment]
I'm going to close this issue for now, hopefully the issue was what @mshaaban0 pointed out. Feel free to reopen if that's not the case.
