### ISSUE TITLE
💡 Proposal - Remove underline in links

### ISSUE THREAD

**Issue by Gracegross** [contentful/forma-36#627]
# Forma 36 contribution proposal

**Comment by gui-santos** [comment]
I'm down for it!

How should the hover state be? Underline or just a different blue?

**Comment by Gracegross** [comment]
> I'm down for it!
> 
> How should the hover state be? Underline or just a different blue?

Yes!!! fabulous idea

**Comment by domarku** [comment]
Thanks for the proposal, @Gracegross!

Making the links just another color might not be enough to separate them from the rest of the text. We could also make the links thicker (like a semibold or a bold) and do what @gui-santos suggested on hover.

**Comment by denkristoffer** [comment]
As long as there's some sort of way to differentiate links from body text for colour blind people. I'm sure we can come up with something good 🙂

**Comment by Gracegross** [comment]
Here are the accessiblity guidelines I found:

- A non-color indicator, such as an underline, must be present on hover
- The contrast ratio between the surrounding text and the background must be at least 4.5:1
- The contrast ratio between the link and the background must be at least 4.5:1
- The contrast ratio between the link and the surrounding text must be at least 3:1.


I propose these changes:
- underline on hover
- change colour from 3965AD to 2E75D4 ...this is a higher contrast
- thoughts on making it semi-bold? I'm not too opinionated but I think it might be a little bit too much


Here is the current version and 2 new versions... one semibold, one regular
<img width="689" alt="Screenshot 2020-11-06 at 14 11 17" src="https://user-images.githubusercontent.com/69515265/98369872-f294e100-2039-11eb-8e4b-840123844beb.png">



<img width="690" alt="Screenshot 2020-11-06 at 14 10 28" src="https://user-images.githubusercontent.com/69515265/98369843-e3ae2e80-2039-11eb-8fd3-a678d203576c.png">

<img width="682" alt="Screenshot 2020-11-06 at 14 10 16" src="https://user-images.githubusercontent.com/69515265/98369838-e27d0180-2039-11eb-9caf-76ec2786cc8e.png">

**Comment by m10l** [comment]
Nice! Like the changes 🚀

**Comment by domarku** [comment]
Cool, me too! Vote for semibold 👍

**Comment by m10l** [comment]
I'd vote against semibold as it'd have a negative impact on our Rich Text editor. Could be a prop though

**Comment by domarku** [comment]
Wait, what's the negative impact? Inline links? Seems like it wouldn't be a big change (or am I looking at the wrong thing)

![Uploading Nov-06-2020 18-11-35.gif…]()
