### ISSUE TITLE
💡 Proposal - Forma36 v4

### ISSUE THREAD

**Issue by burakukula** [contentful/forma-36#653]
# Forma 36 v4

## The problem
We are getting closer to release next major version of the library. Let's gather all the changes that would go into the v4 in the issue, so we would have an overview of the upcoming change. 

## The proposed solution
List of the updates for the V4:

- [ ] components are distributed into several packages
- [ ] icons moved to the separate package (remove Icon and ProductIcon from react-components)
- [ ] Illustration component  - not used in the webapp, maybe we can deprecate this component (?)
- [ ] IconButton clickable area - https://github.com/contentful/forma-36/pull/650
- [x] move Grid to GA
- [x] move Flex to GA
- [x] support higher Node versions
- [x] remove InViewport component (?)
- [ ] accessibility improvements #601
- [ ] accessibility improvements for Autocomplete
- [x] Drop support for old browser versions - use the same as Contentful (https://github.com/contentful/browserslist-config)
- [ ] CSS-in-JS with Emotion 10
- [ ] Fully controlled or fully not-controlled components
- [x] Export prop types
- [x] Rename font weight exports to semantic names

Please, edit the proposal with the updates that could go into the V4 from your perspective.

## Breaking changes

V4

**Comment by denkristoffer** [comment]
Exciting 🙌 

I would like to propose we land a11y improvements (#601) – I'm especially thinking of proper keyboard accessibility.

**Comment by gui-santos** [comment]
Since this just happened and I think we should not forget it

Can we make v4 publish the CSS together with the components? So the consumer of the library does not need to import the CSS in their project?

**Comment by denkristoffer** [comment]
Absolutely. And in that vein, do we want to keep CSS modules or move to something like emotion that we use elsewhere? Personally I'd be happy to get completely rid of external CSS files if we can, but maybe it's not worth the work.

**Comment by burakukula** [comment]
This sounds like a great idea!
Regarding dropping the CSS file. I'm just thinking about maybe some case like... dunno, supporting static pages or something not necessarily build with react. Is that even a case? Would we be able to build, let's say just HTML markup and use the CSS that we currently expose?

**Comment by denkristoffer** [comment]
I think CSS-in-JS would help simplify use of the library. No more having to import CSS files at all or even know about them. IMO it's also a bit nicer when developing, having the style right there in the component.

**Comment by m10l** [comment]
@burakukula I don't think that'd be a valid use-case. Our users are using F36 to build applications, and the CSS we currently export is not fit for just using outside of React anyway as we're using the css module hashes in the classnames.

So with that being said, **I don't think switching to emotion would be a breaking change**
