### ISSUE TITLE
🐛 Bug - `v3.63.3` breaks Button and Select styles

### ISSUE THREAD

**Issue by gregoralbrecht** [contentful/forma-36#663]
# Forma 36 bug report

## Summary

You are probably already aware of it, but `@contentful/forma-36-react-components@3.63.3` breaks some styles for me. I didn't do anything differently with `v3.63.2` and it works.

I started working on a UI extension yesterday which looks like this:

```jsx
import {
  Button,
  SelectField,
  Option,
} from '@contentful/forma-36-react-components'

const Sidebar = () => {
  return (
    <div className={styles.container}>
      <div className={styles.select}>
        <SelectField
          id="selectEnvironment"
          name="selectEnvironment"
          labelText="Select environment"
          onChange={event => setEnv(event.target.value)}
          width="full"
          willBlurOnEsc
        >
          <Option value="next">Next</Option>
          <Option value="production">Production</Option>
        </SelectField>
      </div>
      <Button
        buttonType="primary"
        isFullWidth
        onClick={() => console.info(`Deploying to ${env}...`)}
      >
        Deploy content
      </Button>
    </div>
  )
}
```

After running `yarn install` again today, I saw broken styles:

## `v3.63.3`
![image](https://user-images.githubusercontent.com/6179211/100341424-d5ba5080-2fdc-11eb-8b37-1d1f10c13d50.png)

## `v3.63.2`
![image](https://user-images.githubusercontent.com/6179211/100341508-ee2a6b00-2fdc-11eb-9a55-7d0f74143a19.png)

**Comment by denkristoffer** [comment]
Hi @gregoralbrecht, thanks for reporting this. Just to be sure, are you importing both the styles and tokens in the project?

**Comment by gregoralbrecht** [comment]
@denkristoffer Yes, I imported them in the root component. The only thing that changed between these two screenshots was that I ran `yarn add @contentful/forma-36-react-components@3.63.2` which fixed the missing styles. It's weird, though, because the `<Tabs>`, `<Tab>`, and `<TabPanel>` still worked.

**Comment by denkristoffer** [comment]
[3.63.3](https://github.com/contentful/forma-36/releases/tag/%40contentful%2Fforma-36-react-components%403.63.3) doesn't contain any changes that should affect this, so my initial thought is that there's something else going on as well, perhaps an update of some underlying dependency. Would it be possible for you to share the two lock files before and after updating?

**Comment by gregoralbrecht** [comment]
Sorry, I can't share the lock file since this is client work. If you can't reproduce this it might be an issue on our end, though. Just wanted to raise in case you wanted to know :)

**Comment by denkristoffer** [comment]
@gregoralbrecht Are you able to upgrade to the latest version and see if the problem is still there?

**Comment by denkristoffer** [comment]
Nevermind, the issue has been found and is being worked on 🙂

**Comment by gregoralbrecht** [comment]
Sorry for the late reply. Glad you found it, makes sense it was missing CSS variables. Thanks for fixing it! :)
