### ISSUE TITLE
💡 Proposal - All contributors

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#676]
# Forma 36 contribution proposal

Let's set up [All Contributors](https://allcontributors.org/) to credit and appreciate everyone who contributes to Forma 36 😄

**Comment by denkristoffer** [comment]
@all-contributors please add m10l for code, maintenance

**Comment by denkristoffer** [comment]
@all-contributors please add wichniowski for code, maintenance

**Comment by denkristoffer** [comment]
@all-contributors please add burakukula for code, maintenance

**Comment by denkristoffer** [comment]
@all-contributors please add mshaaban0 for code, maintenance

**Comment by denkristoffer** [comment]
@all-contributors please add gui-santos for code, maintenance

**Comment by gui-santos** [comment]
@all-contributors please add @gui-santos for code, maintenance

**Comment by denkristoffer** [comment]
@all-contributors please add @gui-santos for code, maintenance

**Comment by denkristoffer** [comment]
@all-contributors please add @mshaaban0 for code, maintenance

**Comment by denkristoffer** [comment]
@all-contributors please add @burakukula for code, maintenance

**Comment by denkristoffer** [comment]
@all-contributors please add @domarku for design

**Comment by denkristoffer** [comment]
@all-contributors please add @denkristoffer for code, maintenance

**Comment by denkristoffer** [comment]
@all-contributors please add @suevalov for code, maintenance

**Comment by denkristoffer** [comment]
@all-contributors please add @Gracegross for design

**Comment by denkristoffer** [comment]
@all-contributors please add @miretxu for code

**Comment by denkristoffer** [comment]
@all-contributors please add @burakukula for doc

**Comment by denkristoffer** [comment]
@all-contributors please add @mshaaban0 for doc

**Comment by denkristoffer** [comment]
@all-contributors please add @gui-santos for doc
