### ISSUE TITLE
🐛 Bug - Unable to import f36 CSS from create-contentful-app project

### ISSUE THREAD

**Issue by kamsar** [contentful/forma-36#704]
# Forma 36 bug report

## Summary

Apps created with `create-contentful-app` can no longer import f36-react-components CSS.

This occurred somewhere between 3.67.6 and 3.68.8 according to dependabot on our app's repo.

## Environment

Netlify build/local dev (windows 10/node 12.18.3)

## Steps to reproduce

```bash
npm init react-app contentful-bug-repro
cd contentful-bug-repro
npm i @contentful/forma-36-react-components
```

Open `src/index.js` and add this line [which is present in `create-contentful-app`](https://github.com/contentful/create-contentful-app/blob/9546a18eb5584efe8afcbdc27e72ddef6cf6aec3/template/src/index.tsx#L15):

```
import '@contentful/forma-36-react-components/dist/styles.css';
```

Run a build:
```
npm run build
```

## Expected results

I get the f36 CSS imported.

## Actual results

```
yarn build
yarn run v1.22.10
$ react-scripts build
Creating an optimized production build...
Failed to compile.

./node_modules/@contentful/forma-36-react-components/dist/styles.css
ParserError: Syntax Error at line: 1, column 23


error Command failed with exit code 1.
```

**Comment by denkristoffer** [comment]
Thank you @kamsar, we'll get this fixed.

**Comment by denkristoffer** [comment]
@all-contributors please add @kamsar for bug

**Comment by kamsar** [comment]
3.71.3 seems happy on our build. Thanks!
