### ISSUE TITLE
🐛 Bug - Table row hover state overflows border radius

### ISSUE THREAD

**Issue by andipaetzold** [contentful/forma-36#801]
# Forma 36 bug report

## Summary

When hovering the bottom row of a table, the background color overflows the border in the bottom left and bottom right.

This was probably introduced with the latest visual style update as there was (I think) no border-radius before.

## Environment

Chrome, Safari, Firefox

## Steps to reproduce

https://f36.contentful.com/components/table/

Zoom to the bottom left of the table and hover the last row

## Expected results

The background color should not overflow the table border.

## Actual results

<img width="612" alt="Screenshot 2021-01-21 at 16 31 24" src="https://user-images.githubusercontent.com/4947671/105372651-1c57b000-5c06-11eb-8183-e2171b4ecb2c.png">

**Comment by denkristoffer** [comment]
Thanks for catching this, I'm taking a look 🙂

**Comment by denkristoffer** [comment]
@all-contributors add @andipaetzold for bug
