### ISSUE TITLE
🐛 Bug - Tooltip doesn't disappear when wrapping disabled elements

### ISSUE THREAD

**Issue by andipaetzold** [contentful/forma-36#805]
# Forma 36 bug report

## Summary

When wrapping `<Tooltip>` around a disabled element e.g. a `<button>`, the tooltip shows up when hovering over the button but does not disappear when leaving the button. The tooltip then just stays visible. It doesn't even disappear when clicking.

It did some first debugging and it seems like `onMouseEnter` triggers correctly but `onMouseLeave` doesn't.

This seems to be a common problem: https://github.com/facebook/react/issues/4251

A potential fix is using `onPointer(Enter|Leave)` or `onMouseOut`. `onPointer(Enter|Leave)` might not be eligible because of it's new and not supported by older browsers.

## Environment

* Chrome is broken
* Safari is broken
* Firefox works

## Steps to reproduce

https://codesandbox.io/s/relaxed-mendeleev-xl87p?file=/src/index.js

## Expected results

The tooltip should disappear when the mouse leaves the button

## Actual results

The tooltip doesn't disappear

**Comment by denkristoffer** [comment]
Looking into this it seems to happen every time on a regular `<button />`, not on Forma 36's `<Button />`, `<TextLink />`, etc. 🤔

**Comment by denkristoffer** [comment]
@andipaetzold Can you try this branch and see if it solves your problem? https://github.com/contentful/forma-36/tree/fix-tooltip-on-disabled-element

**Comment by andipaetzold** [comment]
Hm - I also can't reproduce it in code sandbox, but it's broken in a private project. Will try that branch and let you know :)

**Comment by andipaetzold** [comment]
That seems to fix it.
