### ISSUE TITLE
💡 Proposal - v4 package renaming

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#811]
## The problem

Forma 36 package names are very long and with the new build setup there'll be a lot of typing!

## The proposed solution

Rename existing packages to use the shorter "f36" moniker:

- `@contentful/forma-36-react-components` → `@contentful/f36-components`
- `@contentful/forma-36-tokens` → `@contentful/f36-tokens`

Use the moniker for new packages as well:

- `@contentful/f36-base`
- `@contentful/f36-typography`
- `@contentful/f36-workbench`
- `@contentful/f36-modal`
- `@contentful/f36-icon`
- `@contentful/f36-card`
- `@contentful/f36-button`
- `@contentful/f36-skeleton`
- `@contentful/f36-input`
- `@contentful/f36-form`
- `@contentful/f36-tab`
- `@contentful/f36-note`
- `@contentful/f36-notification`
- `@contentful/f36-switch`
- `@contentful/f36-spinner`
- `@contentful/f36-tag`
- `@contentful/f36-dropdown`
- `@contentful/f36-accordion`
- `@contentful/f36-autocomplete`

## Later work

Maybe we can group some packages in a core package:

`@contentful/f36-inputs`, `@contentful/f36-forms`, `@contentful/f36-base`, and `@contentful/f36-typography` → `@contentful/f36-core`

We should cut this from the initial scope since it makes sense to first investigate what packages our users would want grouped into such a core package. See https://github.com/contentful/forma-36/issues/811#issuecomment-768113163

**Comment by gui-santos** [comment]
Yes! +100

**Comment by nikazawila** [comment]
that's real neat! 👌🏻

**Comment by mshaaban0** [comment]
100% want 🙌 
One recommendation from my side is to reduce the number of packages needed to get started, maybe include `typography`, `button` and `form-elements` in `base` or `core`? since these components are used in almost all views!

**Comment by denkristoffer** [comment]
I like that idea @mshaaban0 👍 Added to OP.

**Comment by nikazawila** [comment]
I don't disagree, but I think before we go ahead and create `core`, we could use a quick survey of what actual clients of f36 would expect to see there, as for example, for me `core` should also include icons and cards, but... it isn't really about me - so knowing the expectations from people using it in their projects would be pretty good before we make assumptions for them.
