### ISSUE TITLE
🐛 Bug - Using TextField with textarea prop showing value undefined.

### ISSUE THREAD

**Issue by imshuffling** [contentful/forma-36#824]
# Forma 36 bug report

## Summary

Using the TextField component with textarea prop is showing value undefined.

![image](https://user-images.githubusercontent.com/739061/106924892-75940900-6707-11eb-9300-6776b10a215b.png)

## Environment

Chrome, Mac OS 13"

## Steps to reproduce

- Creating a TextField component using the Forma36 library
- When you start typing into the input the onchange event fires and the undefined message appears.

```
  const [exercises, setExercises] = useState(fieldValue || []);
...

  // update contentful field value whenever exercises data changes
  useEffect(() => {
    const sanitizedExercises = exercises.map((exercise) => {
      console.log("exercise ", exercise);
      return {
        title: exercise.name,
        id: exercise.id,
        note: exercise.note,
      };
    });
    props.sdk.field.setValue(sanitizedExercises);
  }, [exercises, props.sdk.field]);

...

// On change handler
  const onNoteChanged = (e) => {
    const exerciseIndex = e.target.dataset.index;
    const updatedExercises = [...exercises];
    updatedExercises[exerciseIndex].note = e.target.value;
    setExercises(updatedExercises);
  };

...

{/* This shows a error of undefined */}
<TextField
  labelText={"Notes"}
  value={exercise.note}
  data-index={index}
  onChange={onNoteChanged}
  textarea
/>

{/* This works */}
<textarea
  value={exercise.note}
  data-index={index}
  onChange={onNoteChanged}
/>
```

Full code here - https://gist.github.com/imshuffling/b378c0716c4f1721f1b4e494c3245b36

## Expected results

Value gets stored on state change and when the page is saved.

## Actual results

When typing the onchange event fires and an error appears showing value is undefined.

cc: @davidfateh for reference.

**Comment by denkristoffer** [comment]
Hi @imshuffling 👋 I think the issue here is your `data-index` attribute. `TextField` passes all unknown props to the wrapper element, which is a div, so the `data-index` attribute is `undefined` in your event handler.
