### ISSUE TITLE
💡 Proposal - Tag vs Pill

### ISSUE THREAD

**Issue by burakukula** [contentful/forma-36#841]
# Tag and Pill migration in v4

## The problem
Hey everyone!

Currently, we have 2 components that might be confusing.
`<Tag />` which is mostly used for labeling of highlighting elements in the interface

Example:
<img width="126" alt="Screenshot 2021-02-18 at 15 01 33" src="https://user-images.githubusercontent.com/4446634/108368012-477bf200-71fa-11eb-82a0-35170ddada58.png">

`<Pill />` which is used for tagging elements in the interface

Example:
<img width="256" alt="Screenshot 2021-02-18 at 15 01 38" src="https://user-images.githubusercontent.com/4446634/108368068-582c6800-71fa-11eb-8b0b-539c038defa4.png">

I think in order to achieve more consistency in naming we could migrate those 2 components in v4 to align their names with their purpose

## The proposed solution
1. Migrate `<Tag />` to `<Label />`:
 - create a separate package for `<Label />` that will contain current `<Tag />`
 - I would like to introduce a set of "filled" Labels. Currently, we have only `filled-primary` and I wish we have a full set, the same as we have with the default (light) state. **Downside** - they look a bit like Buttons to me 😕
Fixing my own bug: I've got to the conclusion, that it would be better to create `solid` boolean property for the component, instead of for example `tagType="primary-filled"` it would be something like:
 
 ```
 <Label labelType="primary" size="small" solid>new</Label>
 ```
 This is how it potentially would look like (more or less):
<img width="316" alt="Screenshot 2021-02-17 at 15 19 34" src="https://user-images.githubusercontent.com/4272331/108217147-8dba4e00-7133-11eb-8fa8-4f0c0a0aa3cd.png">

2. Migrate `<Pill />` to `<Tag />`, with the existing functionalities of `Pill`. Maybe we would like to extend the color set of `Pill`? is there a usecase for having more colors for this component?

## Breaking changes
v4

## Open questions:
 - do we agree to the proposed naming or maybe we would like to migrate `<Tag />` to something like `Badge`?
 - do we want to create `solid` labels (current Tags) and do we have any objections against the `solid` boolean prop? 
 - do we want to extend the colors set for `<Pill />` (future Tag) component - more details #585?

**Comment by burakukula** [comment]
Additional changes for the `<Pill />` component are mentioned in here https://github.com/contentful/forma-36/issues/585

**Comment by gui-santos** [comment]
I think I missed the discussion about the reason behind having two similar components, could you show me?

IMO, Label is a confusing name because for me Label is a component related to the `<label>` tag used in forms
so I suggest using other name: Tag or Badge

The boolean prop idea is great 🙌

**Comment by denkristoffer** [comment]
> IMO, Label is a confusing name because for me Label is a component related to the <label> tag used in forms so I suggest using other name: Tag or Badge

I like Badge 👍

**Comment by burakukula** [comment]
@gui-santos @denkristoffer thx for the feedback!
Badge sounds good! (I don't think we ever will have any gamification or something similar going on in the product, where users could achieve, win some badges, so it seems safe to take this namespace for this purpose) 😁

@gui-santos the issue that we have right now is that the current `<Tag />` component is not really used for tagging, it is used for highlighting/labeling elements. The `<Pill />` component is actually used for tags. That's why we could migrate:
the current `Tag` -> `Badge` 
the current `Pill` -> `Tag`

WDYT?

**Comment by m10l** [comment]
Updated with screenshots for clarity.

+1 for not using Label.

I like `Tag` -> `Badge` and `Pill` -> `Tag`. I think the key thing that differentiates these components is that our current Pill component is more aimed at being interactive, and the Tag component is for conveying status.

**Comment by domarku** [comment]
I like `badge`, too.

I think we could avoid the `solid` ones looking like buttons by setting a darker shade than the ones used on buttons. So, instead of `--color-smth-mid` we could use the `--color-smth-base`.

**Comment by denkristoffer** [comment]
I'm +1 on both renames although I see the problem with renaming one package to something that already exists. Which is worse, confusing newcomers (because our current `Pill` is not what you'd expect) or oldtimers 😅 I think I prefer the latter as it's more "future proof".

**Comment by burakukula** [comment]
Yeah, it might be tricky to migrate, that's true. But I think the proposed naming convention is more accurate and reflects better how those components are used. So yeah.. I still vote for migrating both components to the new naming:
`Tag` -> `Badge`
`Pill` -> `Tag`

`Pill` is probably not used very often - of course, I am not sure about it, but for example in the user interface is used 9 times in 6 files. This does not mean it is not used often by customers, but I would assume it's not a very popular component.

**Comment by artibella** [comment]
I am also +1 for renaming both. But I could see some issues if we repurpose the existing `Tag` to become the `Pill` component (event though it is a better name for it).

I did some quick research to see how other design systems name our current `Pill` component: 
https://material.io/components/chips#usage
https://atlassian.design/components/tag/examples
https://www.carbondesignsystem.com/components/tag/usage
https://www.lightningdesignsystem.com/components/pills/

What is unique to our current `Pill` is that we also have a draggable state. Haven't seen that in any other Design System.

Naming is hard  :)

**Comment by suevalov** [comment]
Agree with @denkristoffer on

> I see the problem with renaming one package to something that already exists

If we rename both, the migration path will be extremely confusing and it will hard to write an automated codemode for that.

**Comment by suevalov** [comment]
As for me, the current `Pill` component doesn't sound wrong and I don't a solid reason to complicate v3 => v4 migration.

**Comment by burakukula** [comment]
@suevalov sure. I understand that it might be confusing and it is a complication for the v3 -> v4 migration. The main argument from my side is that the `Pill` component is actually used for tagging right now, but of course, it can be used for other stuff too. We can live with `Pill` name I guess.
Naming is the worst :)

**Comment by suevalov** [comment]
It's settled:

`Tag` is renamed to `Badge` => #857 

`Pill` component stays as it is
