### ISSUE TITLE
💡 Proposal - consistent use of React references

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#849]
# Forma 36 contribution proposal

## What?

:wave:

Forma 36 doesn't currently handle React references in a consistent way (see #267). As we've talked about, v4 provides a good opportunity to take care of this. To get this consistency I suggest we always forward the reference to the root element, no matter what.

## How?

For most of our components it's pretty straightforward, we use `React.forwardRef` and set the `ref` on the outermost element in the component. 

It gets a bit more complicated for some of our components. We have a lot of them wrapped in for example a `<div>`, and for consistency I suggest we still send the reference to that element instead of whatever component is inside it. Contrived example:

```tsx
import React, { forwardRef } from 'react'

interface TextFieldProps {
  ...
}

const TextField = forwardRef<HTMLHeadingElement, TextFieldProps>(
  function TextField(props, forwardedRef) {
    return (
      <div ref={forwardedRef}>
        <input {...props} />
      </div>
    )
  }
)

export default TextField
```

In the above example users probably DO often want the reference to the `<input>` and not the `<div>`, but I think it's better for us to stay consistent. Instead maybe we can cut down on our use of wrapping elements. 

## Open questions

I need your help in coming up with solutions for what to do in situations where we are throwing multiple references around. Should we export them all, or just the root?

**Comment by mshaaban0** [comment]
Isn't this covered by the upcoming `<Primitive />` component? 🤔

**Comment by denkristoffer** [comment]
@mshaaban0 Even with `<Primitive />` we would still have to use `forwardRef()` in every component and pass the refefence to `<Primitive />`, but it should take care of the part of deciding which element to set the reference on.

**Comment by suevalov** [comment]
It's covered by Primitive. Check out for Box, Flex, Grid implementations.

**Comment by denkristoffer** [comment]
We still have the open question to answer. Like the TextField component, the root ref goes to a wrapper `div`, so should we also export a ref to the `input` itself?

**Comment by gui-santos** [comment]
> We still have the open question to answer. Like the TextField component, the root ref goes to a wrapper `div`, so should we also export a ref to the `input` itself?

Yes! We need export refs for the inputs, it's the main problem in the current solution IMO
So I guess in components where there is a wrapper and other components inside of it
we will need to export the ref of everyone, no?

**Comment by denkristoffer** [comment]
Maybe we can come up with a naming convention for our refs, so that they're easy to access.
`secondaryRef`? `componentRef`? `inputRef`? Last one is clearer but would have to be custom named on a case by case basis.

**Comment by gui-santos** [comment]
> Maybe we can come up with a naming convention for our refs, so that they're easy to access.
> `secondaryRef`? `componentRef`? `inputRef`? Last one is clearer but would have to be custom named on a case by case basis.

I actually like the case by case basis solution. But with some codestyle rules like
the container ref is always `containerRef` or `wrapperRef` or something like that
and the other refs are `{element tag or f36 component}Ref` (e.g. inputRef, textareaRef, labelRef, iconRef, headingRef)
if the component exposes only one ref, it's called `ref`
