### ISSUE TITLE
🐛 Bug - Card overflows on Linux Chrome

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#858]
# Forma 36 bug report

## Summary

Card has a vertical scrollbar as seen here:

![Screenshot_2021-03-05_12-59-28](https://user-images.githubusercontent.com/219017/110115975-24833d80-7db7-11eb-891c-36eea01b1dea.png)

This seems to be a Chrome on Linux issue, I haven't been able to reproduce it on macOS.

## Environment

Chrome on Manjaro Linux

## Expected results

No scrollbar should be shown

**Comment by suevalov** [comment]
@denkristoffer could you please test v4 on Linux and see if the problem is still there?
