### ISSUE TITLE
🐛 Bug - MultipleMediaEditor iFrame has no height

### ISSUE THREAD

**Issue by benj3** [contentful/forma-36#860]
# Forma 36 bug report

## Summary

The MultipleMediaEditor component does not resize with its content.

## Environment

Chrome, Windows

## Steps to reproduce

Created a new Field Editor contentful extensions and followed the example here: https://contentful-field-editors.netlify.app/media-multiple

## Expected results

The height of the field should grow with its content by a height set on the iframe html element but that is missing.

## Actual results

The height of field does not grow and instead adds a scrollbar to the content see attached image.

![image](https://user-images.githubusercontent.com/1052915/110146224-39b99580-7dd2-11eb-8629-0b60b93568a7.png)

**Comment by suevalov** [comment]
Hi @benj3,

In order to make your Extension/App autoresizable you need to call `sdk.window.startAutoResizer()` in our code. Call it once and the iframe will listen for all content size changes and will expand itself automatically if something overflows.

**Comment by benj3** [comment]
Thanks :)
