### ISSUE TITLE
💡 Proposal - Polymorphic base component

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#861]
# Forma 36 contribution proposal 

👋 

After one of our recent talks I dug into [Radix UI](https://radix-ui.com/) a bit, as it was one of the interesting component libraries and design systems you mentioned. One of the concepts they use, one I've also seen in [Blueprint](https://blueprintjs.com), is having a polymporphic base component that all other components build on.

## Why?

The biggest win of such a polymorphic base component, as I see it, is that it gives us a place to collect props and capabilities that should be shared across all our components. In v3 that would be props like `testId` and `className`.

## How?

I've added a draft of what such a component could look like for us, based on Radix. It forwards references, adds the `testId` prop and, more interestingly, the `as` prop that gives the component the polymorphic capabilities that lets us render components with different tags when we want to.

So the idea is that we consistently use the component for our root element. Here's a pseudo code example. **This will NOT be the final API**:

```tsx
import React, { forwardRef } from 'react'
import { css } from '@emotion/core'
import tokens from '@contentful/f36-tokens'

import Primitive from '../Primitive'

interface HeadingProps {
  ...
}

const Heading = forwardRef<HTMLHeadingElement, HeadingProps>(
  function Heading(props, forwardedRef) {
	return (
	  <Primitive
	    as="h1"
	    css={{
	      fontWeight: tokens.fontWeightDemiBold
        }}
        ref={forwardedRef}
	    {...props}
	  />
    )
  }
)

export default Heading
```

```tsx
import React from 'react'
import { Heading } from '@contentful/f36-typography'

export default function Component(): React.ReactElement {
  return <Heading>This is a h1 element</Heading>
}
```

## Why not?

The con I see is trading added complexity for an easier way to follow convention.

## What next?

I'm working on a PR with code and will let you know when there's something concrete and working to look at 🙂

**Comment by suevalov** [comment]
Closed by #830
