### ISSUE TITLE
💡 Proposal - useKeyboard hook in f36-utils

### ISSUE THREAD

**Issue by mshaaban0** [contentful/forma-36#885]
## The problem

I see in our code base we have many approaches devs takes to listen to keyboard events and detect keycode, ..etc.

```js
const handleKeyUp = (e: React.KeyboardEvent) => {
    if (KeyCodes.esc(e)) {
      hidePanel();
    }
 };
document.addEventListener('keyup', (handleKeyUp as unknown) as EventListener);
return () => document.removeEventListener('keyup', (handleKeyUp as unknown) as EventListener);
```

That I believe we can make simpler, and since it's considered as interactions, I believe it would fit well in F36

## The proposed solution

A simple hook that accepts a reference or a document, adds/remove the events on mount and unmount, and finally emits callback functions

Also maybe some predefined ones for what we think is the most keyboard buttons we need to listen to?

```js
const { onEsc, onEnter, onKey } = useKeyboard(ref | document);

onEsc(() => alert('👹'))

onKey('h', () => alert('hello'))
```

## Common A11y Keyboard interactions

See full list https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Grid_Role#keyboard_interactions

Key | Action
-- | --
→ | Moves focus to the right. 
← | Moves focus to the left.
↓ | Moves focus down.
↑ | Moves focus up.
Page Down | Moves focus down an author-determined number of rows.
Page Up | Moves focus up an author-determined number of rows.
Home | Moves focus to the first cell in the row that contains focus.
End | Moves focus to the last cell in the row that contains focus.
ctrl + Home | Moves focus to the first cell in the first row.
ctrl + End | Moves focus to the last cell in the last row.

Or 

Key combination | Action
-- | --
ctrl + Space | Select the column that contains the focus.
shift + Space | Selects the row that contains the focus.
ctrl + A | Selects all cells.
shift + → | Extends selection one cell to the right.
shift + ← | Extends selection one cell to the left.
shift + ↓ | Extends selection one cell down.
shift + ↑ | Extends selection one cell up.

**Comment by denkristoffer** [comment]
For simple keypress listeners my initial thought is that this is overkill, but maybe if we use more advanced keyboard functionality like hotkeys anywhere, this could be worth pursuing?

**Comment by mshaaban0** [comment]
@denkristoffer I think with more a11y work coming up we would need this badly, I added some common keyboard interactions that we would want to support, for more reasoning.

**Comment by gui-santos** [comment]
I like it a lot!

**Comment by suevalov** [comment]
something like this? https://react-spectrum.adobe.com/react-aria/useKeyboard.html

**Comment by mshaaban0** [comment]
@suevalov Yes, with more events :)

**Comment by mshaaban0** [comment]
Worth adding:  https://f36.contentful.com/guidelines/keyboard-shortcuts/
