### ISSUE TITLE
🐛 Bug - Loading button spinner does not show

### ISSUE THREAD

**Issue by gui-santos** [contentful/forma-36#895]
# Forma 36 bug report

## Summary

![f36_spinner_bug](https://user-images.githubusercontent.com/6597467/112614018-10b08180-8e21-11eb-8bfb-9584061ec5eb.gif)

I'm not sure if this is an implementation bug or a format 36 bug
But in Contentful's web app we have some buttons where the three dots animated icon does not show up
and in some cases, it shows up but when the loading prop changes to false it disappears (expected) and it leaves a blank space for a few seconds 👀

**Comment by mshaaban0** [comment]
@gui-santos kind reminder, please take care of this.

**Comment by gui-santos** [comment]
Oops! I missed this msg

@denkristoffer the gif I saved is in the delete account modal in user_interface

but there are more buttons with the spinner in that project

**Comment by Chaoste** [comment]
> I'm experiencing a similar issue which I suspect might be related. I am flipping the `loading` flag based on if an asynchronous process is still running, keeping track of that status in state. I notice that whenever I flip the flag from `true` to `false` , it will still show the loading spinner after a brief moment. See code example and screen capture below:
> 
> ```js
> <Button
>   type="submit"
>   buttonType="positive"
>   disabled={!this.state.parameters.testValue?.length}
>   onClick={this.onClick}
>   loading={this.state.isButtonLoading}
> >
>   {this.state.isButtonLoading ? "Loading" : "Not Loading"}
> </Button>
> ```

Hey, I think I found a hotfix for now: `key={Date.now()}` or ```key=`my-button-${isLoading}````
It's ugly but somehow triggers one more render cycle and removes the animation - not in a smooth way but at least it's gone.

https://user-images.githubusercontent.com/9327071/132478465-04bfd932-2cad-4da0-bb20-feee47757806.mov

**Comment by Chaoste** [comment]
Here's the [final solution](https://github.com/contentful/forma-36/pull/1295) which hopefully fixes it for every context.

**Comment by Chaoste** [comment]
After testing in out tasks-app, I can confirm that this is fixed 👍🏻 

https://user-images.githubusercontent.com/9327071/132818102-da214a32-a870-498a-9309-cee524f6011b.mov
