### ISSUE TITLE
🐛 Bug - Modal controls issue

### ISSUE THREAD

**Issue by burakukula** [contentful/forma-36#896]
The issue might be an implementation problem, not really sure right now. 

<img width="1792" alt="Screenshot 2021-03-29 at 12 31 27" src="https://user-images.githubusercontent.com/4272331/112827596-da783980-908e-11eb-8d2e-de35963b299f.png">

I guess we actually don't need to calculate the width for the controls, or there is a reason to do it?

**Comment by denkristoffer** [comment]
Probably a bug. It's double the width of the padding, so it's probably a leftover where `box-sizing: border-box` could've been used instead?
