### ISSUE TITLE
💡 Proposal - Add full page wizard to forma

### ISSUE THREAD

**Issue by Gracegross** [contentful/forma-36#907]
# Forma 36 contribution proposal

## How to use the wizard

• Use full screen wizard when you need the users full attention towards the content
• Use full screen wizard for multiple step processes
• Avoid full screen wizard for information only
• Avoid full screen wizard for single step processes 
• Avoid full screen wizard in the middle of a user flow as it interrupts the workflow and forces attention towards the modal content, losing their current context
• Examples: subscription purchases (Team/Community), space mapping (Enterprise)

## Rules for wizard

_All pages_
• All pages have a progress indicator, "x" icon and title
• Title should be instructional (except review page)
• “x” icon top right returns users to their previous position
• CTA bar anchored to the bottom on page
• Bar is 90% transparency so we can see content below the bar
• CTA button is disabled until the page is completed then becomes enabled

_Progress indicator_
• Max number of steps is 5: if your workflow (or setup) has more than 5 steps, consider grouping them & using the stepper for the groups
• Use one word to describe each step. If you need to use more than one word, keep it short and clear.
• Blue circle indicates the page that the user is on
• Blue circle-check icon indicates completed page
• Mid-grey outlined circle for upcoming pages

 
![Full screen wizard-first step](https://user-images.githubusercontent.com/69515265/114720248-2803d000-9d38-11eb-9850-2735d5bbf210.png)

_Confirmation page_
• Confirmation page is second-last page in process if there is a review page OR last-page in process when there is no review page
• Confirmation page is where users are confirming action
• Green CTA leads to commitment (e.g. creation of new space, assignment of space to licence)

![Full screen wizard-confirm step](https://user-images.githubusercontent.com/69515265/114720219-1fab9500-9d38-11eb-8c62-e3ab29fbfdf0.png)

_Loading state_
• Use primary loading state on confirmation action
• “Done” message on completion
• Use secondary loading state as a backup with Forma spinner (third picture)

![Full screen wizard-loading state-done](https://user-images.githubusercontent.com/69515265/113731819-5dd20480-96f9-11eb-98b7-ddc541806313.png)
![Full screen wizard-loading state](https://user-images.githubusercontent.com/69515265/113731822-5f033180-96f9-11eb-8803-2e6e1834b68d.png)
![Full screen wizard-sec LS](https://user-images.githubusercontent.com/69515265/113731828-5f9bc800-96f9-11eb-95ab-432d4a72392b.png)

_Review page (optional)_
• Review page required if action taken is impactful & requires acknowledgement by users e.g. if billing is involved 
• Review page is final page
• If there is no review page, users require a toast notification to confirm changes
• CTA to other page of the web app (where makes the most sense)
• User receives success message that job is done and instructions on how to proceed

![Full screen wizard-done step](https://user-images.githubusercontent.com/69515265/114720139-0a366b00-9d38-11eb-8b84-feed1cd95904.png)

**Comment by gui-santos** [comment]
Wow! @Gracegross 

I loved that your proposal can already be used as the documentation for this new component 🙌 

I think this proposal has some new "Atomic" components and then a new "Molecule", you know what I mean?
Anyway, I think it's a cool idea
We can make it share some logic that we have around Modals 👌 

I vote 👍

**Comment by Gracegross** [comment]
> Wow! @Gracegross
> 
> I loved that your proposal can already be used as the documentation for this new component 🙌
> 
> I think this proposal has some new "Atomic" components and then a new "Molecule", you know what I mean?
> Anyway, I think it's a cool idea
> We can make it share some logic that we have around Modals 👌
> 
> I vote 👍

Yeah I know what you mean - should I create a separate proposal for the progress bar? or do you think all in one is OK?

**Comment by domarku** [comment]
Thanks for the contribution @Gracegross! It's really well thought out and, as Gui said, you've practically already written the documentation for it 🙇 

I have a couple of questions:
- instead of calling it a "progress bar", could we call it a "progress indicator", to avoid confusion with progress bars?
- have you considered other ways of treating the bottom bar to indicate there is content below the bar, instead of 90% opacity? perhaps adding a subtle shadow (see [notification](https://forma-36-react-components.netlify.app/?path=/story/components-notification--basic))? asking just because I don't think we use reduced background opacity anywhere in our product yet. @fabe any thoughts on this?

**Comment by Gracegross** [comment]
> Thanks for the contribution @Gracegross! It's really well thought out and, as Gui said, you've practically already written the documentation for it 🙇
> 
> I have a couple of questions:
> 
> * instead of calling it a "progress bar", could we call it a "progress indicator", to avoid confusion with progress bars?
> * have you considered other ways of treating the bottom bar to indicate there is content below the bar, instead of 90% opacity? perhaps adding a subtle shadow (see [notification](https://forma-36-react-components.netlify.app/?path=/story/components-notification--basic))? asking just because I don't think we use reduced background opacity anywhere in our product yet. @fabe any thoughts on this?

Totally agree the shadow is way nicer!! Let me update the prototypes.

Consider it now the *progress indicator*

**Comment by denkristoffer** [comment]
I really like the idea of this but I'm not convinced Forma 36 is the right place to build it. The way I see it F36 should be more about adding the progress indicator, the animated loading state, and maybe a page component, and it could be put together in an internal component library. Would you all say that it fits better in Forma 36?

**Comment by Gracegross** [comment]
> I really like the idea of this but I'm not convinced Forma 36 is the right place to build it. The way I see it F36 should be more about adding the progress indicator, the animated loading state, and maybe a page component, and it could be put together in an internal component library. Would you all say that it fits better in Forma 36?

Hey thats a good point. So we could do individual items for:
1. Full screen wizard (including "x" icon
2. Progress indicator
3. Bottom button bar (try and say that 7 times really fast)

WDYT?
