### ISSUE TITLE
💡 v4 Proposal - Combine button components

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#913]
# Forma 36 contribution proposal

## The problem

We currently have `Button`, `CopyButton`, `IconButton`, and `ToggleButton`. That's a lot of button components that do very similar things!

## The proposed solution

We combine the above components into just `Button`, which needs new APIs to replicate the functionality of the different components:

### CopyButton

I'm not convinced `CopyButton` has a place in a design system. It's a rather simple composition of other components that could be better suited for other code bases. My suggestion would be to remove it from Forma 36 and move it to the application that uses it.

### IconButton

`Button` takes an `icon` prop and render it as a value. If no text value is passed only the icon gets rendered.

### ToggleButton

The style of `ToggleButton` can be automatically applied when `Button` is rendered as a direct child of a new `ButtonGroup` component that would be based on the `ToggleButton.Group` component. However, this might be too much magic for designers working with the UI Kit, so for that reason I'm also open to keeping this component around.

**Comment by gui-santos** [comment]
Yes! 👍 

Every time I look at the IconButton I think "This is just the normal button without any text and an Icon" hahaha

**Comment by domarku** [comment]
Thanks for the proposal @denkristoffer! Sounds good to me.

Re: CopyButton — 100% agree it should be removed from Forma.

- For copying values from input fields, there's already a `withCopyButton` prop in [TextInput](https://f36-storybook.contentful.com/?path=/story/form-elements-textinput--basic)
- If there's a need to have one independently, use `Button` with an `icon` prop "Copy"

In **CopyButton**, what do you mean by:

> [...] move it to the application that uses it.

Re: ToggleButton — I agree it would be a bit too much magic to use something that's not really a button but more a stylized checkbox. Vote to keep it as is for now.

**Comment by denkristoffer** [comment]
@domarku

What I mean by "move it to the application that uses it" is that Forma 36 should provide the blocks to build a copy button, but that the actual implementation should be a part of the code that wants to use it. So it's in agreement with your point about `Button` with a "Copy" icon.
