### ISSUE TITLE
🐛 Bug - Stories for Modals are Blocked by Open Modal

### ISSUE THREAD

**Issue by Chaoste** [contentful/forma-36#915]
# Forma 36 bug report

## Summary

One can't view the example code in the storybook for modals. For all subsections, non-closable modals pop up which prevent the user from viewing the code or documentation.

## Environment
- MacOS 10.15.7
- Chrome 89.0.4389.90 (Official Build) (x86_64)

## Steps to reproduce
Visit https://f36-storybook.contentful.com/?path=/docs/components-modal--default

## Expected results
The modals only pop up via clicking on a button and can be closed by the user.

## Actual results
The modals are always visible and not closable.

**Comment by nikazawila** [comment]
Thanks @Chaoste for reporting, I'll take care of it.
