### ISSUE TITLE
💡 Proposal - colors tokens naming convention and migration

### ISSUE THREAD

**Issue by burakukula** [contentful/forma-36#922]
In order to make our pallet scalable, we are thinking about the new approach to color tokens naming.

Currently we expose colors tokens in the following way (it's the case in most of the cases, some exceptions are there, like 
`colorsElements`, where the naming is slightly different, but still similar):
```
'color-blue-dark': '#174E8C', 
'color-blue-base': '#2D64B3', 
'color-blue-mid': '#2E75D4', 
'color-blue-light': '#84B9F5', 
'color-blue-lightest': '#EDF4FC',
```
The upcoming update of the pallete would look like this for all the colors:
<img width="671" alt="Screenshot 2021-04-14 at 15 54 50" src="https://user-images.githubusercontent.com/4272331/114722032-c04e8480-9d39-11eb-8f84-60fea8e1d91a.png">
Based on that it would be maybe useful to migrate colors into slightly different naming convention.

## Approach to the migration

**Proposed tokens naming convention. We would have new tokens for GREY, BLUE, GREEN, RED, PURPLE, ORANGE, YELLOW in the following convention:**
```
blue-900: #003297
blue-800: #00379F
blue-700: #0044AF
blue-600: #0059C8
blue-500: #036FE3
blue-400: #40A0FF
blue-300: #93CCFF
blue-200: #CBEDFF
blue-100: #DCF2FF
```
**Colors Mapping for existing tokens and deprecation cases**

1. blue, green, purple, red, yellow will be mapped the same as blue. We could export both current colors with mapping and new color tokens, example for blue shades 👀 ➡️  https://gist.github.com/burakukula/73a3169063d5cee1c476127e1db2ddb8

2. grey - we would expose additional, new tokens and colors-contrast, colors-elements, colors-text will be mapped with those new tokens, something like that 👀 ➡️  
https://gist.github.com/burakukula/1d038f1481af414a12a41e00844c0722
![image](https://user-images.githubusercontent.com/4272331/114833776-3a314d00-9dd0-11eb-95a4-b6a4cd56d1ca.png)

3. Deprecate or remove coral, ice, mint and peach
  - 🔪  option 1: add deprecation note to those colors and map them to new shades from red, blue, green, and orange (@fabe maybe you could help out here). Remove those colors in v5.
 - 🔪  option 2: remove colors in v4 and add documentation for customers to which colors they should migrate they use those shades (we are using only `colorIceMid` - 3 times in the code - which we should migrate to other color anyway. We can do it even now, before the color migration).

4. Maybe we should deprecate semantic colors - open question to @fabe @domarku and Daniel (I don't know his GitHub profile 😬)

**Proposed migration plan:**

 1. Add new tokens and export both, old and new tokens
 2. Add deprecation note for old tokens and create migration documentation plan for customers
 4. Migrate tokens in our applications slowly (or hackathon style like last time 😁)
 3. Remove old tokens in v5
 
 Open questions:
  - maybe we would be able to provide some sort of script to allow customers to migrate their tokens to new namespaces?
  - what should we do with colors that we would like to get rid of - coral, ice, mint, peach and semantic colors - remove now or depracate and remove in v5?

**Comment by nikazawila** [comment]
I love this @burakukula 💕 
The migration plan sounds good and feasible, too!

**Comment by domarku** [comment]
Thanks @fabe for the elephant job you did on the new color palette and the migration plan and thanks @burakukula for the proposal.

Coral, Ice, Mint and Peach should be mapped to the new tokens: Red, Blue, Green and Yellow, respectively.

Would be curious to see if we can provide a script to migrate existing tokens to new namespaces.

**Comment by burakukula** [comment]
@domarku thx for feedback. 
Sure, we can map the Coral, Ice, Mint and Peach now. And we will be adding the note that we are deprecating now and remove them in v5, right?
What do we want to do with semantic colors? The same case - deprecate now and remove in v5?

**Comment by domarku** [comment]
That sounds like a good plan!

**Comment by denkristoffer** [comment]
Yes big +1 to this scale! Also, Daniel is @damann 😁 

I have some thoughts on deprecation, no conclusions, just some notes for now:

I'm not sure it's a good idea for us to plan for v5 changes already, who knows when such a release is coming, it could be months or it could be years. If we want to deprecate and remove the old scales we can instead choose to deprecate in a major of v3 and remove in v4, but this would impact a lot of our own applications and would require something like a hackathon, as you say. Unless we deprecate in v3, and ship the scales undocumented in v4, which would allow us to remove them whenever we want to 🤔 

However, it doesn't seem like a big deal to support the old semantic names for now, so maybe the way to go here is really just to do that for now?

**Comment by damann** [comment]
The Semantic colors should also be mapped. Same story as with the rest - deprecate now and remove in v5.

**Comment by damann** [comment]
So if I understand it correctly the token naming includes the HEX value? Would it make sense to keep it more flexible / abstract by just using the numbering (blue-100, blue-200 …)?

**Comment by domarku** [comment]
@denkristoffer
> I'm not sure it's a good idea for us to plan for v5 changes already
That's a good point!

@damann the token names are not going to contain hex values, that's just the mapping

**Comment by burakukula** [comment]
@denkristoffer hmm, it's a tricky one. I guess if we release a new scale in minor v3, we still would have time to migrate on our side. Until v4 is finished we still have some time, I guess. 
The problem that I see with that approach is the fact that probably this is quite a big visual change for users, the pallet will change quite a lot, maybe we need some additional communication around this topic ( correct me if I'm wrong, I might be wrong, dunno, speculating ). 
Despite that, I still think we can do it in v3. 🚀
We would maybe need to plan some additional time for the migration. I guess it would be good to do the hackathon style, like we did last time. This way, we will be sure that all our colors are migrated at the same time (avoid two different shades of the same color in the application next to each other - which would be potentially possible if we migrate slowly).
The benefit of that is that we would have one thing less for the v4 migration 🎉
WDYT? v3 minor change + deprecation notes + hackathon + maybe remove in v4? 😁

**Comment by mshaaban0** [comment]
## Notes
* Keep semantic naming and map to the new tokens
* Map the current tokens in V3, deprecate in V4, and remove in V5
* Prepare a code-mod to migrate from old tokens to new tokens
