### ISSUE TITLE
💡 Proposal - Sticky notifications and errors

### ISSUE THREAD

**Issue by denkristoffer** [contentful/forma-36#926]
# Forma 36 contribution proposal

## The problem

Our `Notification` component is one of the primary methods we use to tell users of anything going wrong in our applications. A problem I see with this is that the notification automatically dismisses itself after a set amount of time, and there's no API to make a notification "sticky" so that it stays until the user dismisses it manually. What happens if the user is not looking at the screen when the error appears? I can imagine clicking "Publish", going for a cup of coffee—or just switching to a different tab in your browser—and coming back to a screen with a page that didn't publish and you've no idea why.

## The proposed solution

Notification should take a prop like `isSticky` (or something clearer) to make it stick around until it's dismissed. We should discuss with design if this should be default behaviour for all error notifications.

## Breaking changes

None

**Comment by suevalov** [comment]
I think there's a way to make them sticky already, but it's not so obvious from the API

**Comment by m10l** [comment]
Yup, this was added in using the duration prop - setting duration to 0 will mean it's never automatically dismissed.

**Comment by denkristoffer** [comment]
Aha! Well then, we can make the API better, but consider this mostly a design proposal for all errors then.

**Comment by mshaaban0** [comment]
@fabe to look into new Notification interaction https://vercel.com/design/toast

Notes: 
* Don't dismiss automatically if CTA is present
