### ISSUE TITLE
🐛 Bug - Autocomplete: chevron is clickable in disabled state

### ISSUE THREAD

**Issue by damienxy** [contentful/forma-36#931]
# Forma 36 bug report

## Summary

When the `disabled` flag is on in the Autocomplete component , the chevron is still clickable and dropdown items can be selected.

## Environment

Chrome / Mac

## Steps to reproduce

- set `disabled` to true in `Autocomplete` component
- click on the chevron
- select a dropdown item

## Expected results

Everything disabled, nothing is clickable or selectable

## Actual results

Chevron is clickable, opens the dropdown, options are selectable

**Comment by damienxy** [comment]
I will take a look at it

**Comment by denkristoffer** [comment]
@all-contributors please add @damienxy for bug
