### ISSUE TITLE
🐛 Bug - Primitive component performance impact

### ISSUE THREAD

**Issue by mshaaban0** [contentful/forma-36#948]
## Summary

We introduced `<Primitive />` component as a base component in V4 to ensure the correct usage of common props like `classNames`, `testId`, `style`, and `as`

We noticed the spread of the component actually consumes a lot of time to render the basic component in shadow DOM (See attached)

Let's use this issue to document our findings and find alternatives

## Results

<img width="477" alt="Screenshot 2021-05-04 at 15 09 00" src="https://user-images.githubusercontent.com/6163988/117010649-4a608c00-aced-11eb-8913-148239daebf6.png">

<img width="1490" alt="Screenshot 2021-05-04 at 15 17 43" src="https://user-images.githubusercontent.com/6163988/117010703-577d7b00-aced-11eb-9da4-b1c7f5d32cd1.png">

## Alternatives
TBD

**Comment by suevalov** [comment]
Thanks for bringing this up to the attention. I think it's possible to replace runtine Primitive component with a type-check only version by using https://radix-ui.com/primitives/docs/utilities/polymorphic

**Comment by denkristoffer** [comment]
@mshaaban0 also found some eslint plugins we can use to enforce code style as a kind of replacement for the shared props.

**Comment by burakukula** [comment]
-  we would take care of that later on in the process
 - we can have a look on the eslint now @mshaaban0

**Comment by suevalov** [comment]
Closed by #1069
