### ISSUE TITLE
🐛 Bug – toggle button box-shadow issues

### ISSUE THREAD

**Issue by damann** [contentful/forma-36#958]
<img width="458" alt="Screenshot 2021-05-07 at 16 04 10" src="https://user-images.githubusercontent.com/67584870/117461556-00c2ac00-af4e-11eb-96e1-ebd0237d5d76.png">

- Focus glow is overlapped by adjacent group button
- Corners of middle buttons are rounded (should be rectangular)

**Comment by burakukula** [comment]
@burakukula will have a look on this issue

**Comment by gui-santos** [comment]
@burakukula did you have a look on this one?

**Comment by gui-santos** [comment]
The PR #1109 created by @massao implementing the ButtonGroup component fixed this issue in v4 

![button_group](https://user-images.githubusercontent.com/6597467/126794306-94ac000d-8287-4629-ad56-be7f9529159a.gif)

I think we will only need to build the ToggleButton with ButtonGroup in v4 or make the ButtonGroup "togglable"

**Comment by suevalov** [comment]
Fixed in v4
