### ISSUE TITLE
🐛 Bug - AccordionItem doesn't resize after content dynamic content changes

### ISSUE THREAD

**Issue by PattoCF** [contentful/forma-36#962]
# Forma 36 bug report

## Summary
Accordion Item not resizing for dynamically changed content

## Environment
Google Chrome 90.0.4430.93

## Steps to reproduce

1. create sidebar app
2. added AccordionItem to it
3. Inside AccorditionItem render JSON output
4. Open JSON attributes
5. Content disappears under the next AccordionItem (see the attached video, https://user-images.githubusercontent.com/59477906/117800484-77fc8680-b253-11eb-903f-24bfa33e9510.mov)

I can also invite you to space where we are running the app for better troubleshooting

## Expected results
The additional content inside the AccordionItem would automatically increase the height to what is displayed inside.

## Actual results
Content is being cut off. Opening and closing the AccordionItem leads to the correct result.

**Comment by denkristoffer** [comment]
Maybe we can use a ResizeObserver to watch for dimension changes for the content and then resize the `AccordionItem`. For performance's sake we probably only want to attach it when some boolean prop is true, `isDynamicHeight` or something like that but better 😄

**Comment by burakukula** [comment]
@mshaaban0 will have a look and help out with this issue.

**Comment by gui-santos** [comment]
@mshaaban0 do you still want to do this?
