### ISSUE TITLE
💡 Proposal - Don't allow modals to overflow the view port height

### ISSUE THREAD

**Issue by damann** [contentful/forma-36#964]
# Don't allow modals to overflow the view port height

## The proposed solution

Remove the property `allowHeightOverflow`

## Breaking changes

Yes

**Comment by denkristoffer** [comment]
Like the top alignment for modals we cannot remove at the moment, but we can deprecate it 🙂

**Comment by burakukula** [comment]
- @fabe will have a look on the examples of usage on the client side
