### ISSUE TITLE
💡 Proposal - Notification - Dismiss on click outside of notification

### ISSUE THREAD

**Issue by domarku** [contentful/forma-36#966]
# Forma 36 contribution proposal

## The problem

People should be prevented from accidentally performing destructive actions in any system. That's why, when designing user experiences, we consciously and deliberately introduce friction.

More often than not, in Contentful, that friction is in the form of a confirmation dialog—an "Are you sure you want to do this?" modal. It works well for most use cases, but becomes too much friction when the user:

- performs a less destructive action
- does a repetitive task
- removes a less impactful item

Those and similar actions should be possible to do with less friction, but the user should also have the option to undo. 

We can use the Notification and persist it long enough for the user to have the ability to click on **Undo** in the Notification.

The problem is if the user doesn't need to undo their action and the notification just stays on the screen.

## The proposed solution

Extend the notification component with the option to persist the notification until the user clicks anywhere outside of it. Clicking outside of the notification would implicitly indicate they don't need to undo their action, but continue with other tasks.

(Related to #926)

https://user-images.githubusercontent.com/7631029/117976433-11996600-b330-11eb-9e33-3570e13b151f.mp4

## Breaking changes

I'm not sure, because I'm not sure how to implement it. I assume if it's an additional prop, like `keepOnScreen` then it's not a breaking change.

**Comment by burakukula** [comment]
- documentation regarding this pattern is needed, API provides this option already @domarku
