### ISSUE TITLE
💡 Proposal - Copy updates to forma page

### ISSUE THREAD

**Issue by Gracegross** [contentful/forma-36#978]
# Forma 36 contribution proposal

## The problem

Currently in the product the copy is inconsistent. We use different voices and there is inconsistency with capitalisation and date formats.

We have refreshed the UX writing guidelines to include delight PLUS adding some additional clarity on grammar and rules. A workshop was held with the PD to align on these principles. They have also been reviewed by Cassie, Daniel & Anna (technical writer)

## The proposed solution

[Here is the document](https://docs.google.com/document/d/1ScDiFZfjlQvfQ21DZqamBxktRBWg0WfzwUU3uhEmjtE/edit?usp=sharing) that describes the refreshed guidelines including: "UX Writing Principles" and "Grammar & rules"

This should replace the current information under the "Copy" tab on https://f36.contentful.com/

**Comment by denkristoffer** [comment]
@Gracegross Is the copy in the Google Doc ready for implementation on the website as is?

**Comment by Gracegross** [comment]
This would replace the current ones - but they include some of the current content.

So I took the current guidelines and refreshed them. @denkristoffer
