### ISSUE TITLE
🐛 Bug - Autocomplete Dropdown not closing after clicking outside of extension

### ISSUE THREAD

**Issue by AbhilashDawar** [contentful/forma-36#989]
I'm using Autocomplete component to create a UI extension to be used within Contentful space for one of the Content model. 

**Behavior:** When I click on the input field of the autocomplete component, but then click outside the area of extension without selecting any option from dropdown, the dropdown does not close.

**Expected:** Similar to Select or SelectField components, if Autocomplete component is clicked once and now focus is on the component and dropdown is open, if user clicks anywhere on screen without selecting any option from dropdown, it should still close the dropdown with options.

**Actual:** The dropdown closes if clicked within the extension area, but it remains open if clicked outside extension area. 

Addition (09/06/2021):
Behavior: The dropdown also remains open if some other component comes in focus (eg: rather than clicking outside of the component, I click some other component, like a RadioButton).
Also, In the similar situations as mentioned abovem the search query is not getting cleared while using the `willClearQueryOnClose` prop.

**Comment by gui-santos** [comment]
@Lelith

**Comment by suevalov** [comment]
@AbhilashDawar 

The problem you're facing is universal for all component libraries. Your extension is rendered inside of an iframe and Autocomplete listens only for events happening inside this iframe. Unfortunately, there's no way to close an autocomplete when the click happens outside of an extension (outside of iframe) without changing the way of how extensions and apps are working in Contentful.

We're not going to fix it in Forma. Thanks for understanding.
