### ISSUE TITLE
🐛 Bug - storybook doc should not show 'className' prop for SkeletonImage

### ISSUE THREAD

**Issue by heyitstowler** [contentful/forma-36#992]
# Forma 36 bug report

## Summary

The [storybook for Skeleton Image](https://f36-storybook.contentful.com/?path=/story/components-skeleton-skeletonimage--basic) shows that it takes a `className` prop but the TS typing doesn't allow a `className`
![image](https://user-images.githubusercontent.com/16481282/122432598-76fdf980-cf63-11eb-9045-7df288c9877c.png)
![image](https://user-images.githubusercontent.com/16481282/122432524-6483c000-cf63-11eb-9355-c978c61a3eb9.png)

## Environment

VSCode on a Mac

## Steps to reproduce

Import and use a SkeletonImage and try to add a `className` prop

## Expected results

Expected build to compile 

## Actual results

Build did not compile due to TS error

```
TypeScript error in /Users/christophertowler/Work/provider-finder/src/components/ProviderCard.tsx(40,35):
Type '{ className: string; width: number; height: number; }' is not assignable to type 'IntrinsicAttributes & SkeletonImageProps'.
  Property 'className' does not exist on type 'IntrinsicAttributes & SkeletonImageProps'.  TS2322
```

![image](https://user-images.githubusercontent.com/16481282/122432874-b1679680-cf63-11eb-9606-201dfc1e46d0.png)

![image](https://user-images.githubusercontent.com/16481282/122432524-6483c000-cf63-11eb-9355-c978c61a3eb9.png)

**Comment by denkristoffer** [comment]
Thanks for the report @heyitstowler 🙇 

I think the problem here is with the Storybook. I'm not sure it should be possible to style a skeleton image with CSS. Is this something you would like to be able to do? If so, can you say a bit about your use case?

**Comment by gui-santos** [comment]
I'm converting this to a bug on Storybook as @denkristoffer mentioned

This means that the problem is that in the documentation we are saying a `className` prop exists in the component, but that's not true

**Comment by denkristoffer** [comment]
@all-contributors please add @heyitstowler for bug
